/* test_ml_linreg_exact.js -- the LinearRegression solver accuracy contract.
 *
 * WHAT THE SOLVER PROMISES (the docs state the same):
 *   1. For a design the solver ACCEPTS, the coefficients ARE the ordinary
 *      least-squares solution up to rounding of the normal equations. The
 *      forced-optimum battery below pins that at <= 1e-9 relative (measured
 *      3e-16 .. 6e-10 across feature scales 1 .. 1e3); the independent oracle
 *      is numpy.linalg.lstsq (SVD), whose values are embedded (generated by
 *      tests/agent/t2d_ml_df_time/gen_linreg_oracle.py).
 *   2. The un-ridged system is accepted only while every pivot clears
 *      DYN_SOLVE_MIN_PIVOT = 1000*eps (~2.2e-13) of the largest diagonal
 *      entry of A^T A -- a cut that separates the elimination's own
 *      ROUNDING-LEVEL residue (measured <= ~2.4e-17 relative across the
 *      singular battery below; that residue IS rank deficiency and must go to
 *      the ridge) from a WELL-POSED design's genuine small singular value,
 *      which the normal equations solve to rounding. Below the cut the ridge
 *      solves: A^T A + lI with l = DYN_RIDGE = 1e-9, ABSOLUTE in the
 *      WEIGHT-NORMALIZED system (the system is divided by the mean sample
 *      weight first, so the load is 1e-9 x mean weight in raw units, and no
 *      product can overflow at 1e300 weights or underflow to 0 at subnormal
 *      ones). The load carries NO factor of the system's own scale: a
 *      scale-proportional load would zero every direction sitting far below
 *      the largest column -- the mixed-unit rows of section 7 pin that. The
 *      coefficients are then ridge-biased -- only IDENTIFIABLE quantities
 *      (predictions on consistent targets) are pinned, at <= 1e-4 on the band
 *      battery below.
 *   3. A SINGULAR design (duplicate/constant/collinear columns, identical
 *      rows, a zero column) does not throw, however its elimination rounds:
 *      its pivots sit at the rounding level the gate refuses, so the ridge
 *      fallback reaches them -- which an elimination refusing only exact
 *      zeros used to "solve" into 1/residue garbage. Section 5 is that band.
 *   4. The two input forms agree BIT-FOR-BIT: a dense fit and a CSR fit of
 *      the same reading produce identical coefficients (Object.is), on the
 *      un-ridged path and on the fallback alike.
 *   5. The weighted identities hold on the accepted path: all-ones weights
 *      are bit-identical to no weights, and a power-of-two weight scale is
 *      bit-identical to unit weights (the load is homogeneous in w).
 *   6. Well-posed near-singular designs ABOVE the gate solve EXACTLY
 *      (<= 1e-12, section 7) -- including when the target's true coefficients
 *      lie along the near-null direction, exactly what a ridge bias would
 *      shrink. Designs BELOW the gate (genuine rank deficiency, and the
 *      exactly-singular mixed-unit scales) are ridge-biased and pinned at
 *      <= 1e-6 on their identifiable quantities.
 *
 * Every system here is EXACTLY solvable by construction (integer design,
 * integer coefficients, integer targets), so `want`/`oraclePred` is the true
 * OLS answer and any deviation is solver rounding -- which is exactly what is
 * pinned. The band rows additionally carry the minimum-norm coefficients the
 * solver must not amplify past.
 *
 * Run: dynajs tests/test_ml_linreg_exact.js
 */
import { LinearRegression, CSR } from "dyna:ml";

let n = 0;
function assert(c, msg) { n++; if (!c) throw new Error("assertion failed: " + msg); }
function relerr(got, want) {
    return Math.abs(got - want) / Math.max(1, Math.abs(want));
}

/* Generated by tests/agent/t2d_ml_df_time/gen_linreg_oracle.py
 * (numpy 2.5.3, numpy.linalg.lstsq / SVD). Every system is exactly
 * solvable: integer design, integer coefficients, integer targets, so
 * the OLS solution IS `want` in real arithmetic and every deviation is
 * solver rounding. `oracle` is the independent SVD solve.
 * GOLDEN-START */
const SYSTEMS = [
    { name: "A", note: "4x4 identity block",
      X: [[1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 1, 1]],
      y: [3, 0, 4, 5],
      want: [2, -1, 3, 1],
      oracle: [1.9999999999999987, -1.0000000000000024, 2.9999999999999973, 1.0000000000000029] },
    { name: "B", note: "4x4 dense",
      X: [[1, 2, 3], [4, 5, 6], [7, 8, 10], [1, 1, 1]],
      y: [-2, -5, -8, 0],
      want: [1, -2, 0, 1],
      oracle: [1.0, -1.9999999999999976, -2.194499887496273e-15, 0.9999999999999986] },
    { name: "C", note: "4x4 scaled columns (integers stay exact)",
      X: [[2, 0, 0], [0, 3, 0], [0, 0, 4], [1, 1, 1]],
      y: [13, -17, 9, 3],
      want: [6, -6, 2, 1],
      oracle: [6.000000000000006, -5.999999999999997, 2.0000000000000044, 0.9999999999999851] },
    { name: "D", note: "features x 1e3",
      X: [[1000, 0, 0], [0, 1000, 0], [0, 0, 1000], [1, 1, 1]],
      y: [1001, 2001, 3001, 7],
      want: [1, 2, 3, 1],
      oracle: [1.0000000000000009, 1.999999999999999, 2.9999999999999982, 0.9999999999994842] },
    { name: "E", note: "features x 1e-3 equivalent (one large row)",
      X: [[1, 0, 0], [0, 1, 0], [0, 0, 1], [1000, 1000, 1000]],
      y: [2, 3, 4, 6001],
      want: [1, 2, 3, 1],
      oracle: [0.999999999999776, 2.000000000000113, 3.000000000000114, 0.9999999999998866] },
    { name: "F", note: "10x3 seeded random integers",
      X: [[8, -11, 12], [-8, -12, 12], [6, 7, 20], [-4, 14, -7], [3, 4, -12], [-13, -11, 7], [5, 18, 8], [-10, 17, 18], [10, 7, -15], [-17, -10, -2]],
      y: [71, 57, 57, -48, -36, 35, -2, 15, -44, 2],
      want: [1, -2, 3, 5],
      oracle: [1.0000000000000004, -2.0000000000000004, 3.0000000000000018, 5.000000000000007] },
    { name: "G", note: "25x4 seeded random integers",
      X: [[-43, 39, -3, 20], [-29, -18, -39, 24], [28, -28, 22, -42], [-11, -34, 25, -16], [-3, -4, -2, -24], [6, 32, 0, -31], [-48, -37, -42, -41], [-38, 10, 31, 36], [15, 10, -17, 44], [14, 23, 24, 36], [20, 43, 4, 5], [-25, 44, 5, -1], [-19, -23, 13, -5], [7, 17, 40, -17], [18, 41, -4, -25], [-21, -16, 13, -24], [34, -15, -44, -50], [-48, 13, -15, -22], [11, -44, 4, 12], [-47, -33, -11, -20], [46, -6, 15, -35], [31, -28, 27, -3], [-9, -2, 4, -25], [-38, -20, 49, -22], [17, -24, 34, -2]],
      y: [-45, 92, -123, -206, -60, -19, -102, -163, 204, 34, 90, -60, -149, -163, 54, -186, 156, -122, -10, -177, -5, -56, -102, -381, -120],
      want: [3, 1, -4, 2, -7],
      oracle: [2.9999999999999987, 0.9999999999999996, -4.000000000000002, 1.9999999999999984, -6.999999999999998] },
];
/* BAND-GOLDEN-START */
const BAND = [
    { name: "constcol k=1 (dyadic)", note: "constant column, dyadic ratio",
      X: [[1, 1], [2, 1], [3, 1]],
      y: [2, 4, 6], probe: [4, 1],
      w: null, realizable: true,
      oracleCoef: [2.0000000000000004, -5.652872529645036e-16, -5.652872529645036e-16],
      oraclePred: 8.000000000000002 },
    { name: "constcol k=2 (dyadic)", note: "constant column, dyadic ratio",
      X: [[1, 2], [2, 2], [3, 2]],
      y: [2, 4, 6], probe: [4, 2],
      w: null, realizable: true,
      oracleCoef: [1.9999999999999996, -6.274192149408993e-16, -3.137096074704497e-16],
      oraclePred: 7.999999999999997 },
    { name: "constcol k=4 (dyadic)", note: "constant column, dyadic ratio",
      X: [[1, 4], [2, 4], [3, 4]],
      y: [2, 4, 6], probe: [4, 4],
      w: null, realizable: true,
      oracleCoef: [2.0000000000000004, -6.475303296118805e-17, -1.618825824029701e-17],
      oraclePred: 8.000000000000002 },
    { name: "constcol k=8 (dyadic)", note: "constant column, dyadic ratio",
      X: [[1, 8], [2, 8], [3, 8]],
      y: [2, 4, 6], probe: [4, 8],
      w: null, realizable: true,
      oracleCoef: [2.0000000000000004, -1.1856949532535517e-16, -1.4821186915669396e-17],
      oraclePred: 8.0 },
    { name: "constcol k=0.5 (dyadic)", note: "constant column, dyadic ratio",
      X: [[1, 0.5], [2, 0.5], [3, 0.5]],
      y: [2, 4, 6], probe: [4, 0.5],
      w: null, realizable: true,
      oracleCoef: [2.0000000000000004, -4.965995236957133e-16, -9.931990473914265e-16],
      oraclePred: 8.0 },
    { name: "constcol k=0.25 (dyadic)", note: "constant column, dyadic ratio",
      X: [[1, 0.25], [2, 0.25], [3, 0.25]],
      y: [2, 4, 6], probe: [4, 0.25],
      w: null, realizable: true,
      oracleCoef: [2.0, -2.1236356089860365e-16, -8.494542435944143e-16],
      oraclePred: 7.999999999999999 },
    { name: "constcol k=3", note: "constant column, non-dyadic ratio",
      X: [[1, 3], [2, 3], [3, 3]],
      y: [2, 4, 6], probe: [4, 3],
      w: null, realizable: true,
      oracleCoef: [2.0, -1.663844174236196e-16, -5.5461472474539865e-17],
      oraclePred: 7.999999999999999 },
    { name: "constcol k=5", note: "constant column, non-dyadic ratio",
      X: [[1, 5], [2, 5], [3, 5]],
      y: [2, 4, 6], probe: [4, 5],
      w: null, realizable: true,
      oracleCoef: [2.0, -4.883587583783698e-17, -9.767175167567394e-18],
      oraclePred: 8.0 },
    { name: "constcol k=6", note: "constant column, non-dyadic ratio",
      X: [[1, 6], [2, 6], [3, 6]],
      y: [2, 4, 6], probe: [4, 6],
      w: null, realizable: true,
      oracleCoef: [2.0, -3.9401833480807933e-17, -6.566972246801322e-18],
      oraclePred: 8.0 },
    { name: "constcol k=7", note: "constant column, non-dyadic ratio",
      X: [[1, 7], [2, 7], [3, 7]],
      y: [2, 4, 6], probe: [4, 7],
      w: null, realizable: true,
      oracleCoef: [2.0, -8.309405970993061e-17, -1.1870579958561517e-17],
      oraclePred: 7.999999999999999 },
    { name: "constcol k=9", note: "constant column, non-dyadic ratio",
      X: [[1, 9], [2, 9], [3, 9]],
      y: [2, 4, 6], probe: [4, 9],
      w: null, realizable: true,
      oracleCoef: [2.0000000000000004, -2.1959673492239484e-17, -2.4399637213599415e-18],
      oraclePred: 8.000000000000002 },
    { name: "constcol k=10", note: "constant column, non-dyadic ratio",
      X: [[1, 10], [2, 10], [3, 10]],
      y: [2, 4, 6], probe: [4, 10],
      w: null, realizable: true,
      oracleCoef: [2.0, -7.732126523166594e-17, -7.732126523166595e-18],
      oraclePred: 7.999999999999999 },
    { name: "constcol k=11", note: "constant column, non-dyadic ratio",
      X: [[1, 11], [2, 11], [3, 11]],
      y: [2, 4, 6], probe: [4, 11],
      w: null, realizable: true,
      oracleCoef: [2.0000000000000004, -2.351711778861505e-16, -2.137919798965004e-17],
      oraclePred: 7.999999999999999 },
    { name: "constcol k=13", note: "constant column, non-dyadic ratio",
      X: [[1, 13], [2, 13], [3, 13]],
      y: [2, 4, 6], probe: [4, 13],
      w: null, realizable: true,
      oracleCoef: [2.0000000000000004, -1.1004198123175234e-16, -8.464767787057869e-18],
      oraclePred: 8.0 },
    { name: "constcol k=100", note: "constant column, non-dyadic ratio",
      X: [[1, 100], [2, 100], [3, 100]],
      y: [2, 4, 6], probe: [4, 100],
      w: null, realizable: true,
      oracleCoef: [2.0, -1.0898490881507446e-17, -1.0898490881507446e-19],
      oraclePred: 7.999999999999999 },
    { name: "constcol k=0.3", note: "constant column, non-dyadic ratio",
      X: [[1, 0.3], [2, 0.3], [3, 0.3]],
      y: [2, 4, 6], probe: [4, 0.3],
      w: null, realizable: true,
      oracleCoef: [2.0, -3.268763978881498e-16, -1.0895879929604995e-15],
      oraclePred: 7.999999999999999 },
    { name: "constcol k=0.1", note: "constant column, non-dyadic ratio",
      X: [[1, 0.1], [2, 0.1], [3, 0.1]],
      y: [2, 4, 6], probe: [4, 0.1],
      w: null, realizable: true,
      oracleCoef: [2.0000000000000013, -7.746091412155807e-17, -7.746091412155811e-16],
      oraclePred: 8.000000000000005 },
    { name: "colin k=1 (dyadic)", note: "collinear through origin, dyadic",
      X: [[1, 1], [2, 2], [3, 3]],
      y: [1, 2, 3], probe: [2, 2],
      w: null, realizable: true,
      oracleCoef: [0.5, 0.5000000000000001, -1.426417976083607e-16],
      oraclePred: 1.9999999999999998 },
    { name: "colin k=2 (dyadic)", note: "collinear through origin, dyadic",
      X: [[1, 2], [2, 4], [3, 6]],
      y: [1, 2, 3], probe: [2, 4],
      w: null, realizable: true,
      oracleCoef: [0.20000000000000004, 0.4, -1.2032291104667364e-16],
      oraclePred: 1.9999999999999998 },
    { name: "colin k=4 (dyadic)", note: "collinear through origin, dyadic",
      X: [[1, 4], [2, 8], [3, 12]],
      y: [1, 2, 3], probe: [2, 8],
      w: null, realizable: true,
      oracleCoef: [0.058823529411764726, 0.23529411764705888, -5.652678539509916e-17],
      oraclePred: 2.0000000000000004 },
    { name: "colin k=0.5 (dyadic)", note: "collinear through origin, dyadic",
      X: [[1, 0.5], [2, 1.0], [3, 1.5]],
      y: [1, 2, 3], probe: [2, 1.0],
      w: null, realizable: true,
      oracleCoef: [0.8000000000000003, 0.4000000000000001, -5.183788441017876e-16],
      oraclePred: 2.0 },
    { name: "colin k=0.25 (dyadic)", note: "collinear through origin, dyadic",
      X: [[1, 0.25], [2, 0.5], [3, 0.75]],
      y: [1, 2, 3], probe: [2, 0.5],
      w: null, realizable: true,
      oracleCoef: [0.9411764705882351, 0.23529411764705874, -6.606536190688641e-16],
      oraclePred: 1.999999999999999 },
    { name: "colin k=3", note: "collinear through origin, non-dyadic",
      X: [[1, 3], [2, 6], [3, 9]],
      y: [1, 2, 3], probe: [2, 6],
      w: null, realizable: true,
      oracleCoef: [0.09999999999999996, 0.29999999999999993, -4.1352993499011435e-17],
      oraclePred: 1.9999999999999996 },
    { name: "colin k=5", note: "collinear through origin, non-dyadic",
      X: [[1, 5], [2, 10], [3, 15]],
      y: [1, 2, 3], probe: [2, 10],
      w: null, realizable: true,
      oracleCoef: [0.03846153846153848, 0.19230769230769237, -7.457556521260799e-16],
      oraclePred: 2.0 },
    { name: "colin k=6", note: "collinear through origin, non-dyadic",
      X: [[1, 6], [2, 12], [3, 18]],
      y: [1, 2, 3], probe: [2, 12],
      w: null, realizable: true,
      oracleCoef: [0.027027027027027018, 0.1621621621621621, -2.2895583351460935e-17],
      oraclePred: 1.9999999999999991 },
    { name: "colin k=7", note: "collinear through origin, non-dyadic",
      X: [[1, 7], [2, 14], [3, 21]],
      y: [1, 2, 3], probe: [2, 14],
      w: null, realizable: true,
      oracleCoef: [0.02000000000000002, 0.14000000000000012, -5.310657632888805e-16],
      oraclePred: 2.0000000000000013 },
    { name: "colin k=9", note: "collinear through origin, non-dyadic",
      X: [[1, 9], [2, 18], [3, 27]],
      y: [1, 2, 3], probe: [2, 18],
      w: null, realizable: true,
      oracleCoef: [0.012195121951219506, 0.10975609756097554, 4.052060987952547e-16],
      oraclePred: 1.9999999999999991 },
    { name: "colin k=10", note: "collinear through origin, non-dyadic",
      X: [[1, 10], [2, 20], [3, 30]],
      y: [1, 2, 3], probe: [2, 20],
      w: null, realizable: true,
      oracleCoef: [0.009900990099009906, 0.09900990099009907, -7.429823944478676e-16],
      oraclePred: 2.0000000000000004 },
    { name: "colin k=11", note: "collinear through origin, non-dyadic",
      X: [[1, 11], [2, 22], [3, 33]],
      y: [1, 2, 3], probe: [2, 22],
      w: null, realizable: true,
      oracleCoef: [0.008196721311475412, 0.09016393442622953, 3.336927658628485e-16],
      oraclePred: 2.000000000000001 },
    { name: "colin k=100", note: "collinear through origin, non-dyadic",
      X: [[1, 100], [2, 200], [3, 300]],
      y: [1, 2, 3], probe: [2, 200],
      w: null, realizable: true,
      oracleCoef: [9.99900009999001e-05, 0.009999000099990009, 1.4947386569060967e-16],
      oraclePred: 2.0000000000000013 },
    { name: "colin k=1.5", note: "collinear through origin, non-dyadic",
      X: [[1, 1.5], [2, 3.0], [3, 4.5]],
      y: [1, 2, 3], probe: [2, 3.0],
      w: null, realizable: true,
      oracleCoef: [0.30769230769230754, 0.4615384615384613, -2.262613889716961e-16],
      oraclePred: 1.9999999999999987 },
    { name: "dup cols", note: "one column twice",
      X: [[1, 1], [2, 2], [3, 3]],
      y: [1, 2, 3], probe: [4, 4],
      w: null, realizable: true,
      oracleCoef: [0.5, 0.5000000000000001, -1.426417976083607e-16],
      oraclePred: 4.0 },
    { name: "dup cols + const", note: "one column twice beside a constant column",
      X: [[1, 1, 7], [2, 2, 7], [3, 3, 7]],
      y: [1, 2, 3], probe: [4, 4, 7],
      w: null, realizable: true,
      oracleCoef: [0.5000000000000003, 0.49999999999999994, -1.0470839771850903e-16, 3.05101110580046e-18],
      oraclePred: 4.0 },
    { name: "dup cols k=5", note: "a duplicated pair with a non-dyadic ratio",
      X: [[1, 5], [2, 10], [3, 15]],
      y: [2, 4, 6], probe: [4, 20],
      w: null, realizable: true,
      oracleCoef: [0.07692307692307696, 0.38461538461538475, -1.4915113042521599e-15],
      oraclePred: 8.000000000000002 },
    { name: "identical rows", note: "all three rows identical",
      X: [[1, 5], [1, 5], [1, 5]],
      y: [2, 2, 2], probe: [1, 5],
      w: null, realizable: true,
      oracleCoef: [0.07407407407407407, 0.3703703703703702, 0.07407407407407404],
      oraclePred: 1.999999999999999 },
    { name: "dup row + 1", note: "one row twice, two distinct rows in all",
      X: [[1, 1], [1, 1], [2, 3]],
      y: [2, 2, 5], probe: [1, 1],
      w: null, realizable: true,
      oracleCoef: [0.6666666666666666, 1.1666666666666665, 0.1666666666666673],
      oraclePred: 2.0000000000000004 },
    { name: "zero col", note: "a column of zeros",
      X: [[1, 0], [2, 0], [3, 0]],
      y: [2, 4, 6], probe: [4, 0],
      w: null, realizable: true,
      oracleCoef: [2.000000000000001, 0.0, -9.538271408308964e-16],
      oraclePred: 8.000000000000002 },
    { name: "zero col + dup", note: "zero column beside a duplicated column",
      X: [[1, 0, 1], [2, 0, 2], [3, 0, 3]],
      y: [2, 4, 6], probe: [4, 0, 4],
      w: null, realizable: true,
      oracleCoef: [0.9999999999999994, 1.1102230246251565e-16, 0.9999999999999997, 2.3375038351724297e-16],
      oraclePred: 7.9999999999999964 },
    { name: "x3=x1+1*x2", note: "three-column linear dependence",
      X: [[1, 1, 2], [2, 3, 5], [3, 2, 5], [4, 4, 8]],
      y: [2, 5, 5, 8], probe: [1, 2, 3],
      w: null, realizable: true,
      oracleCoef: [0.3333333333333333, 0.33333333333333337, 0.6666666666666666, -4.1371923818932543e-16],
      oraclePred: 2.9999999999999996 },
    { name: "x3=x1+2*x2", note: "three-column linear dependence",
      X: [[1, 1, 3], [2, 3, 8], [3, 2, 7], [4, 4, 12]],
      y: [2, 5, 5, 8], probe: [1, 2, 5],
      w: null, realizable: true,
      oracleCoef: [0.5, -4.233359785421751e-17, 0.49999999999999983, 3.264848976148213e-16],
      oraclePred: 2.9999999999999996 },
    { name: "x3=x1+3*x2", note: "three-column linear dependence",
      X: [[1, 1, 4], [2, 3, 11], [3, 2, 9], [4, 4, 16]],
      y: [2, 5, 5, 8], probe: [1, 2, 7],
      w: null, realizable: true,
      oracleCoef: [0.636363636363637, -0.09090909090909102, 0.3636363636363633, -5.346825455744751e-16],
      oraclePred: 2.999999999999998 },
    { name: "x3=x1+5*x2", note: "three-column linear dependence",
      X: [[1, 1, 6], [2, 3, 17], [3, 2, 13], [4, 4, 24]],
      y: [2, 5, 5, 8], probe: [1, 2, 11],
      w: null, realizable: true,
      oracleCoef: [0.7777777777777778, -0.11111111111111101, 0.2222222222222225, -2.2182340302854803e-15],
      oraclePred: 3.000000000000001 },
    { name: "constcol k=5 w ones", note: "canonical band row, all-ones weights",
      X: [[1, 5], [2, 5], [3, 5]],
      y: [2, 4, 6], probe: [4, 5],
      w: [1, 1, 1], realizable: true,
      oracleCoef: [2.0, -4.883587583783698e-17, -9.767175167567394e-18],
      oraclePred: 8.0 },
    { name: "constcol k=5 w 1:2:3", note: "canonical band row, unequal weights",
      X: [[1, 5], [2, 5], [3, 5]],
      y: [2, 4, 6], probe: [4, 5],
      w: [1, 2, 3], realizable: true,
      oracleCoef: [2.0, -5.5936828172749694e-18, -1.1187365634549942e-18],
      oraclePred: 8.0 },
    { name: "colin k=3 w", note: "collinear, unequal weights",
      X: [[1, 3], [2, 6], [3, 9]],
      y: [1, 2, 3], probe: [2, 6],
      w: [0.5, 1, 2], realizable: true,
      oracleCoef: [0.09999999999999994, 0.2999999999999999, 6.44209767930293e-17],
      oraclePred: 1.9999999999999991 },
    { name: "dup cols w 1e300", note: "canonical duplicate columns, huge weights",
      X: [[1, 1], [2, 2], [3, 3]],
      y: [1, 2, 3], probe: [4, 4],
      w: [1e+300, 1e+300, 1e+300], realizable: true,
      oracleCoef: [0.5, 0.5000000000000001, -1.426417976083607e-16],
      oraclePred: 4.0 },
    { name: "dup cols w 1e-320", note: "duplicate columns, subnormal weights",
      X: [[1, 1], [2, 2], [3, 3]],
      y: [1, 2, 3], probe: [4, 4],
      w: [1e-320, 1e-320, 1e-320], realizable: true,
      oracleCoef: [0.5, 0.5000000000000001, -1.426417976083607e-16],
      oraclePred: 4.0 },
    { name: "zero col w 1e-320", note: "zero column, subnormal weights (ridge underflow)",
      X: [[0], [0]],
      y: [1, 2], probe: [0],
      w: [1e-320, 1e-320], realizable: false,
      oracleCoef: [0.0, 1.4999999999999996],
      oraclePred: 1.4999999999999996 },
];
/* BAND-GOLDEN-END */
/* NEAR-GOLDEN-START */
const NEAR = [
    { name: "near d=1000 null", note: "x2=3*x1+d*z, pivot ratio 1.986e-07 >= 1000*eps: exact",
      X: [[1.0, 1003.0], [2.0, -994.0], [3.0, 1009.0], [4.0, -988.0], [5.0, 1015.0], [6.0, -982.0], [7.0, 1021.0], [8.0, -976.0]],
      y: [-1000.0, 1000.0, -1000.0, 1000.0, -1000.0, 1000.0, -1000.0, 1000.0], probe: [2.5, 1007.5],
      want: [3.0, -1.0, 0.0], oracle: [3.0000000000000777, -0.9999999999999969, -3.9646724974182554e-13],
      probeWant: -1000.0, oraclePred: -999.999999999997,
      ratio: 1.9856993999896498e-07, side: "exact", singular: false },
    { name: "near d=1000 smooth", note: "x2=3*x1+d*z, pivot ratio 1.986e-07 >= 1000*eps: exact",
      X: [[1.0, 1003.0], [2.0, -994.0], [3.0, 1009.0], [4.0, -988.0], [5.0, 1015.0], [6.0, -982.0], [7.0, 1021.0], [8.0, -976.0]],
      y: [3.0, 5.0, 7.0, 9.0, 11.0, 13.0, 15.0, 17.0], probe: [2.5, 1007.5],
      want: [2.0, 0.0, 1.0], oracle: [2.0, 2.3681250706450135e-15, 1.0000000000000022],
      probeWant: 6.0, oraclePred: 6.000000000002387,
      ratio: 1.9856993999896498e-07, side: "exact", singular: false },
    { name: "near d=10000 null", note: "x2=3*x1+d*z, pivot ratio 1.981e-09 >= 1000*eps: exact",
      X: [[1.0, 10003.0], [2.0, -9994.0], [3.0, 10009.0], [4.0, -9988.0], [5.0, 10015.0], [6.0, -9982.0], [7.0, 10021.0], [8.0, -9976.0]],
      y: [-10000.0, 10000.0, -10000.0, 10000.0, -10000.0, 10000.0, -10000.0, 10000.0], probe: [2.5, 10007.5],
      want: [3.0, -1.0, 0.0], oracle: [3.0000000000006994, -0.9999999999999981, -2.9773294359923295e-12],
      probeWant: -10000.0, oraclePred: -9999.999999999984,
      ratio: 1.980787710207248e-09, side: "exact", singular: false },
    { name: "near d=10000 smooth", note: "x2=3*x1+d*z, pivot ratio 1.981e-09 >= 1000*eps: exact",
      X: [[1.0, 10003.0], [2.0, -9994.0], [3.0, 10009.0], [4.0, -9988.0], [5.0, 10015.0], [6.0, -9982.0], [7.0, 10021.0], [8.0, -9976.0]],
      y: [3.0, 5.0, 7.0, 9.0, 11.0, 13.0, 15.0, 17.0], probe: [2.5, 10007.5],
      want: [2.0, 0.0, 1.0], oracle: [2.0000000000000013, 7.631681657677192e-16, 1.0000000000000027],
      probeWant: 6.0, oraclePred: 6.000000000007644,
      ratio: 1.980787710207248e-09, side: "exact", singular: false },
    { name: "near d=100000 null", note: "x2=3*x1+d*z, pivot ratio 1.980e-11 >= 1000*eps: exact",
      X: [[1.0, 100003.0], [2.0, -99994.0], [3.0, 100009.0], [4.0, -99988.0], [5.0, 100015.0], [6.0, -99982.0], [7.0, 100021.0], [8.0, -99976.0]],
      y: [-100000.0, 100000.0, -100000.0, 100000.0, -100000.0, 100000.0, -100000.0, 100000.0], probe: [2.5, 100007.5],
      want: [3.0, -1.0, 0.0], oracle: [3.0000000000042797, -1.0, -2.6530940069879414e-11],
      probeWant: -100000.0, oraclePred: -100000.00000000001,
      ratio: 1.9802573820765363e-11, side: "exact", singular: false },
    { name: "near d=100000 smooth", note: "x2=3*x1+d*z, pivot ratio 1.980e-11 >= 1000*eps: exact",
      X: [[1.0, 100003.0], [2.0, -99994.0], [3.0, 100009.0], [4.0, -99988.0], [5.0, 100015.0], [6.0, -99982.0], [7.0, 100021.0], [8.0, -99976.0]],
      y: [3.0, 5.0, 7.0, 9.0, 11.0, 13.0, 15.0, 17.0], probe: [2.5, 100007.5],
      want: [2.0, 0.0, 1.0], oracle: [1.9999999999999996, 1.3053615143307195e-19, 1.0000000000000022],
      probeWant: 6.0, oraclePred: 6.000000000000014,
      ratio: 1.9802573820765363e-11, side: "exact", singular: false },
    { name: "near d=500000 null", note: "x2=3*x1+d*z, pivot ratio 7.921e-13 >= 1000*eps: exact",
      X: [[1.0, 500003.0], [2.0, -499994.0], [3.0, 500009.0], [4.0, -499988.0], [5.0, 500015.0], [6.0, -499982.0], [7.0, 500021.0], [8.0, -499976.0]],
      y: [-500000.0, 500000.0, -500000.0, 500000.0, -500000.0, 500000.0, -500000.0, 500000.0], probe: [2.5, 500007.5],
      want: [3.0, -1.0, 0.0], oracle: [2.9999999999995803, -0.999999999999969, 1.0573793881637012e-11],
      probeWant: -500000.0, oraclePred: -499999.9999999845,
      ratio: 7.92083959697417e-13, side: "exact", singular: false },
    { name: "near d=500000 smooth", note: "x2=3*x1+d*z, pivot ratio 7.921e-13 >= 1000*eps: exact",
      X: [[1.0, 500003.0], [2.0, -499994.0], [3.0, 500009.0], [4.0, -499988.0], [5.0, 500015.0], [6.0, -499982.0], [7.0, 500021.0], [8.0, -499976.0]],
      y: [3.0, 5.0, 7.0, 9.0, 11.0, 13.0, 15.0, 17.0], probe: [2.5, 500007.5],
      want: [2.0, 0.0, 1.0], oracle: [2.000000000000001, 2.294744734882065e-14, 1.0000000000000024],
      probeWant: 6.0, oraclePred: 6.0000000114739,
      ratio: 7.92083959697417e-13, side: "exact", singular: false },
    { name: "near d=1e+06 null", note: "x2=3*x1+d*z, pivot ratio 1.980e-13 < 1000*eps: ridge",
      X: [[1.0, 1000003.0], [2.0, -999994.0], [3.0, 1000009.0], [4.0, -999988.0], [5.0, 1000015.0], [6.0, -999982.0], [7.0, 1000021.0], [8.0, -999976.0]],
      y: [-1000000.0, 1000000.0, -1000000.0, 1000000.0, -1000000.0, 1000000.0, -1000000.0, 1000000.0], probe: [2.5, 1000007.5],
      want: [3.0, -1.0, 0.0], oracle: [3.0000000000040403, -0.999999999999996, 2.114710251413003e-11],
      probeWant: -1000000.0, oraclePred: -999999.999999996,
      ratio: 1.980203959959405e-13, side: "ridge", singular: false },
    { name: "near d=1e+06 smooth", note: "x2=3*x1+d*z, pivot ratio 1.980e-13 < 1000*eps: ridge",
      X: [[1.0, 1000003.0], [2.0, -999994.0], [3.0, 1000009.0], [4.0, -999988.0], [5.0, 1000015.0], [6.0, -999982.0], [7.0, 1000021.0], [8.0, -999976.0]],
      y: [3.0, 5.0, 7.0, 9.0, 11.0, 13.0, 15.0, 17.0], probe: [2.5, 1000007.5],
      want: [2.0, 0.0, 1.0], oracle: [1.9999999999999987, 2.8679391184950817e-15, 1.0000000000000022],
      probeWant: 6.0, oraclePred: 6.00000000286796,
      ratio: 1.980203959959405e-13, side: "ridge", singular: false },
    { name: "near d=2e+06 null", note: "x2=3*x1+d*z, pivot ratio 4.951e-14 < 1000*eps: ridge",
      X: [[1.0, 2000003.0], [2.0, -1999994.0], [3.0, 2000009.0], [4.0, -1999988.0], [5.0, 2000015.0], [6.0, -1999982.0], [7.0, 2000021.0], [8.0, -1999976.0]],
      y: [-2000000.0, 2000000.0, -2000000.0, 2000000.0, -2000000.0, 2000000.0, -2000000.0, 2000000.0], probe: [2.5, 2000007.5],
      want: [3.0, -1.0, 0.0], oracle: [3.0000000001015987, -0.9999999999999991, -5.892364930979637e-10],
      probeWant: -2000000.0, oraclePred: -1999999.9999999986,
      ratio: 4.950502474974627e-14, side: "ridge", singular: false },
    { name: "near d=2e+06 smooth", note: "x2=3*x1+d*z, pivot ratio 4.951e-14 < 1000*eps: ridge",
      X: [[1.0, 2000003.0], [2.0, -1999994.0], [3.0, 2000009.0], [4.0, -1999988.0], [5.0, 2000015.0], [6.0, -1999982.0], [7.0, 2000021.0], [8.0, -1999976.0]],
      y: [3.0, 5.0, 7.0, 9.0, 11.0, 13.0, 15.0, 17.0], probe: [2.5, 2000007.5],
      want: [2.0, 0.0, 1.0], oracle: [2.0, 3.584775326904386e-16, 1.0000000000000022],
      probeWant: 6.0, oraclePred: 6.000000000716961,
      ratio: 4.950502474974627e-14, side: "ridge", singular: false },
    { name: "near d=1e+09 null", note: "x2=3*x1+d*z, pivot ratio 1.980e-19 < 1000*eps: ridge",
      X: [[1.0, 1000000003.0], [2.0, -999999994.0], [3.0, 1000000009.0], [4.0, -999999988.0], [5.0, 1000000015.0], [6.0, -999999982.0], [7.0, 1000000021.0], [8.0, -999999976.0]],
      y: [-1000000000.0, 1000000000.0, -1000000000.0, 1000000000.0, -1000000000.0, 1000000000.0, -1000000000.0, 1000000000.0], probe: [2.5, 1000000007.5],
      want: [3.0, -1.0, 0.0], oracle: [3.0000000530953645, -1.0, -2.3064940845252218e-07],
      probeWant: -1000000000.0, oraclePred: -1000000000.0000001,
      ratio: 1.980198025742575e-19, side: "ridge", singular: false },
    { name: "near d=1e+09 smooth", note: "x2=3*x1+d*z, pivot ratio 1.980e-19 < 1000*eps: ridge",
      X: [[1.0, 1000000003.0], [2.0, -999999994.0], [3.0, 1000000009.0], [4.0, -999999988.0], [5.0, 1000000015.0], [6.0, -999999982.0], [7.0, 1000000021.0], [8.0, -999999976.0]],
      y: [3.0, 5.0, 7.0, 9.0, 11.0, 13.0, 15.0, 17.0], probe: [2.5, 1000000007.5],
      want: [2.0, 0.0, 1.0], oracle: [1.9999999999999993, -1.3234889800848443e-23, 1.0000000000000022],
      probeWant: 6.0, oraclePred: 5.999999999999988,
      ratio: 1.980198025742575e-19, side: "ridge", singular: false },
    { name: "mixed-unit M=1", note: "const column at 1 beside unit features, pivot ratio 0.000e+00: ridge",
      X: [[1, 1.0], [2, 1.0], [3, 1.0], [4, 1.0]],
      y: [7, 9, 11, 13], probe: [2.5, 1.0],
      want: [2.0, 0.0, 5.0], oracle: [2.000000000000001, 2.4999999999999996, 2.4999999999999996],
      probeWant: 10.0, oraclePred: 10.000000000000002,
      ratio: 0.0, side: "ridge", singular: true },
    { name: "mixed-unit M=10000", note: "const column at 10000 beside unit features, pivot ratio 0.000e+00: ridge",
      X: [[1, 10000.0], [2, 10000.0], [3, 10000.0], [4, 10000.0]],
      y: [7, 9, 11, 13], probe: [2.5, 10000.0],
      want: [2.0, 0.0, 5.0], oracle: [2.0, 0.0004999999950000001, 4.999999950000001e-08],
      probeWant: 10.0, oraclePred: 10.0,
      ratio: 0.0, side: "ridge", singular: true },
    { name: "mixed-unit M=1e+06", note: "const column at 1e+06 beside unit features, pivot ratio 0.000e+00: ridge",
      X: [[1, 1000000.0], [2, 1000000.0], [3, 1000000.0], [4, 1000000.0]],
      y: [7, 9, 11, 13], probe: [2.5, 1000000.0],
      want: [2.0, 0.0, 5.0], oracle: [2.0, 4.999999999994999e-06, 4.999999999994998e-12],
      probeWant: 10.0, oraclePred: 10.0,
      ratio: 0.0, side: "ridge", singular: true },
];
/* NEAR-GOLDEN-END */
/* GOLDEN-END */

/* ---- 1. the forced-optimum battery: exact answer + the numpy oracle ---- */
for (const s of SYSTEMS) {
    const m = new LinearRegression().fit(s.X, s.y);
    const got = m.coef.concat([m.intercept]);
    let worst = 0, worstOracle = 0;
    for (let j = 0; j < got.length; j++) {
        worst = Math.max(worst, relerr(got[j], s.want[j]));
        worstOracle = Math.max(worstOracle, relerr(got[j], s.oracle[j]));
    }
    assert(worst <= 1e-9,
        s.name + " (" + s.note + "): exact OLS to <= 1e-9 relative, got " +
        worst.toExponential(3) + " coef=" + JSON.stringify(got) +
        " want=" + JSON.stringify(s.want));
    assert(worstOracle <= 1e-9,
        s.name + ": within 1e-9 relative of the numpy lstsq oracle, got " +
        worstOracle.toExponential(3));
    /* the forced optimum is also EXACT on the predictions */
    const pred = m.predict(s.X);
    for (let i = 0; i < pred.length; i++)
        assert(Math.abs(pred[i] - s.y[i]) <= 1e-6 * Math.max(1, Math.abs(s.y[i])),
            s.name + ": prediction " + i + " recovers the target");
}

/* ---- 2. singular designs: the ridge fallback keeps them solvable ---- */
function singularRow(X, y, probe, wantPred, label) {
    const m = new LinearRegression().fit(X, y);   /* must NOT throw */
    for (const c of m.coef.concat([m.intercept]))
        assert(Number.isFinite(c), label + ": coefficients stay finite");
    const p = m.predict([probe])[0];
    assert(Math.abs(p - wantPred) <= 1e-5 * Math.max(1, Math.abs(wantPred)),
        label + ": the identifiable prediction is recovered, got " + p +
        " want " + wantPred);
}
/* duplicate columns: only the sum is identifiable (2 + -1 = 1) */
singularRow([[1, 1], [2, 2], [3, 3]], [1, 2, 3], [4, 4], 4,
    "duplicate columns");
/* a zero column must come out as exactly 0 */
{
    const m = new LinearRegression().fit([[1, 0], [2, 0], [3, 0]], [2, 4, 6]);
    assert(m.coef[1] === 0, "a zero column is fitted as exactly 0");
    assert(Math.abs(m.coef[0] - 2) <= 1e-5, "the live column is recovered");
}
/* exact integer collinearity (col2 = 2 * col1): only 2*c1 + c2 is identifiable */
singularRow([[1, 2], [2, 4], [3, 6]], [3, 6, 9], [4, 8], 12,
    "integer collinear columns");
/* constant columns are collinear with the intercept */
singularRow([[1, 5], [1, 5], [1, 5]], [2, 2, 2], [1, 5], 2,
    "constant columns");
/* an empty fit refuses cleanly (typed, no crash) */
{
    let threw = false;
    try { new LinearRegression().fit([], []); } catch (e) {
        threw = e instanceof TypeError;
    }
    assert(threw, "an empty fit refuses with TypeError");
}

/* ---- 3. dense == sparse, bit-for-bit, on the new path ---- */
{
    const X = [[1, 0, 2], [0, 3, 0], [4, 0, 5], [1, 1, 0]];
    const y = [7, -2, 11, 4];
    const a = new LinearRegression().fit(X, y);
    const b = new LinearRegression().fit(CSR.fromDense(X), y);
    assert(a.coef.length === b.coef.length &&
           a.coef.every((v, i) => Object.is(v, b.coef[i])) &&
           Object.is(a.intercept, b.intercept),
        "a CSR fit is bit-identical to the dense fit of the same reading");
}

/* ---- 4. the weighted identities on the un-ridged path ---- */
{
    const X = [[1], [2], [3], [4]], y = [1, 2, 3, 10];
    const plain = new LinearRegression().fit(X, y);
    const ones = new LinearRegression().fit(X, y, { sampleWeight: [1, 1, 1, 1] });
    assert(plain.coef.every((v, i) => Object.is(v, ones.coef[i])) &&
           Object.is(plain.intercept, ones.intercept),
        "all-ones weights are BIT-identical to no weights");
    const zeroed = new LinearRegression().fit(X, y, { sampleWeight: [1, 1, 1, 0] });
    const deleted = new LinearRegression().fit([[1], [2], [3]], [1, 2, 3]);
    assert(Math.abs(zeroed.predict([[10]])[0] - deleted.predict([[10]])[0]) <= 1e-7,
        "weight 0 == the row not being there (to ridge/rounding)");
}

/* ---- 5. THE NUMERICALLY-SINGULAR BAND (the k-band matrix) ----
 *
 * An exactly-singular design does NOT always eliminate to an exact zero
 * pivot: any non-dyadic collinearity ratio leaves a rounding-level residue,
 * which an elimination that only refuses zero pivots "solves" into
 * coefficients amplified by 1/residue (1e15..1e31) and predictions that are
 * wrong on a perfectly realizable system. These rows are that band made
 * permanent: every family of exact singularity (a constant column, a column
 * that is a multiple of another, duplicate columns, identical rows, a zero
 * column, a three-column dependence) crossed with dyadic AND non-dyadic
 * ratios, dense and CSR, weighted and not.
 *
 * The coefficients of a singular design are not unique, so what is pinned is
 * what is IDENTIFIABLE: the prediction at a probe row (whose direction lies
 * in the design). `oraclePred`/`oracleCoef` come from numpy.linalg.lstsq, an
 * independent SVD solve; the residual of every `exact` row is zero, so the
 * probe prediction is unique however the minimiser splits the null space.
 *
 * The bounds: the identifiable prediction to 1e-4 relative (the ridge
 * fallback's bias on this battery measured 1e-9 .. 1.5e-5, worst at the
 * most extreme ratio; a garbage 1/residue solve misses by 0.5 relative and
 * by 1e15 in the coefficients), and every coefficient inside 8x the
 * minimum-norm solution's largest -- no amplification. */
for (const b of BAND) {
    const opt = b.w ? { sampleWeight: b.w } : undefined;
    const m = new LinearRegression().fit(b.X, b.y, opt);
    const coef = m.coef.concat([m.intercept]);
    for (let j = 0; j < coef.length; j++)
        assert(Number.isFinite(coef[j]),
            b.name + " (" + b.note + "): coefficient " + j + " is finite, got " + coef[j]);
    const oraMax = Math.max(1, ...b.oracleCoef.map(Math.abs));
    for (let j = 0; j < coef.length; j++)
        assert(Math.abs(coef[j]) <= 8 * oraMax,
            b.name + ": no 1/residue amplification -- |coef[" + j + "]| = " +
            Math.abs(coef[j]).toExponential(3) + " <= 8 x " + oraMax);
    const gotPred = m.predict([b.probe])[0];
    assert(Number.isFinite(gotPred) &&
           Math.abs(gotPred - b.oraclePred) <= 1e-4 * Math.max(1, Math.abs(b.oraclePred)),
        b.name + ": the identifiable prediction is the oracle's, got " + gotPred +
        " want " + b.oraclePred);
    /* the fit reproduces the realizable target of every row */
    if (b.realizable) {
        const tp = m.predict(b.X);
        for (let i = 0; i < tp.length; i++)
            assert(Math.abs(tp[i] - b.y[i]) <= 1e-4 * Math.max(1, Math.abs(b.y[i])),
                b.name + ": training prediction " + i + " recovers the target, got " +
                tp[i] + " want " + b.y[i]);
    }
    /* sparse == dense, BIT-identical, on the fallback path too */
    const s = new LinearRegression().fit(CSR.fromDense(b.X), b.y, opt);
    assert(s.coef.length === m.coef.length &&
           s.coef.every((v, i) => Object.is(v, m.coef[i])) &&
           Object.is(s.intercept, m.intercept),
        b.name + ": a CSR fit is bit-identical to the dense fit");
    assert(Object.is(s.predict([b.probe])[0], gotPred),
        b.name + ": the CSR prediction is bit-identical");
    m.close(); s.close();
}

/* ---- 6. the weight range: no load may overflow or underflow ----
 *
 * The ridge load is DYN_RIDGE x the system scale, and the system is divided
 * by the mean weight BEFORE the load is formed -- so a huge (1e300) or
 * subnormal (1e-320) weight scale cannot turn it into +Inf (whose pivots the
 * elimination refused, leaving no answer) or into 0 (which left a singular
 * system singular and threw "singular system" at a caller whose weights were
 * all equal). Weighted least squares is homogeneous in the weights, so these
 * rows also pin the answer against the unit-weight fit. */
{
    const X = [[1, 1], [2, 2], [3, 3]], y = [1, 2, 3], probe = [4, 4];
    const unit = new LinearRegression().fit(X, y);
    const unitPred = unit.predict([probe])[0];
    assert(Math.abs(unitPred - 4) <= 1e-4, "the unit-weight reference prediction");
    /* 2^1000: a power-of-two scale, so dividing by the mean weight is exact
       and the fit must be BIT-identical to the unit-weight one */
    const pow2 = new LinearRegression().fit(X, y, { sampleWeight: [Math.pow(2, 1000), Math.pow(2, 1000), Math.pow(2, 1000)] });
    assert(Number.isFinite(pow2.coef[0]) && Number.isFinite(pow2.intercept),
        "weights 2^1000: finite coefficients");
    assert(pow2.coef.every((v, i) => Object.is(v, unit.coef[i])) &&
           Object.is(pow2.intercept, unit.intercept),
        "weights 2^1000 are bit-identical to unit weights (exact power-of-two scale)");
    /* 1e300: used to overflow the load into +Inf -> no usable answer */
    const huge = new LinearRegression().fit(X, y, { sampleWeight: [1e300, 1e300, 1e300] });
    const hugeCoef = huge.coef.concat([huge.intercept]);
    assert(hugeCoef.every(Number.isFinite), "weights 1e300: finite coefficients, got " + JSON.stringify(hugeCoef));
    assert(Math.max(...hugeCoef.map(Math.abs)) > 0.5,
        "weights 1e300: NOT the silently-zero model, got " + JSON.stringify(hugeCoef));
    assert(Math.abs(huge.predict([probe])[0] - unitPred) <= 1e-6 * Math.max(1, Math.abs(unitPred)),
        "weights 1e300: the identifiable prediction matches the unit-weight fit, got " +
        huge.predict([probe])[0]);
    /* 1e-320 (subnormal): used to underflow the load to 0 -> "singular system" */
    const tiny = new LinearRegression().fit(X, y, { sampleWeight: [1e-320, 1e-320, 1e-320] });
    assert(tiny.coef.concat([tiny.intercept]).every(Number.isFinite),
        "subnormal weights: finite coefficients");
    assert(Math.abs(tiny.predict([probe])[0] - unitPred) <= 1e-6 * Math.max(1, Math.abs(unitPred)),
        "subnormal weights: the identifiable prediction matches the unit-weight fit");
    /* subnormal weights beside a ZERO column: the ridge underflowed to 0 and
       the fit threw "singular system"; the least-squares answer is the mean */
    const zx = new LinearRegression().fit([[0], [0]], [1, 2], { sampleWeight: [1e-320, 1e-320] });
    assert(zx.coef.concat([zx.intercept]).every(Number.isFinite),
        "subnormal weights + zero column: finite, got " + JSON.stringify(zx.coef));
    assert(Math.abs(zx.predict([[0]])[0] - 1.5) <= 1e-6,
        "subnormal weights + zero column: the least-squares intercept is the mean, got " +
        zx.predict([[0]])[0]);
    /* a mixed subnormal/normal weight vector keeps the homogeneity */
    const mixed = new LinearRegression().fit(X, y, { sampleWeight: [1e-320, 1, 1] });
    assert(mixed.coef.concat([mixed.intercept]).every(Number.isFinite),
        "mixed subnormal weights: finite coefficients");
    unit.close(); pow2.close(); huge.close(); tiny.close(); zx.close(); mixed.close();
    /* the stated finite-input LIMIT at the top of the range: A^T A is
       accumulated from the raw weight x feature^2 products BEFORE the weight
       normalization runs, so a product past ~1.8e308 (1e300 weights on
       1e6-scale features) reaches the solve as +Inf, where no load can repair
       it. The fit refuses with the typed InternalError instead of returning a
       model -- pinned here so the boundary stays a documented refusal, not a
       silent regression. */
    let overflowThrew = null;
    try {
        new LinearRegression().fit([[1, 1e6], [2, 1e6], [3, 1e6], [4, 1e6]],
            [3, 5, 7, 9], { sampleWeight: [1e300, 1e300, 1e300, 1e300] });
    } catch (e) {
        overflowThrew = e;
    }
    assert(overflowThrew !== null &&
           /singular system/.test(overflowThrew.message),
        "1e300 weights on 1e6-scale features: the documented overflow limit " +
        "refuses with 'singular system', got " + overflowThrew);
}

/* ---- 7. THE CONDITIONING GATE: near-singular WELL-POSED designs and
 *          mixed-unit singular scales (the generated NEAR block) ----
 *
 * The gate (DYN_SOLVE_MIN_PIVOT = 1000*eps ~ 2.2e-13 relative) has to split
 * two regimes the elimination cannot tell apart -- both end in a tiny last
 * pivot:
 *   - side "exact": the pivot is a genuine small singular value. The design
 *     is WELL-POSED however near-singular, and the un-ridged solve must
 *     deliver the exact OLS answer: predictions on the training rows AND an
 *     out-of-row probe to <= 1e-12 relative, coefficients to <= 1e-6 (the
 *     near-null coefficient component carries the conditioning noise; the
 *     predictions do not). The null-heavy targets are the sharp end of this:
 *     y = -d*z IS 3*x1 - x2, so their true coefficients (3, -1, 0) lie ALONG
 *     the near-null direction -- exactly what a ridge bias shrinks (the old
 *     2.2e-7 gate routed these rows to a ridge whose SCALE-PROPORTIONAL load
 *     missed by up to 1.3e0 relative; measured under the current absolute
 *     load the same misrouting still costs ~6e-10, 600x over the bound).
 *   - side "ridge": the pivot sits in the elimination's rounding band --
 *     genuine rank deficiency. Only identifiable quantities are pinned, at
 *     <= 1e-6 (the fallback's measured error here is ~1e-10; a garbage
 *     1/residue solve misses by 1e15). The mixed-unit rows (exactly singular
 *     at EVERY magnitude: the elimination leaves an exact zero pivot, so no
 *     positive gate can keep them off the ridge) are what pins the LOAD: the
 *     ridge is 1e-9 x the mean weight and nothing else -- a load proportional
 *     to the system's own largest diagonal grows with the constant column's
 *     units and zeroes the unit-scale direction (measured: 3.2e-2 relative
 *     error at 1e4, the zero model at 1e6).
 *
 * `ratio`/`side` are computed by the generator replicating the C elimination
 * op-for-op, so each row asserts the ROUTING it must take, not merely a
 * bound.
 *
 * MUTATION MATRIX -- each row below fails under exactly one of these single
 * constant flips (and passes the other two):
 *   - gate back to eps/DYN_RIDGE (2.2e-7): every side "exact" row is
 *     ridge-routed instead and fails its 1e-12 bound;
 *   - gate to 1e-300: the non-dyadic BAND rows (section 5) solve their
 *     rounding residue un-ridged into 1/residue garbage -- the amplification
 *     assertions there fail;
 *   - ridge load back to DYN_RIDGE x system scale: every side "ridge" row and
 *     the mixed-unit rows collapse toward the null direction (and the
 *     1e-320/1e300 weight corners of section 6 throw instead). */
for (const nr of NEAR) {
    const bound = nr.side === "exact" ? 1e-12 : 1e-6;
    const m = new LinearRegression().fit(nr.X, nr.y);   /* must NOT throw */
    const coef = m.coef.concat([m.intercept]);
    for (let j = 0; j < coef.length; j++)
        assert(Number.isFinite(coef[j]),
            nr.name + " (" + nr.note + "): coefficient " + j + " is finite, got " + coef[j]);
    if (!nr.singular) {
        /* well-posed: the OLS answer is UNIQUE, so the coefficients are
           pinnable -- at 1e-6 relative, because the near-null component
           carries the conditioning noise (measured 1.7e-9 at ratio 7.9e-13)
           while every PREDICTION stays exact, which the next assertions pin
           600x tighter */
        let worst = 0, worstOracle = 0;
        for (let j = 0; j < coef.length; j++) {
            worst = Math.max(worst, relerr(coef[j], nr.want[j]));
            worstOracle = Math.max(worstOracle, relerr(coef[j], nr.oracle[j]));
        }
        assert(worst <= 1e-6,
            nr.name + ": coefficients within 1e-6 relative of the exact " +
            "OLS answer, got " + worst.toExponential(3) +
            " coef=" + JSON.stringify(coef) + " want=" + JSON.stringify(nr.want));
        assert(worstOracle <= 1e-6,
            nr.name + ": coefficients within 1e-6 relative of the numpy " +
            "lstsq oracle, got " + worstOracle.toExponential(3));
    } else {
        /* exactly singular: the coefficients are NOT unique -- pin only that
           the fit is a real model, not the silently-zeroed one */
        const mag = coef.reduce((s, v) => s + Math.abs(v), 0);
        assert(mag > 0.5,
            nr.name + ": NOT the silently-zero model, coef=" + JSON.stringify(coef));
    }
    /* every row's target is exactly realizable: training predictions recover
       it, and the probe prediction (whose direction lies in the design) is
       the exact one -- at 1e-12 on the exact side (measured <= 2.7e-15; the
       gate regression measured up to 1.3e0 here) and 1e-6 on the ridge side
       (measured <= 1.1e-10) */
    const tp = m.predict(nr.X);
    for (let i = 0; i < tp.length; i++)
        assert(relerr(tp[i], nr.y[i]) <= bound,
            nr.name + ": training prediction " + i + " within " + bound +
            " relative, got " + tp[i] + " want " + nr.y[i]);
    const pp = m.predict([nr.probe])[0];
    assert(relerr(pp, nr.probeWant) <= bound,
        nr.name + ": probe prediction within " + bound + " relative, got " +
        pp + " want " + nr.probeWant);
    m.close();
}


print("test_ml_linreg_exact: all " + n + " assertions passed");
