/* test_protobuf.js -- the protobuf wire codec in dyna:serialize (plan 3.7).
 *
 * THE ORACLE IS THE OFFICIAL LIBRARY, THREE TIMES OVER:
 *  (1) The wire-grammar examples printed in the encoding guide at
 *      https://protobuf.dev/programming-guides/encoding/ (Test1/Test2/Test3/
 *      Test4, the 10-byte negative int32, the -500 ZigZag) -- byte for byte.
 *  (2) Bytes generated BY protoc 35.1 (libprotoc 35.1, /opt/homebrew/bin/
 *      protoc) via `protoc --encode=<Msg> gold.proto < text` and verified by
 *      `protoc --decode` round trip. The .proto for the 197-byte Gold message
 *      is at the bottom of this file; the S/PackOnly/OneI/MI/MB vectors come
 *      from the same toolchain. These are FOREIGN bytes: an encoder that only
 *      agreed with itself would pass a round trip and fail every vector here.
 *  (3) The negative cases are hand-built from the same documented grammar
 *      (tag = (field << 3) | wire_type) -- the decoder is the untrusted
 *      surface and every refusal must be observable and distinct.
 *
 * Run: dynajs (built with CONFIG_NATIVE_MODULES=y) tests/test_protobuf.js
 */
import { Proto } from "dyna:serialize";

let n = 0, fails = 0;
function assert(c, msg) { n++; if (!c) { fails++; print("FAIL: " + msg); } }
function eq(a, b, msg) {
    assert(a === b, msg + " (got " + JSON.stringify(a) + ", want " + JSON.stringify(b) + ")");
}
function throws(fn, msg) {
    let t = false;
    try { fn(); } catch (e) { t = true; }
    assert(t, msg);
}
/* The MESSAGE, not just that it threw: two guards against one symptom must be
 * told apart, and every refusal is supposed to name its reason. */
function throwsMatch(fn, re, msg) {
    let got = "";
    try { fn(); } catch (e) { got = String(e.message); }
    assert(re.test(got), msg + (got ? " (got: " + got + ")" : " (did not throw)"));
}
const hex = (u8) => Array.from(u8, (b) => b.toString(16).padStart(2, "0")).join("");
const bytes = (h) => new Uint8Array(h.match(/../g) ? h.match(/../g).map((x) => parseInt(x, 16)) : []);
const j = (v) => JSON.stringify(v);
function deepEq(a, b) {
    if (a === b) return true;
    if (typeof a !== "object" || typeof b !== "object" || a === null || b === null) return false;
    if (a instanceof Uint8Array || b instanceof Uint8Array) {
        return a instanceof Uint8Array && b instanceof Uint8Array &&
            a.length === b.length && Array.from(a).every((v, i) => v === b[i]);
    }
    const ka = Object.keys(a), kb = Object.keys(b);
    if (ka.length !== kb.length) return false;
    for (const k of ka) if (!(k in b) || !deepEq(a[k], b[k])) return false;
    return true;
}
function assertEq(v, want, msg) { assert(deepEq(v, want), msg + " (got " + j(v) + ", want " + j(want) + ")"); }

const S = { fields: [
    { name: "a", number: 1, type: "int32" },
    { name: "b", number: 2, type: "string" },
    { name: "c", number: 3, type: "sint32" },
    { name: "d", number: 4, type: "int32" },
    { name: "e", number: 5, type: "uint32" },
    { name: "f", number: 6, type: "bool" },
] };

/* ------------------ spec vectors: protobuf.dev encoding guide ---------- */
/* All byte strings below are printed in that document; the .proto snippet
 * each came from is named beside it. */

eq(hex(Proto.encode({ a: 150 }, { fields: [{ name: "a", number: 1, type: "int32" }] })),
   "089601", "Test1 {int32 a=1} a=150 -> 08 96 01 (spec 'A Simple Message')");

eq(hex(Proto.encode({ b: "testing" }, { fields: [{ name: "b", number: 2, type: "string" }] })),
   "120774657374696e67", "Test2 {string b=2} b='testing' -> 12 07 ... (spec)");

eq(hex(Proto.encode({ c: { a: 150 } }, { fields: [{ name: "c", number: 3, type: "message",
    message: { fields: [{ name: "a", number: 1, type: "int32" }] } }] })),
   "1a03089601", "Test3 {Test1 c=3} c.a=150 -> 1a 03 08 96 01 (spec 'Submessages')");

{
    const t4 = { fields: [{ name: "d", number: 4, type: "string" },
                          { name: "e", number: 5, type: "int32", repeated: true }] };
    eq(hex(Proto.encode({ d: "hello", e: [1, 2, 3] }, t4)),
       "220568656c6c6f2a03010203",
       "Test4 {string d=4; repeated int32 e=5} d='hello' e=[1,2,3] (spec, packed)");
    eq(hex(Proto.encode({ d: "hello", e: [1, 2, 3] },
                        { fields: [{ name: "d", number: 4, type: "string" },
                                   { name: "e", number: 5, type: "int32", repeated: true, packed: false }] })),
       "220568656c6c6f280128022803",
       "Test4 with packed=false emits one record per element (spec 'Repeated Elements')");
}

/* int32 negatives are 10-byte two's-complement varints (spec 'Signed Integers'). */
eq(hex(Proto.encode({ a: -2 }, { fields: [{ name: "a", number: 1, type: "int32" }] })),
   "08feffffffffffffffff01", "int32 -2 -> the spec's ten-byte two's complement");

/* sint32 ZigZag: -500 encodes as the varint 999 (spec: '-500z is 999'). */
eq(hex(Proto.encode({ c: -500 }, { fields: [{ name: "c", number: 1, type: "sint32" }] })),
   "08e707", "sint32 -500 -> ZigZag 999 -> e7 07 (spec)");

/* decode of those same spec bytes must round trip to the same value. */
{
    const t1 = { fields: [{ name: "a", number: 1, type: "int32" }] };
    assertEq(Proto.decode(bytes("089601"), t1), { a: 150 }, "decode Test1 bytes");
    const t2 = { fields: [{ name: "b", number: 2, type: "string" }] };
    assertEq(Proto.decode(bytes("120774657374696e67"), t2), { b: "testing" }, "decode Test2 bytes");
}

/* --------------------------- protoc 35.1 golden bytes ------------------ */
/* 197 bytes, generated by protoc 35.1 from gold.proto (printed at the end of
 * this file) and verified with protoc --decode. Descriptor field order MUST
 * match the .proto declaration order (protoc emits in field-number order). */

const innerSchema = { fields: [{ name: "n", number: 1, type: "int32" },
                               { name: "s", number: 2, type: "string" }] };
const goldSchema = { fields: [
    { name: "i32", number: 1, type: "int32" },
    { name: "i64", number: 2, type: "int64" },
    { name: "u32", number: 3, type: "uint32" },
    { name: "u64", number: 4, type: "uint64" },
    { name: "s32", number: 5, type: "sint32" },
    { name: "s64", number: 6, type: "sint64" },
    { name: "f32", number: 7, type: "fixed32" },
    { name: "f64", number: 8, type: "fixed64" },
    { name: "sf32", number: 9, type: "sfixed32" },
    { name: "sf64", number: 10, type: "sfixed64" },
    { name: "fl", number: 11, type: "float" },
    { name: "db", number: 12, type: "double" },
    { name: "b", number: 13, type: "bool" },
    { name: "str", number: 14, type: "string" },
    { name: "byt", number: 15, type: "bytes" },
    { name: "color", number: 16, type: "enum" },
    { name: "inner", number: 17, type: "message", message: innerSchema },
    { name: "rep", number: 18, type: "int32", repeated: true },
    { name: "rep_unpacked", number: 19, type: "int32", repeated: true, packed: false },
    { name: "rep_str", number: 20, type: "string", repeated: true },
    { name: "m", number: 21, type: "message", map: true, keyType: "string", valueType: "int32" },
    { name: "a", number: 22, type: "string", oneof: "choice" },
] };
const GOLD_HEX =
    "08eafeffffffffffffff0110809ce8af"+
    "edffffffff011880d0acf30e20c0f5aa"+
    "e4d3da980228ff880f30d3db80cb493d"+
    "efbeadde41c0ba8a3cd56204004deb32"+
    "a4f851000000000000fcff5d00006040"+
    "61000000000000d0bf6801720d68c3a9"+
    "6c6c6f2077c3b6726c647a04010203ff"+
    "8001028a0108082a1204646565709201"+
    "05010203ac02980107980108a2010561"+
    "6c706861a2010462657461aa01060a02"+
    "6b31100aaa010f0a026b3210ecffffff"+
    "ffffffffff01b2010c6f6e656f662d73"+
    "7472696e67";
          // a = "oneof-string"

const GOLD_VALUE = {
    i32: -150, i64: -5000000000, u32: 4000000000, u64: 1234567890123456,
    s32: -123456, s64: -9876543210, f32: 3735928559, f64: 1234567890123456,
    sf32: -123456789, sf64: -1125899906842624, fl: 3.5, db: -0.25, b: true,
    str: "héllo wörld", byt: bytes("010203ff"), color: 2,
    inner: { n: 42, s: "deep" }, rep: [1, 2, 3, 300], rep_unpacked: [7, 8],
    rep_str: ["alpha", "beta"], m: { k1: 10, k2: -20 }, a: "oneof-string",
};

eq(hex(Proto.encode(GOLD_VALUE, goldSchema)), GOLD_HEX,
   "protoc-35.1 Gold message encodes to the foreign bytes, byte for byte");
assertEq(Proto.decode(bytes(GOLD_HEX), goldSchema), GOLD_VALUE,
   "protoc-35.1 Gold bytes decode to the exact value");
eq(hex(Proto.encode(Proto.decode(bytes(GOLD_HEX), goldSchema), goldSchema)), GOLD_HEX,
   "decode -> encode is byte-exact for the foreign bytes");

/* More protoc-35.1 vectors. */
{
    const v = { a: 150, b: "testing", c: -500, d: -2147483648, e: 4294967295 };
    const s = { fields: [{ name: "a", number: 1, type: "int32" },
                         { name: "b", number: 2, type: "string" },
                         { name: "c", number: 3, type: "sint32" },
                         { name: "d", number: 4, type: "int32" },
                         { name: "e", number: 5, type: "uint32" }] };
    const h = "089601120774657374696e6718e7072080808080f8ffffffff0128ffffffff0f";
    eq(hex(Proto.encode(v, s)), h, "S vector encodes to protoc bytes");
    assertEq(Proto.decode(bytes(h), s), v, "S vector decodes to the value");
}
{
    const pk = { fields: [{ name: "nums", number: 1, type: "int32", repeated: true }] };
    eq(hex(Proto.encode({ nums: [1, 2, 3] }, pk)), "0a03010203",
       "PackOnly packed [1,2,3] -> 0a 03 01 02 03 (protoc)");
}
{
    const oi = { fields: [{ name: "a", number: 22, type: "string", oneof: "c" },
                          { name: "bb", number: 23, type: "int32", oneof: "c" }] };
    eq(hex(Proto.encode({ bb: 77 }, oi)), "b8014d", "OneI oneof int bb=77 (protoc)");
}
{
    /* map<int32,string> {7:"seven", -3:"neg"} and map<bool,int32> {true:1} */
    const mi = { fields: [{ name: "m", number: 1, type: "message", map: true,
                            keyType: "int32", valueType: "string" }] };
    const mb = { fields: [{ name: "m", number: 1, type: "message", map: true,
                            keyType: "bool", valueType: "int32" }] };
    eq(hex(Proto.encode({ m: { "7": "seven", "-3": "neg" } }, mi)),
       "0a0908071205736576656e0a1008fdffffffffffffffff0112036e6567",
       "map<int32,string> with negative key (protoc)");
    assertEq(Proto.decode(bytes("0a0908071205736576656e0a1008fdffffffffffffffff0112036e6567"), mi),
             { m: { "7": "seven", "-3": "neg" } }, "decode map<int32,string>");
    eq(hex(Proto.encode({ m: { "true": 1 } }, mb)), "0a0408011001",
       "map<bool,int32> key true (protoc)");
}

/* ---------------- packed / unpacked interop (spec requires both) ------- */
{
    const packed = { fields: [{ name: "rep", number: 18, type: "int32", repeated: true }] };
    const unpacked = { fields: [{ name: "rep", number: 18, type: "int32", repeated: true, packed: false }] };
    assertEq(Proto.decode(bytes("920103010203"), packed), { rep: [1, 2, 3] },
             "packed-declared field parses a packed wire record");
    assertEq(Proto.decode(bytes("900101900102900103"), packed), { rep: [1, 2, 3] },
             "packed-declared field parses an UNPACKED wire record");
    assertEq(Proto.decode(bytes("920103010203"), unpacked), { rep: [1, 2, 3] },
             "unpacked-declared field parses a PACKED wire record");
    assertEq(Proto.decode(bytes("920100"), packed), { rep: [] },
             "an empty packed record appends nothing");
    /* fixed-size packed payload must be a whole number of elements. */
    throws(() => Proto.decode(bytes("3a03010203"),
        { fields: [{ name: "f", number: 7, type: "fixed32", repeated: true }] }),
        "packed fixed32 payload of 3 bytes is refused");
}

/* ------------------- unknown fields are preserved verbatim ------------- */
{
    const t1 = { fields: [{ name: "a", number: 1, type: "int32" }] };
    /* field 100, wire 0, value 5: tag = 100<<3|0 = 800 = a0 06 (grammar). */
    const wire = bytes("089601a00605");
    const dec = Proto.decode(wire, t1);
    assertEq(dec, { a: 150 }, "decode keeps the known field");
    const re = hex(Proto.encode(dec, t1));
    assert(re.includes("a00605"), "the unknown record re-emits verbatim");
    assertEq(Proto.decode(bytes(re), t1), dec, "re-decoded object is stable");
    /* a known field with the WRONG wire type is an unknown field, not a crash. */
    const wrong = Proto.decode(bytes("0a0105"), t1);   /* field 1 as LEN */
    assertEq(wrong, {}, "wrong wire type for a known field decodes as absent");
    eq(hex(Proto.encode(wrong, t1)), "0a0105", "and re-encodes the preserved bytes");
}

/* ------------------- the decoder is the untrusted surface -------------- */
{
    const t1 = { fields: [{ name: "a", number: 1, type: "int32" }] };
    throws(() => Proto.decode(bytes("0896"), t1), "truncated varint refused");
    throws(() => Proto.decode(bytes("0a0501"), t1), "declared LEN 5 over 1 byte refused");
    throws(() => Proto.decode(bytes("08" + "80".repeat(11) + "00"), t1),
           "varint longer than 10 bytes refused");
    throws(() => Proto.decode(bytes("0affffffff0f"), t1),
           "length prefix above 2^31-1 refused before any allocation");
    throws(() => Proto.decode(bytes("0a0501"), t1), "length bomb beyond the input refused");
    throws(() => Proto.decode(bytes("00"), t1), "field number 0 refused");
    throws(() => Proto.decode(bytes("0e01"), t1), "wire type 6 refused");
    throws(() => Proto.decode(bytes("0f01"), t1), "wire type 7 refused");
    throws(() => Proto.decode(bytes("0b"), t1), "group start (wire 3) refused");
    throws(() => Proto.decode(bytes("0c"), t1), "group end (wire 4) refused");
    throws(() => Proto.decode(bytes("8080808010"), t1),
           "field number above 2^29-1 refused");
    throws(() => Proto.decode(bytes("08818080808080808010"),
        { fields: [{ name: "i", number: 1, type: "int64" }] }),
        "int64 not exactly representable as a double is refused (2^60+1)");
    throws(() => Proto.decode(bytes("0a0200"),
        { fields: [{ name: "m", number: 1, type: "message", map: true,
                     keyType: "int32", valueType: "int32" }] }),
        "a map entry with field number 0 is refused");
}

/* ----------------------------- depth caps ------------------------------ */
/* Each level is `0a 02` wrapping the next; the innermost is `0a 00`. */
{
    /* the schema parser recurses, so the 63/64-level schemas are built
       EXPLICITLY here (a cyclic schema object would recurse forever). */
    function mkSchema(n) {
        let s = { fields: [] };
        for (let i = 0; i < n; i++)
            s = { fields: [{ name: "m", number: 1, type: "message", message: s }] };
        return s;
    }
    function mkData(n) {
        let v = {};
        for (let i = 0; i < n; i++) v = { m: v };
        return v;
    }
    /* each level's LEN covers the WHOLE rest: 0a00 -> 0a02 0a00 ->
       0a04 ... (lengths grow by 2 per level; all stay single-byte) */
    function mkWire(n) {
        let w = "0a00";
        for (let i = 0; i < n; i++)
            w = "0a" + (w.length / 2).toString(16).padStart(2, "0") + w;
        return w;
    }
    assertEq(Proto.decode(bytes(mkWire(63)), mkSchema(63)), mkData(63),
             "63 nested message levels decode (the cap is 64)");
    throws(() => Proto.decode(bytes(mkWire(64)), mkSchema(64)),
           "64 nested levels are the cap (N)");
    throws(() => Proto.decode(bytes("0a02".repeat(65) + "0a00"), m),
           "65 nested levels are refused (N+1)");
    throws(() => Proto.decode(bytes("0a02".repeat(100) + "0a00"), m),
           "a 100-level depth bomb is refused");
    /* the encode side enforces the same cap on value nesting. */
    const deep = {};
    let cur = deep;
    for (let i = 0; i < 63; i++) { cur.m = {}; cur = cur.m; }
    throws(() => Proto.encode(deep, m), "unused");
    /* schema nesting is capped too. */
    let sch = { fields: [{ name: "x", number: 1, type: "message", message: null }] };
    let top = sch;
    for (let i = 0; i < 65; i++) { sch.fields[0].message = { fields: [{ name: "x", number: 1, type: "message", message: null }] }; sch = sch.fields[0].message; }
    throws(() => Proto.encode({}, top), "a 65-deep schema is refused");
}

/* -------------------- encode-side refusals (strict) -------------------- */
{
    const s = { fields: [{ name: "a", number: 1, type: "int32" },
                         { name: "b", number: 2, type: "string" },
                         { name: "c", number: 3, type: "bytes" },
                         { name: "d", number: 4, type: "message",
                           message: { fields: [{ name: "x", number: 1, type: "int32" }] } },
                         { name: "e", number: 5, type: "uint32" },
                         { name: "f", number: 6, type: "bool" }] };
    throws(() => Proto.encode({ a: "not a number" }, s), "string where int32 required");
    throws(() => Proto.encode({ a: 1.5 }, s), "non-integer number refused");
    throws(() => Proto.encode({ a: 2147483648 }, s), "int32 overflow refused");
    throws(() => Proto.encode({ a: -2147483649 }, s), "int32 underflow refused");
    throws(() => Proto.encode({ e: 4294967296 }, s), "uint32 overflow refused");
    throws(() => Proto.encode({ b: 42 }, s), "number where string required");
    throws(() => Proto.encode({ c: "abc" }, s), "string where bytes required");
    throws(() => Proto.encode({ d: [1, 2] }, s), "array where a message required");
    throws(() => Proto.encode({ d: bytes("0102") }, s), "byte view where a message required");
    throws(() => Proto.encode({ a: 1, d: 2 }, s), "number where a message required");
    throws(() => Proto.encode(5, s), "a primitive top-level value refused");
    throws(() => Proto.encode({}, "not a schema"), "non-object schema refused");
    throws(() => Proto.encode({}, { fields: "nope" }), "non-array fields refused");
    throws(() => Proto.encode({}, { fields: [{ name: "a", number: 0, type: "int32" }] }),
           "field number 0 refused");
    throws(() => Proto.encode({}, { fields: [{ name: "a", number: 536870912, type: "int32" }] }),
           "field number 2^29 refused");
    throws(() => Proto.encode({}, { fields: [{ name: "a", number: 1, type: "int65" }] }),
           "unknown type string refused");
    throws(() => Proto.encode({}, { fields: [{ name: "a", number: 1, type: "message" }] }),
           "message type without a nested schema refused");
    throws(() => Proto.encode({}, { fields: [{ name: "a", number: 1, type: "message", map: true }] }),
           "map without keyType refused");
    throws(() => Proto.encode({}, { fields: [{ name: "a", number: 1, type: "int32" },
                                             { name: "b", number: 1, type: "int32" }] }),
           "duplicate field numbers refused");
}

/* ------------------------ defaults and boundaries ---------------------- */
{
    eq(hex(Proto.encode({}, S)), "", "an empty value encodes to zero bytes");
    assertEq(Proto.decode(bytes(""), S), {}, "empty input decodes to {}");
    assertEq(Proto.decode(bytes("089601"), S), { a: 150 },
             "unset singular fields stay undefined");
    const rep = { fields: [{ name: "r", number: 1, type: "int32", repeated: true },
                           { name: "m", number: 2, type: "message", map: true,
                             keyType: "string", valueType: "int32" }] };
    assertEq(Proto.decode(bytes(""), rep), { r: [], m: {} },
             "absent repeated/map fields default to [] and {}");
    eq(hex(Proto.encode({ r: [], m: {} }, rep)), "", "empty collections are not encoded");
    assertEq(Proto.decode(bytes("089601"), S), { a: 150 }, "no default-value synthesis");
    eq(hex(Proto.encode({ a: null }, S)), "", "null is treated as absent");
    /* oneof members both set: both encode, both survive decode. */
    const oi = { fields: [{ name: "a", number: 22, type: "string", oneof: "c" },
                          { name: "bb", number: 23, type: "int32", oneof: "c" }] };
    eq(hex(Proto.encode({ a: "x", bb: 5 }, oi)), "b2010178b80105",
       "oneof members encode independently");
    /* last one wins for a repeated singular field. */
    assertEq(Proto.decode(bytes("08 01 08 02".replace(/ /g, "")), S), { a: 2 },
             "a singular field repeated on the wire keeps the last value");
}

/* 08-17 security regression: the unknown-field preservation list is capped
   at 65536 records -- an all-unknown body must refuse, not allocate ~150 B
   per 2-byte record without bound. */
{
    const cap = 65536;
    const bomb = new Uint8Array((cap + 1) * 2);
    for (let i = 0; i < bomb.length; i += 2) { bomb[i] = 0x18; bomb[i + 1] = 0x01; }
    let t = false;
    try { Proto.decode(bomb, { fields: [] }); } catch (e) { t = true; }
    assert(t, "unknown-field record cap: 65537 records refuse");
    const under = bomb.subarray(0, 100);
    const r = Proto.decode(under, { fields: [] });
    assert(Array.isArray(r.__protoUnknown) && r.__protoUnknown.length === 50,
        "unknown-field records below the cap still preserve");
}

/* ------------------ proto3 strings are UTF-8 on the wire ---------------- */
{
    const sschema = { fields: [{ name: "s", number: 1, type: "string" }] };
    assertEq(Proto.decode(bytes("0a02c3a9"), sschema), { s: "\u00e9" },
             "a valid UTF-8 string decodes exactly as before");
    throwsMatch(() => Proto.decode(bytes("0a02fffe"), sschema),
                /not valid UTF-8/,
                "a string field with an invalid byte is refused");
    throwsMatch(() => Proto.decode(bytes("0a046162ffa0"), sschema),
                /not valid UTF-8/,
                "a truncated multi-byte sequence is refused too");
    throwsMatch(() => Proto.decode(bytes("0a01a0"), sschema),
                /not valid UTF-8/,
                "a stray continuation byte is refused");
    /* bytes fields take arbitrary octets: only strings are UTF-8-checked */
    assertEq(Proto.decode(bytes("1202fffe"),
                          { fields: [{ name: "b", number: 2, type: "bytes" }] }),
             { b: new Uint8Array([0xff, 0xfe]) },
             "a bytes field still accepts non-UTF-8 octets");
}

/* ------------------ map key errors name the key ------------------------- */
{
    throwsMatch(() => Proto.encode({ m: { "99999999999": "x" } },
        { fields: [{ name: "m", number: 1, type: "message", map: true,
                     keyType: "int32", valueType: "string" }] }),
        /map key "99999999999" is out of range/,
        "an out-of-range int32 map key error names the key");
    throwsMatch(() => Proto.encode({ m: { "-1": "x" } },
        { fields: [{ name: "m", number: 1, type: "message", map: true,
                     keyType: "uint32", valueType: "string" }] }),
        /map key "-1" is out of range/,
        "and so does a negative uint32 map key");
}

if (fails) { print("test_protobuf: " + fails + " FAILURES / " + n); process.exit(1); }
print("test_protobuf: " + n + " assertions OK");

/* gold.proto -- the source of GOLD_HEX, generated with protoc 35.1:
 *   syntax = "proto3";
 *   enum Color { RED = 0; GREEN = 1; BLUE = 2; }
 *   message Inner { int32 n = 1; string s = 2; }
 *   message Gold {
 *     int32 i32 = 1;  int64 i64 = 2;  uint32 u32 = 3;  uint64 u64 = 4;
 *     sint32 s32 = 5; sint64 s64 = 6;  fixed32 f32 = 7; fixed64 f64 = 8;
 *     sfixed32 sf32 = 9; sfixed64 sf64 = 10; float fl = 11; double db = 12;
 *     bool b = 13; string str = 14; bytes byt = 15; Color color = 16;
 *     Inner inner = 17;
 *     repeated int32 rep = 18;
 *     repeated int32 rep_unpacked = 19 [packed = false];
 *     repeated string rep_str = 20;
 *     map<string, int32> m = 21;
 *     oneof choice { string a = 22; int32 bb = 23; }
 *   }
 * text input (protoc --encode):
 *   i32:-150 i64:-5000000000 u32:4000000000 u64:1234567890123456
 *   s32:-123456 s64:-9876543210 f32:3735928559 f64:1234567890123456
 *   sf32:-123456789 sf64:-1125899906842624 fl:3.5 db:-0.25 b:true
 *   str:"héllo wörld" byt:"\001\002\003\377" color:BLUE inner:{n:42 s:"deep"}
 *   rep:1 rep:2 rep:3 rep:300 rep_unpacked:7 rep_unpacked:8
 *   rep_str:"alpha" rep_str:"beta" m:{key:"k1" value:10} m:{key:"k2" value:-20}
 *   a:"oneof-string"
 */