/* GENERATED by gen_matrix.js — T1 atom-parent slice matrices.
 * Literal parents longer than the slice threshold; ops compared against
 * the spec substring reference. */

function mkRnd(n, seed, hi) {
  var s = "";
  var x = seed | 0;
  for (var i = 0; i < n; i++) {
    x = (x * 1103515245 + 12345) & 0x7fffffff;
    s += String.fromCharCode((hi ? 65 : 97) + (x >>> 16) % 26);
  }
  return s;
}
function mkWide(n, seed) {
  var s = "\u1450";
  var x = seed | 0;
  for (var i = 0; i < n; i++) {
    x = (x * 1103515245 + 12345) & 0x7fffffff;
    s += String.fromCharCode(0x100 + (x >>> 16) % 500);
  }
  return s;
}
function mkWideNarrowable(n) {
  var s = "\u1450";
  for (var i = 0; i < n; i++) s += String.fromCharCode(0xF7 - (i % 90));
  return s;
}
function lit64() { return "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ab"; }
var LIT1024 = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ababcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ababcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ababcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ababcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ababcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ababcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ababcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ababcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ababcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ababcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ababcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ababcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ababcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ababcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ababcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ab";
var WLIT = "ā" + "ĂăĄ".repeat(341) + "ąĆ"; /* 1026 wide units */

test("m1_narrow_l64_o0", function () {
  var start = 1, end = start + 64;
  var want = LIT1024.substring(start, end);
  var got = LIT1024.slice(start, end);
  ok(got === want, "content");
  eq(got.length, 64, "length");
  eq(got.charCodeAt(0), want.charCodeAt(0), "first unit");
  eq(got.charCodeAt(got.length - 1), want.charCodeAt(want.length - 1), "last unit");
});

test("m1_narrow_l64_o1", function () {
  var start = 2, end = start + 64;
  var want = LIT1024.substring(start, end);
  var got = LIT1024.slice(start, end);
  ok(got === want, "content");
  eq(got.length, 64, "length");
  eq(got.charCodeAt(0), want.charCodeAt(0), "first unit");
  eq(got.charCodeAt(got.length - 1), want.charCodeAt(want.length - 1), "last unit");
});

test("m1_narrow_l64_o63", function () {
  var start = 64, end = start + 64;
  var want = LIT1024.substring(start, end);
  var got = LIT1024.slice(start, end);
  ok(got === want, "content");
  eq(got.length, 64, "length");
  eq(got.charCodeAt(0), want.charCodeAt(0), "first unit");
  eq(got.charCodeAt(got.length - 1), want.charCodeAt(want.length - 1), "last unit");
});

test("m1_narrow_l64_o100", function () {
  var start = 101, end = start + 64;
  var want = LIT1024.substring(start, end);
  var got = LIT1024.slice(start, end);
  ok(got === want, "content");
  eq(got.length, 64, "length");
  eq(got.charCodeAt(0), want.charCodeAt(0), "first unit");
  eq(got.charCodeAt(got.length - 1), want.charCodeAt(want.length - 1), "last unit");
});

test("m1_narrow_l65_o0", function () {
  var start = 1, end = start + 65;
  var want = LIT1024.substring(start, end);
  var got = LIT1024.slice(start, end);
  ok(got === want, "content");
  eq(got.length, 65, "length");
  eq(got.charCodeAt(0), want.charCodeAt(0), "first unit");
  eq(got.charCodeAt(got.length - 1), want.charCodeAt(want.length - 1), "last unit");
});

test("m1_narrow_l65_o1", function () {
  var start = 2, end = start + 65;
  var want = LIT1024.substring(start, end);
  var got = LIT1024.slice(start, end);
  ok(got === want, "content");
  eq(got.length, 65, "length");
  eq(got.charCodeAt(0), want.charCodeAt(0), "first unit");
  eq(got.charCodeAt(got.length - 1), want.charCodeAt(want.length - 1), "last unit");
});

test("m1_narrow_l65_o63", function () {
  var start = 64, end = start + 65;
  var want = LIT1024.substring(start, end);
  var got = LIT1024.slice(start, end);
  ok(got === want, "content");
  eq(got.length, 65, "length");
  eq(got.charCodeAt(0), want.charCodeAt(0), "first unit");
  eq(got.charCodeAt(got.length - 1), want.charCodeAt(want.length - 1), "last unit");
});

test("m1_narrow_l65_o100", function () {
  var start = 101, end = start + 65;
  var want = LIT1024.substring(start, end);
  var got = LIT1024.slice(start, end);
  ok(got === want, "content");
  eq(got.length, 65, "length");
  eq(got.charCodeAt(0), want.charCodeAt(0), "first unit");
  eq(got.charCodeAt(got.length - 1), want.charCodeAt(want.length - 1), "last unit");
});

test("m1_narrow_l100_o0", function () {
  var start = 1, end = start + 100;
  var want = LIT1024.substring(start, end);
  var got = LIT1024.slice(start, end);
  ok(got === want, "content");
  eq(got.length, 100, "length");
  eq(got.charCodeAt(0), want.charCodeAt(0), "first unit");
  eq(got.charCodeAt(got.length - 1), want.charCodeAt(want.length - 1), "last unit");
});

test("m1_narrow_l100_o1", function () {
  var start = 2, end = start + 100;
  var want = LIT1024.substring(start, end);
  var got = LIT1024.slice(start, end);
  ok(got === want, "content");
  eq(got.length, 100, "length");
  eq(got.charCodeAt(0), want.charCodeAt(0), "first unit");
  eq(got.charCodeAt(got.length - 1), want.charCodeAt(want.length - 1), "last unit");
});

test("m1_narrow_l100_o63", function () {
  var start = 64, end = start + 100;
  var want = LIT1024.substring(start, end);
  var got = LIT1024.slice(start, end);
  ok(got === want, "content");
  eq(got.length, 100, "length");
  eq(got.charCodeAt(0), want.charCodeAt(0), "first unit");
  eq(got.charCodeAt(got.length - 1), want.charCodeAt(want.length - 1), "last unit");
});

test("m1_narrow_l100_o100", function () {
  var start = 101, end = start + 100;
  var want = LIT1024.substring(start, end);
  var got = LIT1024.slice(start, end);
  ok(got === want, "content");
  eq(got.length, 100, "length");
  eq(got.charCodeAt(0), want.charCodeAt(0), "first unit");
  eq(got.charCodeAt(got.length - 1), want.charCodeAt(want.length - 1), "last unit");
});

test("m1_narrow_l127_o0", function () {
  var start = 1, end = start + 127;
  var want = LIT1024.substring(start, end);
  var got = LIT1024.slice(start, end);
  ok(got === want, "content");
  eq(got.length, 127, "length");
  eq(got.charCodeAt(0), want.charCodeAt(0), "first unit");
  eq(got.charCodeAt(got.length - 1), want.charCodeAt(want.length - 1), "last unit");
});

test("m1_narrow_l127_o1", function () {
  var start = 2, end = start + 127;
  var want = LIT1024.substring(start, end);
  var got = LIT1024.slice(start, end);
  ok(got === want, "content");
  eq(got.length, 127, "length");
  eq(got.charCodeAt(0), want.charCodeAt(0), "first unit");
  eq(got.charCodeAt(got.length - 1), want.charCodeAt(want.length - 1), "last unit");
});

test("m1_narrow_l127_o63", function () {
  var start = 64, end = start + 127;
  var want = LIT1024.substring(start, end);
  var got = LIT1024.slice(start, end);
  ok(got === want, "content");
  eq(got.length, 127, "length");
  eq(got.charCodeAt(0), want.charCodeAt(0), "first unit");
  eq(got.charCodeAt(got.length - 1), want.charCodeAt(want.length - 1), "last unit");
});

test("m1_narrow_l127_o100", function () {
  var start = 101, end = start + 127;
  var want = LIT1024.substring(start, end);
  var got = LIT1024.slice(start, end);
  ok(got === want, "content");
  eq(got.length, 127, "length");
  eq(got.charCodeAt(0), want.charCodeAt(0), "first unit");
  eq(got.charCodeAt(got.length - 1), want.charCodeAt(want.length - 1), "last unit");
});

test("m1_narrow_l128_o0", function () {
  var start = 1, end = start + 128;
  var want = LIT1024.substring(start, end);
  var got = LIT1024.slice(start, end);
  ok(got === want, "content");
  eq(got.length, 128, "length");
  eq(got.charCodeAt(0), want.charCodeAt(0), "first unit");
  eq(got.charCodeAt(got.length - 1), want.charCodeAt(want.length - 1), "last unit");
});

test("m1_narrow_l128_o1", function () {
  var start = 2, end = start + 128;
  var want = LIT1024.substring(start, end);
  var got = LIT1024.slice(start, end);
  ok(got === want, "content");
  eq(got.length, 128, "length");
  eq(got.charCodeAt(0), want.charCodeAt(0), "first unit");
  eq(got.charCodeAt(got.length - 1), want.charCodeAt(want.length - 1), "last unit");
});

test("m1_narrow_l128_o63", function () {
  var start = 64, end = start + 128;
  var want = LIT1024.substring(start, end);
  var got = LIT1024.slice(start, end);
  ok(got === want, "content");
  eq(got.length, 128, "length");
  eq(got.charCodeAt(0), want.charCodeAt(0), "first unit");
  eq(got.charCodeAt(got.length - 1), want.charCodeAt(want.length - 1), "last unit");
});

test("m1_narrow_l128_o100", function () {
  var start = 101, end = start + 128;
  var want = LIT1024.substring(start, end);
  var got = LIT1024.slice(start, end);
  ok(got === want, "content");
  eq(got.length, 128, "length");
  eq(got.charCodeAt(0), want.charCodeAt(0), "first unit");
  eq(got.charCodeAt(got.length - 1), want.charCodeAt(want.length - 1), "last unit");
});

test("m1_narrow_l255_o0", function () {
  var start = 1, end = start + 255;
  var want = LIT1024.substring(start, end);
  var got = LIT1024.slice(start, end);
  ok(got === want, "content");
  eq(got.length, 255, "length");
  eq(got.charCodeAt(0), want.charCodeAt(0), "first unit");
  eq(got.charCodeAt(got.length - 1), want.charCodeAt(want.length - 1), "last unit");
});

test("m1_narrow_l255_o1", function () {
  var start = 2, end = start + 255;
  var want = LIT1024.substring(start, end);
  var got = LIT1024.slice(start, end);
  ok(got === want, "content");
  eq(got.length, 255, "length");
  eq(got.charCodeAt(0), want.charCodeAt(0), "first unit");
  eq(got.charCodeAt(got.length - 1), want.charCodeAt(want.length - 1), "last unit");
});

test("m1_narrow_l255_o63", function () {
  var start = 64, end = start + 255;
  var want = LIT1024.substring(start, end);
  var got = LIT1024.slice(start, end);
  ok(got === want, "content");
  eq(got.length, 255, "length");
  eq(got.charCodeAt(0), want.charCodeAt(0), "first unit");
  eq(got.charCodeAt(got.length - 1), want.charCodeAt(want.length - 1), "last unit");
});

test("m1_narrow_l255_o100", function () {
  var start = 101, end = start + 255;
  var want = LIT1024.substring(start, end);
  var got = LIT1024.slice(start, end);
  ok(got === want, "content");
  eq(got.length, 255, "length");
  eq(got.charCodeAt(0), want.charCodeAt(0), "first unit");
  eq(got.charCodeAt(got.length - 1), want.charCodeAt(want.length - 1), "last unit");
});

test("m1_narrow_l256_o0", function () {
  var start = 1, end = start + 256;
  var want = LIT1024.substring(start, end);
  var got = LIT1024.slice(start, end);
  ok(got === want, "content");
  eq(got.length, 256, "length");
  eq(got.charCodeAt(0), want.charCodeAt(0), "first unit");
  eq(got.charCodeAt(got.length - 1), want.charCodeAt(want.length - 1), "last unit");
});

test("m1_narrow_l256_o1", function () {
  var start = 2, end = start + 256;
  var want = LIT1024.substring(start, end);
  var got = LIT1024.slice(start, end);
  ok(got === want, "content");
  eq(got.length, 256, "length");
  eq(got.charCodeAt(0), want.charCodeAt(0), "first unit");
  eq(got.charCodeAt(got.length - 1), want.charCodeAt(want.length - 1), "last unit");
});

test("m1_narrow_l256_o63", function () {
  var start = 64, end = start + 256;
  var want = LIT1024.substring(start, end);
  var got = LIT1024.slice(start, end);
  ok(got === want, "content");
  eq(got.length, 256, "length");
  eq(got.charCodeAt(0), want.charCodeAt(0), "first unit");
  eq(got.charCodeAt(got.length - 1), want.charCodeAt(want.length - 1), "last unit");
});

test("m1_narrow_l256_o100", function () {
  var start = 101, end = start + 256;
  var want = LIT1024.substring(start, end);
  var got = LIT1024.slice(start, end);
  ok(got === want, "content");
  eq(got.length, 256, "length");
  eq(got.charCodeAt(0), want.charCodeAt(0), "first unit");
  eq(got.charCodeAt(got.length - 1), want.charCodeAt(want.length - 1), "last unit");
});

test("m1_narrow_l1000_o0", function () {
  var start = 1, end = start + 1000;
  var want = LIT1024.substring(start, end);
  var got = LIT1024.slice(start, end);
  ok(got === want, "content");
  eq(got.length, 1000, "length");
  eq(got.charCodeAt(0), want.charCodeAt(0), "first unit");
  eq(got.charCodeAt(got.length - 1), want.charCodeAt(want.length - 1), "last unit");
});

test("m1_narrow_l1000_o1", function () {
  var start = 2, end = start + 1000;
  var want = LIT1024.substring(start, end);
  var got = LIT1024.slice(start, end);
  ok(got === want, "content");
  eq(got.length, 1000, "length");
  eq(got.charCodeAt(0), want.charCodeAt(0), "first unit");
  eq(got.charCodeAt(got.length - 1), want.charCodeAt(want.length - 1), "last unit");
});

test("m1_wide_sweep", function () {
  var starts = [0, 1, 63, 100, 500], lens = [1, 63, 64, 65, 255, 256, 1000];
  for (var si = 0; si < starts.length; si++) {
    for (var li = 0; li < lens.length; li++) {
      var st = starts[si], en = st + lens[li];
      if (en > WLIT.length) continue;
      var want = WLIT.substring(st, en), got = WLIT.slice(st, en);
      ok(got === want, "wide st=" + st + " len=" + lens[li]);
      eq(got.charCodeAt(0), want.charCodeAt(0), "first unit");
    }
  }
});
summary("sliced_waveB");
