/* GENERATED by gen_matrix.js — T3 search matrices over slice windows.
 * Every case diffed against refLastIndexOf (ES spec) / indexOf symmetry. */

function mkRnd(n, seed, hi) {
  var s = "";
  var x = seed | 0;
  for (var i = 0; i < n; i++) {
    x = (x * 1103515245 + 12345) & 0x7fffffff;
    s += String.fromCharCode((hi ? 65 : 97) + (x >>> 16) % 26);
  }
  return s;
}
function mkWide(n, seed) {
  var s = "\u1450";
  var x = seed | 0;
  for (var i = 0; i < n; i++) {
    x = (x * 1103515245 + 12345) & 0x7fffffff;
    s += String.fromCharCode(0x100 + (x >>> 16) % 500);
  }
  return s;
}
function mkWideNarrowable(n) {
  var s = "\u1450";
  for (var i = 0; i < n; i++) s += String.fromCharCode(0xF7 - (i % 90));
  return s;
}
function lit64() { return "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ab"; }
function refLastIndexOf(s, needle, from) {
  var n = s.length, m = needle.length;
  if (arguments.length < 3 || from === undefined || from !== from)
    from = Infinity;
  var k = Math.min(Math.max(from, 0), n - m);
  if (n - m < 0) return -1;
  while (k >= 0) { if (s.substring(k, k + m) === needle) return k; k--; }
  return -1;
}
var P = mkRnd(50000, 101, false);
var PW = mkWide(20000, 102);
var sliceSizes = [100, 1024, 1025, 4096, 16384, 50000];

test("m3_lidx_matrix", function () {
  var seeds = [1, 2, 3];
  for (var si = 0; si < sliceSizes.length; si++) {
    var L = sliceSizes[si];
    var S = P.slice(0, L);
    for (var ni = 0; ni < 6; ni++) {
      var ndLen = [1, 2, 5, 30][ni % 4];
      var pos = (ni * 7919 + si * 104729) % Math.max(1, L - ndLen);
      var nd = P.substring(pos, pos + ndLen);
      var got = S.lastIndexOf(nd);
      var want = refLastIndexOf(S, nd, undefined);
      eq(got, want, "lidx L=" + L + " pos=" + pos + " nl=" + ndLen);
      var fi = S.indexOf(nd);
      ok(fi <= got && got <= L, "idx<=lidx L=" + L + " pos=" + pos);
      ok(fi < 0 || S.substring(fi, fi + nd.length) === nd, "idx match valid L=" + L);
      for (var f = 0; f < 4; f++) {
        var from = [undefined, 0, pos, L][f];
        eq(S.lastIndexOf(nd, from), refLastIndexOf(S, nd, from),
           "lidx from L=" + L + " pos=" + pos + " f=" + f);
      }
    }
    var absent = "QQ-absent-" + si;
    eq(S.lastIndexOf(absent), -1, "lidx absent L=" + L);
    eq(S.indexOf(absent), -1, "idx absent L=" + L);
    var across = P.substring(L - 5, L + 5);
    var fi = S.indexOf(across);
    /* across content may recur inside a random haystack; the invariant is
       that any match lies wholly inside the window */
    ok(fi === -1 || fi <= L - 10, "across-end match wholly inside L=" + L);
  }
});
test("m3_lidx_wide_matrix", function () {
  for (var si = 0; si < sliceSizes.length; si++) {
    var L = Math.min(sliceSizes[si], PW.length);
    var S = PW.slice(0, L);
    for (var ni = 0; ni < 4; ni++) {
      var pos = (ni * 6007 + si * 8191) % Math.max(1, L - 8);
      var nd = PW.substring(pos, pos + 8);
      eq(S.lastIndexOf(nd), refLastIndexOf(S, nd, undefined),
         "wide lidx L=" + L + " pos=" + pos);
      eq(S.indexOf(nd), refLastIndexOf(S, nd, undefined) === -1 ? -1 : S.indexOf(nd),
         "wide idx sanity L=" + L);
    }
  }
});
summary("sliced_waveB");
