/* GENERATED by gen_matrix.js — T4 narrow-at-flatten content matrices.
 * Wide all-latin1 slices + short/long concats; content compared to the
 * spec concatenation. */

function mkRnd(n, seed, hi) {
  var s = "";
  var x = seed | 0;
  for (var i = 0; i < n; i++) {
    x = (x * 1103515245 + 12345) & 0x7fffffff;
    s += String.fromCharCode((hi ? 65 : 97) + (x >>> 16) % 26);
  }
  return s;
}
function mkWide(n, seed) {
  var s = "\u1450";
  var x = seed | 0;
  for (var i = 0; i < n; i++) {
    x = (x * 1103515245 + 12345) & 0x7fffffff;
    s += String.fromCharCode(0x100 + (x >>> 16) % 500);
  }
  return s;
}
function mkWideNarrowable(n) {
  var s = "\u1450";
  for (var i = 0; i < n; i++) s += String.fromCharCode(0xF7 - (i % 90));
  return s;
}
function lit64() { return "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ab"; }
var sizes = [64, 65, 127, 128, 255, 256, 1000, 2000];
var WN = mkWideNarrowable(3000);

test("m4_flatten_matrix", function () {
  for (var i = 0; i < sizes.length; i++) {
    var L = sizes[i];
    var S = WN.slice(1, 1 + L);
    var tail = S + "xy";
    ok(tail === WN.substring(1, 1 + L) + "xy", "tail L=" + L);
    var head = "xy" + S;
    ok(head === "xy" + WN.substring(1, 1 + L), "head L=" + L);
    var both = S + S;
    ok(both === WN.substring(1, 1 + L) + WN.substring(1, 1 + L), "both L=" + L);
    eq(tail.length, L + 2, "tail length L=" + L);
    eq(tail.charCodeAt(L), 120, "first tail unit L=" + L);
  }
});
test("m4_genuine_wide_untouched", function () {
  var G = mkWide(2000, 77);
  var S = G.slice(0, 2000);
  var r = S + "x";
  ok(r === G.substring(0, 2000) + "x", "genuine wide concat content");
  eq(r.charCodeAt(r.length - 1), 120, "narrow tail unit");
  ok(r.indexOf("\u1450") === 0, "wide head intact");
});
summary("sliced_waveB");
