// converted from console.log/print oracle: expectations baked from the
// node oracle; dynajs-vs-node divergences are explicit DIVERGE entries.
__EXP = null;
// parametric probe generated by tools_agent/gen_param.py
// expectations baked from the node oracle at generation time
__EXP = null;
const OP = { B0: 0n, B1: 1n, B2: 2n, B3: 3n, B4: 4n, B5: 5n, B6: 6n, B7: 7n, B8: 8n, B9: 9n, B10: 10n, B11: 11n, B12: 12n, B13: 13n, B14: 14n, B15: 15n, B16: 16n };
function dispatch(op, x) {
    switch (op) {
        case OP.B0: return 0n + 1n;
        case OP.B1: return 1n + 1n;
        case OP.B2: return 2n + 1n;
        case OP.B3: return 3n + 1n;
        case OP.B4: return 4n + 1n;
        case OP.B5: return 5n + 1n;
        case OP.B6: return 6n + 1n;
        case OP.B7: return 7n + 1n;
        case OP.B8: return 8n + 1n;
        case OP.B9: return 9n + 1n;
        case OP.B10: return 10n + 1n;
        case OP.B11: return 11n + 1n;
        case OP.B12: return 12n + 1n;
        case OP.B13: return 13n + 1n;
        case OP.B14: return 14n + 1n;
        case OP.B15: return 15n + 1n;
        case OP.B16: return 16n + 1n;
        default: return -1;
    }
}
function key(i) { return OP[Object.keys(OP)[i]]; }
test("hit0", function () { assert_eq(String((function(){ return dispatch(OP.B0, 0); })()), "1", "hit0"); });
test("hit1", function () { assert_eq(String((function(){ return dispatch(OP.B1, 0); })()), "2", "hit1"); });
test("hit2", function () { assert_eq(String((function(){ return dispatch(OP.B2, 0); })()), "3", "hit2"); });
test("hit3", function () { assert_eq(String((function(){ return dispatch(OP.B3, 0); })()), "4", "hit3"); });
test("hit4", function () { assert_eq(String((function(){ return dispatch(OP.B4, 0); })()), "5", "hit4"); });
test("hit5", function () { assert_eq(String((function(){ return dispatch(OP.B5, 0); })()), "6", "hit5"); });
test("hit6", function () { assert_eq(String((function(){ return dispatch(OP.B6, 0); })()), "7", "hit6"); });
test("hit7", function () { assert_eq(String((function(){ return dispatch(OP.B7, 0); })()), "8", "hit7"); });
test("hit8", function () { assert_eq(String((function(){ return dispatch(OP.B8, 0); })()), "9", "hit8"); });
test("hit9", function () { assert_eq(String((function(){ return dispatch(OP.B9, 0); })()), "10", "hit9"); });
test("hit10", function () { assert_eq(String((function(){ return dispatch(OP.B10, 0); })()), "11", "hit10"); });
test("hit11", function () { assert_eq(String((function(){ return dispatch(OP.B11, 0); })()), "12", "hit11"); });
test("hit12", function () { assert_eq(String((function(){ return dispatch(OP.B12, 0); })()), "13", "hit12"); });
test("hit13", function () { assert_eq(String((function(){ return dispatch(OP.B13, 0); })()), "14", "hit13"); });
test("hit14", function () { assert_eq(String((function(){ return dispatch(OP.B14, 0); })()), "15", "hit14"); });
test("hit15", function () { assert_eq(String((function(){ return dispatch(OP.B15, 0); })()), "16", "hit15"); });
test("hit16", function () { assert_eq(String((function(){ return dispatch(OP.B16, 0); })()), "17", "hit16"); });
test("miss", function () { assert_eq(String((function(){ return dispatch(undefined, 5); })()), "-1", "miss"); });
test("keycount", function () { assert_eq(String((function(){ return Object.keys(OP).length; })()), "17", "keycount"); });
test("frozentype", function () { assert_eq(String((function(){ return typeof OP; })()), "object", "frozentype"); });
summary("constprop");

summary("constprop");
