// converted from console.log/print oracle: expectations baked from the
// node oracle; dynajs-vs-node divergences are explicit DIVERGE entries.
__EXP = null;
// parametric probe generated by tools_agent/gen_param.py
// expectations baked from the node oracle at generation time
__EXP = null;
const OP = { B0: 0n, B1: 1n, B2: 2n, B3: 3n, B4: 4n, B5: 5n, B6: 6n, B7: 7n, B8: 8n, B9: 9n, B10: 10n, B11: 11n, B12: 12n, B13: 13n, B14: 14n, B15: 15n, B16: 16n, B17: 17n, B18: 18n, B19: 19n, B20: 20n, B21: 21n, B22: 22n, B23: 23n, B24: 24n, B25: 25n, B26: 26n, B27: 27n, B28: 28n, B29: 29n, B30: 30n };
function dispatch(op, x) {
    switch (op) {
        case OP.B0: return 0n + 1n;
        case OP.B1: return 1n + 1n;
        case OP.B2: return 2n + 1n;
        case OP.B3: return 3n + 1n;
        case OP.B4: return 4n + 1n;
        case OP.B5: return 5n + 1n;
        case OP.B6: return 6n + 1n;
        case OP.B7: return 7n + 1n;
        case OP.B8: return 8n + 1n;
        case OP.B9: return 9n + 1n;
        case OP.B10: return 10n + 1n;
        case OP.B11: return 11n + 1n;
        case OP.B12: return 12n + 1n;
        case OP.B13: return 13n + 1n;
        case OP.B14: return 14n + 1n;
        case OP.B15: return 15n + 1n;
        case OP.B16: return 16n + 1n;
        case OP.B17: return 17n + 1n;
        case OP.B18: return 18n + 1n;
        case OP.B19: return 19n + 1n;
        case OP.B20: return 20n + 1n;
        case OP.B21: return 21n + 1n;
        case OP.B22: return 22n + 1n;
        case OP.B23: return 23n + 1n;
        case OP.B24: return 24n + 1n;
        case OP.B25: return 25n + 1n;
        case OP.B26: return 26n + 1n;
        case OP.B27: return 27n + 1n;
        case OP.B28: return 28n + 1n;
        case OP.B29: return 29n + 1n;
        case OP.B30: return 30n + 1n;
        default: return -1;
    }
}
function key(i) { return OP[Object.keys(OP)[i]]; }
test("hit0", function () { assert_eq(String((function(){ return dispatch(OP.B0, 0); })()), "1", "hit0"); });
test("hit1", function () { assert_eq(String((function(){ return dispatch(OP.B1, 0); })()), "2", "hit1"); });
test("hit2", function () { assert_eq(String((function(){ return dispatch(OP.B2, 0); })()), "3", "hit2"); });
test("hit3", function () { assert_eq(String((function(){ return dispatch(OP.B3, 0); })()), "4", "hit3"); });
test("hit4", function () { assert_eq(String((function(){ return dispatch(OP.B4, 0); })()), "5", "hit4"); });
test("hit5", function () { assert_eq(String((function(){ return dispatch(OP.B5, 0); })()), "6", "hit5"); });
test("hit6", function () { assert_eq(String((function(){ return dispatch(OP.B6, 0); })()), "7", "hit6"); });
test("hit7", function () { assert_eq(String((function(){ return dispatch(OP.B7, 0); })()), "8", "hit7"); });
test("hit8", function () { assert_eq(String((function(){ return dispatch(OP.B8, 0); })()), "9", "hit8"); });
test("hit9", function () { assert_eq(String((function(){ return dispatch(OP.B9, 0); })()), "10", "hit9"); });
test("hit10", function () { assert_eq(String((function(){ return dispatch(OP.B10, 0); })()), "11", "hit10"); });
test("hit11", function () { assert_eq(String((function(){ return dispatch(OP.B11, 0); })()), "12", "hit11"); });
test("hit12", function () { assert_eq(String((function(){ return dispatch(OP.B12, 0); })()), "13", "hit12"); });
test("hit13", function () { assert_eq(String((function(){ return dispatch(OP.B13, 0); })()), "14", "hit13"); });
test("hit14", function () { assert_eq(String((function(){ return dispatch(OP.B14, 0); })()), "15", "hit14"); });
test("hit15", function () { assert_eq(String((function(){ return dispatch(OP.B15, 0); })()), "16", "hit15"); });
test("hit16", function () { assert_eq(String((function(){ return dispatch(OP.B16, 0); })()), "17", "hit16"); });
test("hit17", function () { assert_eq(String((function(){ return dispatch(OP.B17, 0); })()), "18", "hit17"); });
test("hit18", function () { assert_eq(String((function(){ return dispatch(OP.B18, 0); })()), "19", "hit18"); });
test("hit19", function () { assert_eq(String((function(){ return dispatch(OP.B19, 0); })()), "20", "hit19"); });
test("hit20", function () { assert_eq(String((function(){ return dispatch(OP.B20, 0); })()), "21", "hit20"); });
test("hit21", function () { assert_eq(String((function(){ return dispatch(OP.B21, 0); })()), "22", "hit21"); });
test("hit22", function () { assert_eq(String((function(){ return dispatch(OP.B22, 0); })()), "23", "hit22"); });
test("hit23", function () { assert_eq(String((function(){ return dispatch(OP.B23, 0); })()), "24", "hit23"); });
test("hit24", function () { assert_eq(String((function(){ return dispatch(OP.B24, 0); })()), "25", "hit24"); });
test("hit25", function () { assert_eq(String((function(){ return dispatch(OP.B25, 0); })()), "26", "hit25"); });
test("hit26", function () { assert_eq(String((function(){ return dispatch(OP.B26, 0); })()), "27", "hit26"); });
test("hit27", function () { assert_eq(String((function(){ return dispatch(OP.B27, 0); })()), "28", "hit27"); });
test("hit28", function () { assert_eq(String((function(){ return dispatch(OP.B28, 0); })()), "29", "hit28"); });
test("hit29", function () { assert_eq(String((function(){ return dispatch(OP.B29, 0); })()), "30", "hit29"); });
test("hit30", function () { assert_eq(String((function(){ return dispatch(OP.B30, 0); })()), "31", "hit30"); });
test("miss", function () { assert_eq(String((function(){ return dispatch(undefined, 5); })()), "-1", "miss"); });
test("keycount", function () { assert_eq(String((function(){ return Object.keys(OP).length; })()), "31", "keycount"); });
test("frozentype", function () { assert_eq(String((function(){ return typeof OP; })()), "object", "frozentype"); });
summary("constprop");

summary("constprop");
