// converted from console.log/print oracle: expectations baked from the
// node oracle; dynajs-vs-node divergences are explicit DIVERGE entries.
__EXP = null;
// parametric probe generated by tools_agent/gen_param.py
// expectations baked from the node oracle at generation time
__EXP = null;
const OP = { S0: "s0", S1: "s1", S2: "s2", S3: "s3", S4: "s4", S5: "s5", S6: "s6", S7: "s7", S8: "s8", S9: "s9", S10: "s10", S11: "s11", S12: "s12", S13: "s13", S14: "s14", S15: "s15", S16: "s16", S17: "s17", S18: "s18", S19: "s19", S20: "s20", S21: "s21", S22: "s22", S23: "s23", S24: "s24", S25: "s25", S26: "s26", S27: "s27", S28: "s28", S29: "s29", S30: "s30" };
function dispatch(op, x) {
    switch (op) {
        case OP.S0: return "s" + 0;
        case OP.S1: return "s" + 1;
        case OP.S2: return "s" + 2;
        case OP.S3: return "s" + 3;
        case OP.S4: return "s" + 4;
        case OP.S5: return "s" + 5;
        case OP.S6: return "s" + 6;
        case OP.S7: return "s" + 7;
        case OP.S8: return "s" + 8;
        case OP.S9: return "s" + 9;
        case OP.S10: return "s" + 10;
        case OP.S11: return "s" + 11;
        case OP.S12: return "s" + 12;
        case OP.S13: return "s" + 13;
        case OP.S14: return "s" + 14;
        case OP.S15: return "s" + 15;
        case OP.S16: return "s" + 16;
        case OP.S17: return "s" + 17;
        case OP.S18: return "s" + 18;
        case OP.S19: return "s" + 19;
        case OP.S20: return "s" + 20;
        case OP.S21: return "s" + 21;
        case OP.S22: return "s" + 22;
        case OP.S23: return "s" + 23;
        case OP.S24: return "s" + 24;
        case OP.S25: return "s" + 25;
        case OP.S26: return "s" + 26;
        case OP.S27: return "s" + 27;
        case OP.S28: return "s" + 28;
        case OP.S29: return "s" + 29;
        case OP.S30: return "s" + 30;
        default: return -1;
    }
}
function key(i) { return OP[Object.keys(OP)[i]]; }
test("hit0", function () { assert_eq(String((function(){ return dispatch(OP.S0, 0); })()), "s0", "hit0"); });
test("hit1", function () { assert_eq(String((function(){ return dispatch(OP.S1, 0); })()), "s1", "hit1"); });
test("hit2", function () { assert_eq(String((function(){ return dispatch(OP.S2, 0); })()), "s2", "hit2"); });
test("hit3", function () { assert_eq(String((function(){ return dispatch(OP.S3, 0); })()), "s3", "hit3"); });
test("hit4", function () { assert_eq(String((function(){ return dispatch(OP.S4, 0); })()), "s4", "hit4"); });
test("hit5", function () { assert_eq(String((function(){ return dispatch(OP.S5, 0); })()), "s5", "hit5"); });
test("hit6", function () { assert_eq(String((function(){ return dispatch(OP.S6, 0); })()), "s6", "hit6"); });
test("hit7", function () { assert_eq(String((function(){ return dispatch(OP.S7, 0); })()), "s7", "hit7"); });
test("hit8", function () { assert_eq(String((function(){ return dispatch(OP.S8, 0); })()), "s8", "hit8"); });
test("hit9", function () { assert_eq(String((function(){ return dispatch(OP.S9, 0); })()), "s9", "hit9"); });
test("hit10", function () { assert_eq(String((function(){ return dispatch(OP.S10, 0); })()), "s10", "hit10"); });
test("hit11", function () { assert_eq(String((function(){ return dispatch(OP.S11, 0); })()), "s11", "hit11"); });
test("hit12", function () { assert_eq(String((function(){ return dispatch(OP.S12, 0); })()), "s12", "hit12"); });
test("hit13", function () { assert_eq(String((function(){ return dispatch(OP.S13, 0); })()), "s13", "hit13"); });
test("hit14", function () { assert_eq(String((function(){ return dispatch(OP.S14, 0); })()), "s14", "hit14"); });
test("hit15", function () { assert_eq(String((function(){ return dispatch(OP.S15, 0); })()), "s15", "hit15"); });
test("hit16", function () { assert_eq(String((function(){ return dispatch(OP.S16, 0); })()), "s16", "hit16"); });
test("hit17", function () { assert_eq(String((function(){ return dispatch(OP.S17, 0); })()), "s17", "hit17"); });
test("hit18", function () { assert_eq(String((function(){ return dispatch(OP.S18, 0); })()), "s18", "hit18"); });
test("hit19", function () { assert_eq(String((function(){ return dispatch(OP.S19, 0); })()), "s19", "hit19"); });
test("hit20", function () { assert_eq(String((function(){ return dispatch(OP.S20, 0); })()), "s20", "hit20"); });
test("hit21", function () { assert_eq(String((function(){ return dispatch(OP.S21, 0); })()), "s21", "hit21"); });
test("hit22", function () { assert_eq(String((function(){ return dispatch(OP.S22, 0); })()), "s22", "hit22"); });
test("hit23", function () { assert_eq(String((function(){ return dispatch(OP.S23, 0); })()), "s23", "hit23"); });
test("hit24", function () { assert_eq(String((function(){ return dispatch(OP.S24, 0); })()), "s24", "hit24"); });
test("hit25", function () { assert_eq(String((function(){ return dispatch(OP.S25, 0); })()), "s25", "hit25"); });
test("hit26", function () { assert_eq(String((function(){ return dispatch(OP.S26, 0); })()), "s26", "hit26"); });
test("hit27", function () { assert_eq(String((function(){ return dispatch(OP.S27, 0); })()), "s27", "hit27"); });
test("hit28", function () { assert_eq(String((function(){ return dispatch(OP.S28, 0); })()), "s28", "hit28"); });
test("hit29", function () { assert_eq(String((function(){ return dispatch(OP.S29, 0); })()), "s29", "hit29"); });
test("hit30", function () { assert_eq(String((function(){ return dispatch(OP.S30, 0); })()), "s30", "hit30"); });
test("miss", function () { assert_eq(String((function(){ return dispatch(undefined, 5); })()), "-1", "miss"); });
test("keycount", function () { assert_eq(String((function(){ return Object.keys(OP).length; })()), "31", "keycount"); });
test("frozentype", function () { assert_eq(String((function(){ return typeof OP; })()), "object", "frozentype"); });
summary("constprop");

summary("constprop");
