// converted from console.log/print oracle: expectations baked from the
// node oracle; dynajs-vs-node divergences are explicit DIVERGE entries.
__EXP = null;
// parametric probe generated by tools_agent/gen_param.py
// expectations baked from the node oracle at generation time
__EXP = null;
const OP = { S0: "s0", S1: "s1", S2: "s2", S3: "s3", S4: "s4", S5: "s5", S6: "s6", S7: "s7", S8: "s8", S9: "s9", S10: "s10", S11: "s11", S12: "s12", S13: "s13", S14: "s14", S15: "s15", S16: "s16" };
function dispatch(op, x) {
    switch (op) {
        case OP.S0: return "s" + 0;
        case OP.S1: return "s" + 1;
        case OP.S2: return "s" + 2;
        case OP.S3: return "s" + 3;
        case OP.S4: return "s" + 4;
        case OP.S5: return "s" + 5;
        case OP.S6: return "s" + 6;
        case OP.S7: return "s" + 7;
        case OP.S8: return "s" + 8;
        case OP.S9: return "s" + 9;
        case OP.S10: return "s" + 10;
        case OP.S11: return "s" + 11;
        case OP.S12: return "s" + 12;
        case OP.S13: return "s" + 13;
        case OP.S14: return "s" + 14;
        case OP.S15: return "s" + 15;
        case OP.S16: return "s" + 16;
        default: return -1;
    }
}
function key(i) { return OP[Object.keys(OP)[i]]; }
test("hit0", function () { assert_eq(String((function(){ return dispatch(OP.S0, 0); })()), "s0", "hit0"); });
test("hit1", function () { assert_eq(String((function(){ return dispatch(OP.S1, 0); })()), "s1", "hit1"); });
test("hit2", function () { assert_eq(String((function(){ return dispatch(OP.S2, 0); })()), "s2", "hit2"); });
test("hit3", function () { assert_eq(String((function(){ return dispatch(OP.S3, 0); })()), "s3", "hit3"); });
test("hit4", function () { assert_eq(String((function(){ return dispatch(OP.S4, 0); })()), "s4", "hit4"); });
test("hit5", function () { assert_eq(String((function(){ return dispatch(OP.S5, 0); })()), "s5", "hit5"); });
test("hit6", function () { assert_eq(String((function(){ return dispatch(OP.S6, 0); })()), "s6", "hit6"); });
test("hit7", function () { assert_eq(String((function(){ return dispatch(OP.S7, 0); })()), "s7", "hit7"); });
test("hit8", function () { assert_eq(String((function(){ return dispatch(OP.S8, 0); })()), "s8", "hit8"); });
test("hit9", function () { assert_eq(String((function(){ return dispatch(OP.S9, 0); })()), "s9", "hit9"); });
test("hit10", function () { assert_eq(String((function(){ return dispatch(OP.S10, 0); })()), "s10", "hit10"); });
test("hit11", function () { assert_eq(String((function(){ return dispatch(OP.S11, 0); })()), "s11", "hit11"); });
test("hit12", function () { assert_eq(String((function(){ return dispatch(OP.S12, 0); })()), "s12", "hit12"); });
test("hit13", function () { assert_eq(String((function(){ return dispatch(OP.S13, 0); })()), "s13", "hit13"); });
test("hit14", function () { assert_eq(String((function(){ return dispatch(OP.S14, 0); })()), "s14", "hit14"); });
test("hit15", function () { assert_eq(String((function(){ return dispatch(OP.S15, 0); })()), "s15", "hit15"); });
test("hit16", function () { assert_eq(String((function(){ return dispatch(OP.S16, 0); })()), "s16", "hit16"); });
test("miss", function () { assert_eq(String((function(){ return dispatch(undefined, 5); })()), "-1", "miss"); });
test("keycount", function () { assert_eq(String((function(){ return Object.keys(OP).length; })()), "17", "keycount"); });
test("frozentype", function () { assert_eq(String((function(){ return typeof OP; })()), "object", "frozentype"); });
summary("constprop");

summary("constprop");
