// converted from console.log/print oracle: expectations baked from the
// node oracle; dynajs-vs-node divergences are explicit DIVERGE entries.
__EXP = null;
// parametric probe generated by tools_agent/gen_param.py
// expectations baked from the node oracle at generation time
__EXP = null;
const OP = { K0: 0 * 2, K1: 1 * 2, K2: 2 * 2, K3: 3 * 2, K4: 4 * 2 };
try { OP.K0 = 999; } catch (e) {}
function dispatch(op, x) {
    switch (op) {
        case OP.K0: return x + 0;
        case OP.K1: return x + 1;
        case OP.K2: return x + 2;
        case OP.K3: return x + 3;
        case OP.K4: return x + 4;
        default: return -1;
    }
}
function key(i) { return OP[Object.keys(OP)[i]]; }
test("hit0", function () { assert_eq(String((function(){ return dispatch(OP.K0, 10); })()), "10", "hit0"); });
test("hit1", function () { assert_eq(String((function(){ return dispatch(OP.K1, 10); })()), "11", "hit1"); });
test("hit2", function () { assert_eq(String((function(){ return dispatch(OP.K2, 10); })()), "12", "hit2"); });
test("hit3", function () { assert_eq(String((function(){ return dispatch(OP.K3, 10); })()), "13", "hit3"); });
test("hit4", function () { assert_eq(String((function(){ return dispatch(OP.K4, 10); })()), "14", "hit4"); });
test("miss", function () { assert_eq(String((function(){ return dispatch(undefined, 5); })()), "-1", "miss"); });
test("arith", function () { assert_eq(String((function(){ return dispatch(key(3), 1); })()), "4", "arith"); });
test("keycount", function () { assert_eq(String((function(){ return Object.keys(OP).length; })()), "5", "keycount"); });
test("frozentype", function () { assert_eq(String((function(){ return typeof OP; })()), "object", "frozentype"); });
summary("constprop");

summary("constprop");
