// converted from console.log/print oracle: expectations baked from the
// node oracle; dynajs-vs-node divergences are explicit DIVERGE entries.
__EXP = null;
// parametric probe generated by tools_agent/gen_param.py
// expectations baked from the node oracle at generation time
__EXP = null;
const OP = { S0: "s0", S1: "s1" };
function dispatch(op, x) {
    switch (op) {
        case OP.S0: return "s" + 0;
        case OP.S1: return "s" + 1;
        default: return -1;
    }
}
function key(i) { return OP[Object.keys(OP)[i]]; }
test("hit0", function () { assert_eq(String((function(){ return dispatch(OP.S0, 0); })()), "s0", "hit0"); });
test("hit1", function () { assert_eq(String((function(){ return dispatch(OP.S1, 0); })()), "s1", "hit1"); });
test("miss", function () { assert_eq(String((function(){ return dispatch(undefined, 5); })()), "-1", "miss"); });
test("keycount", function () { assert_eq(String((function(){ return Object.keys(OP).length; })()), "2", "keycount"); });
test("frozentype", function () { assert_eq(String((function(){ return typeof OP; })()), "object", "frozentype"); });
summary("constprop");

summary("constprop");
