// converted from console.log/print oracle: expectations baked from the
// node oracle; dynajs-vs-node divergences are explicit DIVERGE entries.
__EXP = null;
// parametric probe generated by tools_agent/gen_param.py
// expectations baked from the node oracle at generation time
__EXP = null;
const OP = { K0: 0 * 2, K1: 1 * 2 };
function dispatch(op, x) {
    switch (op) {
        case OP.K0: return x + 0;
        case OP.K1: return x + 1;
        default: return -1;
    }
}
function key(i) { return OP[Object.keys(OP)[i]]; }
test("hit0", function () { assert_eq(String((function(){ return dispatch(OP.K0, 10); })()), "10", "hit0"); });
test("hit1", function () { assert_eq(String((function(){ return dispatch(OP.K1, 10); })()), "11", "hit1"); });
test("miss", function () { assert_eq(String((function(){ return dispatch(undefined, 5); })()), "-1", "miss"); });
test("arith", function () { assert_eq(String((function(){ return dispatch(key(3), 1); })()), "-1", "arith"); });
test("keycount", function () { assert_eq(String((function(){ return Object.keys(OP).length; })()), "2", "keycount"); });
test("frozentype", function () { assert_eq(String((function(){ return typeof OP; })()), "object", "frozentype"); });
summary("constprop");

summary("constprop");
