// converted from console.log/print oracle: expectations baked from the
// node oracle; dynajs-vs-node divergences are explicit DIVERGE entries.
__EXP = null;
// parametric probe generated by tools_agent/gen_param.py
// expectations baked from the node oracle at generation time
__EXP = null;
const OP = { K0: 0 * 2, K1: 1 * 2, K2: 2 * 2, K3: 3 * 2, K4: 4 * 2, K5: 5 * 2, K6: 6 * 2, K7: 7 * 2, K8: 8 * 2, K9: 9 * 2, K10: 10 * 2, K11: 11 * 2, K12: 12 * 2, K13: 13 * 2, K14: 14 * 2, K15: 15 * 2, K16: 16 * 2, K17: 17 * 2, K18: 18 * 2, K19: 19 * 2, K20: 20 * 2, K21: 21 * 2, K22: 22 * 2, K23: 23 * 2, K24: 24 * 2, K25: 25 * 2, K26: 26 * 2, K27: 27 * 2, K28: 28 * 2, K29: 29 * 2, K30: 30 * 2 };
try { OP.K0 = 999; } catch (e) {}
function dispatch(op, x) {
    switch (op) {
        case OP.K0: return x + 0;
        case OP.K1: return x + 1;
        case OP.K2: return x + 2;
        case OP.K3: return x + 3;
        case OP.K4: return x + 4;
        case OP.K5: return x + 5;
        case OP.K6: return x + 6;
        case OP.K7: return x + 7;
        case OP.K8: return x + 8;
        case OP.K9: return x + 9;
        case OP.K10: return x + 10;
        case OP.K11: return x + 11;
        case OP.K12: return x + 12;
        case OP.K13: return x + 13;
        case OP.K14: return x + 14;
        case OP.K15: return x + 15;
        case OP.K16: return x + 16;
        case OP.K17: return x + 17;
        case OP.K18: return x + 18;
        case OP.K19: return x + 19;
        case OP.K20: return x + 20;
        case OP.K21: return x + 21;
        case OP.K22: return x + 22;
        case OP.K23: return x + 23;
        case OP.K24: return x + 24;
        case OP.K25: return x + 25;
        case OP.K26: return x + 26;
        case OP.K27: return x + 27;
        case OP.K28: return x + 28;
        case OP.K29: return x + 29;
        case OP.K30: return x + 30;
        default: return -1;
    }
}
function key(i) { return OP[Object.keys(OP)[i]]; }
test("hit0", function () { assert_eq(String((function(){ return dispatch(OP.K0, 10); })()), "10", "hit0"); });
test("hit1", function () { assert_eq(String((function(){ return dispatch(OP.K1, 10); })()), "11", "hit1"); });
test("hit2", function () { assert_eq(String((function(){ return dispatch(OP.K2, 10); })()), "12", "hit2"); });
test("hit3", function () { assert_eq(String((function(){ return dispatch(OP.K3, 10); })()), "13", "hit3"); });
test("hit4", function () { assert_eq(String((function(){ return dispatch(OP.K4, 10); })()), "14", "hit4"); });
test("hit5", function () { assert_eq(String((function(){ return dispatch(OP.K5, 10); })()), "15", "hit5"); });
test("hit6", function () { assert_eq(String((function(){ return dispatch(OP.K6, 10); })()), "16", "hit6"); });
test("hit7", function () { assert_eq(String((function(){ return dispatch(OP.K7, 10); })()), "17", "hit7"); });
test("hit8", function () { assert_eq(String((function(){ return dispatch(OP.K8, 10); })()), "18", "hit8"); });
test("hit9", function () { assert_eq(String((function(){ return dispatch(OP.K9, 10); })()), "19", "hit9"); });
test("hit10", function () { assert_eq(String((function(){ return dispatch(OP.K10, 10); })()), "20", "hit10"); });
test("hit11", function () { assert_eq(String((function(){ return dispatch(OP.K11, 10); })()), "21", "hit11"); });
test("hit12", function () { assert_eq(String((function(){ return dispatch(OP.K12, 10); })()), "22", "hit12"); });
test("hit13", function () { assert_eq(String((function(){ return dispatch(OP.K13, 10); })()), "23", "hit13"); });
test("hit14", function () { assert_eq(String((function(){ return dispatch(OP.K14, 10); })()), "24", "hit14"); });
test("hit15", function () { assert_eq(String((function(){ return dispatch(OP.K15, 10); })()), "25", "hit15"); });
test("hit16", function () { assert_eq(String((function(){ return dispatch(OP.K16, 10); })()), "26", "hit16"); });
test("hit17", function () { assert_eq(String((function(){ return dispatch(OP.K17, 10); })()), "27", "hit17"); });
test("hit18", function () { assert_eq(String((function(){ return dispatch(OP.K18, 10); })()), "28", "hit18"); });
test("hit19", function () { assert_eq(String((function(){ return dispatch(OP.K19, 10); })()), "29", "hit19"); });
test("hit20", function () { assert_eq(String((function(){ return dispatch(OP.K20, 10); })()), "30", "hit20"); });
test("hit21", function () { assert_eq(String((function(){ return dispatch(OP.K21, 10); })()), "31", "hit21"); });
test("hit22", function () { assert_eq(String((function(){ return dispatch(OP.K22, 10); })()), "32", "hit22"); });
test("hit23", function () { assert_eq(String((function(){ return dispatch(OP.K23, 10); })()), "33", "hit23"); });
test("hit24", function () { assert_eq(String((function(){ return dispatch(OP.K24, 10); })()), "34", "hit24"); });
test("hit25", function () { assert_eq(String((function(){ return dispatch(OP.K25, 10); })()), "35", "hit25"); });
test("hit26", function () { assert_eq(String((function(){ return dispatch(OP.K26, 10); })()), "36", "hit26"); });
test("hit27", function () { assert_eq(String((function(){ return dispatch(OP.K27, 10); })()), "37", "hit27"); });
test("hit28", function () { assert_eq(String((function(){ return dispatch(OP.K28, 10); })()), "38", "hit28"); });
test("hit29", function () { assert_eq(String((function(){ return dispatch(OP.K29, 10); })()), "39", "hit29"); });
test("hit30", function () { assert_eq(String((function(){ return dispatch(OP.K30, 10); })()), "40", "hit30"); });
test("miss", function () { assert_eq(String((function(){ return dispatch(undefined, 5); })()), "-1", "miss"); });
test("arith", function () { assert_eq(String((function(){ return dispatch(key(3), 1); })()), "4", "arith"); });
test("keycount", function () { assert_eq(String((function(){ return Object.keys(OP).length; })()), "31", "keycount"); });
test("frozentype", function () { assert_eq(String((function(){ return typeof OP; })()), "object", "frozentype"); });
summary("constprop");

summary("constprop");
