// converted from console.log/print oracle: expectations baked from the
// node oracle; dynajs-vs-node divergences are explicit DIVERGE entries.
__EXP = null;
// parametric probe generated by tools_agent/gen_param.py
// expectations baked from the node oracle at generation time
__EXP = null;
const OP = Object.freeze({ K0: 0 * 2, K1: 1 * 2, K2: 2 * 2, K3: 3 * 2, K4: 4 * 2, K5: 5 * 2, K6: 6 * 2, K7: 7 * 2, K8: 8 * 2, K9: 9 * 2, K10: 10 * 2, K11: 11 * 2, K12: 12 * 2, K13: 13 * 2, K14: 14 * 2, K15: 15 * 2, K16: 16 * 2 });
function dispatch(op, x) {
    switch (op) {
        case OP.K0: return x + 0;
        case OP.K1: return x + 1;
        case OP.K2: return x + 2;
        case OP.K3: return x + 3;
        case OP.K4: return x + 4;
        case OP.K5: return x + 5;
        case OP.K6: return x + 6;
        case OP.K7: return x + 7;
        case OP.K8: return x + 8;
        case OP.K9: return x + 9;
        case OP.K10: return x + 10;
        case OP.K11: return x + 11;
        case OP.K12: return x + 12;
        case OP.K13: return x + 13;
        case OP.K14: return x + 14;
        case OP.K15: return x + 15;
        case OP.K16: return x + 16;
        default: return -1;
    }
}
function key(i) { return OP[Object.keys(OP)[i]]; }
test("hit0", function () { assert_eq(String((function(){ return dispatch(OP.K0, 10); })()), "10", "hit0"); });
test("hit1", function () { assert_eq(String((function(){ return dispatch(OP.K1, 10); })()), "11", "hit1"); });
test("hit2", function () { assert_eq(String((function(){ return dispatch(OP.K2, 10); })()), "12", "hit2"); });
test("hit3", function () { assert_eq(String((function(){ return dispatch(OP.K3, 10); })()), "13", "hit3"); });
test("hit4", function () { assert_eq(String((function(){ return dispatch(OP.K4, 10); })()), "14", "hit4"); });
test("hit5", function () { assert_eq(String((function(){ return dispatch(OP.K5, 10); })()), "15", "hit5"); });
test("hit6", function () { assert_eq(String((function(){ return dispatch(OP.K6, 10); })()), "16", "hit6"); });
test("hit7", function () { assert_eq(String((function(){ return dispatch(OP.K7, 10); })()), "17", "hit7"); });
test("hit8", function () { assert_eq(String((function(){ return dispatch(OP.K8, 10); })()), "18", "hit8"); });
test("hit9", function () { assert_eq(String((function(){ return dispatch(OP.K9, 10); })()), "19", "hit9"); });
test("hit10", function () { assert_eq(String((function(){ return dispatch(OP.K10, 10); })()), "20", "hit10"); });
test("hit11", function () { assert_eq(String((function(){ return dispatch(OP.K11, 10); })()), "21", "hit11"); });
test("hit12", function () { assert_eq(String((function(){ return dispatch(OP.K12, 10); })()), "22", "hit12"); });
test("hit13", function () { assert_eq(String((function(){ return dispatch(OP.K13, 10); })()), "23", "hit13"); });
test("hit14", function () { assert_eq(String((function(){ return dispatch(OP.K14, 10); })()), "24", "hit14"); });
test("hit15", function () { assert_eq(String((function(){ return dispatch(OP.K15, 10); })()), "25", "hit15"); });
test("hit16", function () { assert_eq(String((function(){ return dispatch(OP.K16, 10); })()), "26", "hit16"); });
test("miss", function () { assert_eq(String((function(){ return dispatch(undefined, 5); })()), "-1", "miss"); });
test("arith", function () { assert_eq(String((function(){ return dispatch(key(3), 1); })()), "4", "arith"); });
test("keycount", function () { assert_eq(String((function(){ return Object.keys(OP).length; })()), "17", "keycount"); });
test("frozentype", function () { assert_eq(String((function(){ return typeof OP; })()), "object", "frozentype"); });
summary("constprop");

summary("constprop");
