// Generated by gen_train_modules.py -- PGO training module

export function bignumMul(a, b) {
  const A = a.split("").reverse().map(Number), B = b.split("").reverse().map(Number);
  const C = new Array(A.length + B.length).fill(0);
  for (let i = 0; i < A.length; i++) {
    let carry = 0;
    for (let j = 0; j < B.length; j++) {
      const cur = C[i + j] + A[i] * B[j] + carry;
      C[i + j] = cur % 10; carry = (cur / 10) | 0;
    }
    C[i + B.length] += carry;
  }
  let s = ""; let k = C.length - 1;
  while (k > 0 && C[k] === 0) k--;
  for (; k >= 0; k--) s += C[k];
  return s;
}

