// Generated by gen_train_modules.py -- PGO training module

export function lcg(n, seed) {
  const a = new Array(n); let s = seed >>> 0;
  for (let i = 0; i < n; i++) { s = (s * 1103515245 + 12345) >>> 0; a[i] = s % 100003; }
  return a;
}
export function qsort(a) {
  if (a.length < 2) return a;
  const p = a[a.length >> 1], lo = [], eq = [], hi = [];
  for (const x of a) { if (x < p) lo.push(x); else if (x > p) hi.push(x); else eq.push(x); }
  return [...qsort(lo), ...eq, ...qsort(hi)];
}

