// Generated by gen_train_modules.py -- PGO training module

export function parseCsv(text) {
  const lines = text.split("\n").filter(l => l.length);
  const rows = lines.map(l => l.split(",").map(f => /^\d+$/.test(f) ? parseInt(f, 10) : f));
  return { header: rows[0], rows: rows.slice(1) };
}

