// Generated by gen_train_modules.py -- PGO training module

const k1 = Symbol("k1"), k2 = Symbol.for("shared.k2");
export function symbols(n) {
  const o = { [k1]: 1, [k2]: 2, plain: 3 }; let sink = 0;
  for (let i = 0; i < n; i++) { o[k1] = i; sink += o[k1] + o[k2] + o.plain; }
  return sink % 109;
}

