// Generated by gen_train_modules.py -- PGO training module

export function regexpDrive(text, n) {
  let sink = 0;
  const re1 = /(ab)+/g, re2 = /abc/g, re3 = /\d+/g;
  for (let i = 0; i < n; i++) {
    let m; re1.lastIndex = 0; while ((m = re1.exec(text))) sink += m[0].length;
    re2.lastIndex = 0; while ((m = re2.exec(text))) sink += 1;
    re3.lastIndex = 0; while ((m = re3.exec(text))) sink += m[0].length;
    sink += text.replace(/ab/g, "AB").length % 3;
    sink += text.split(" ").length % 5;
  }
  return sink % 97;
}

