// Generated by gen_train_modules.py -- PGO training module

export class Matrix {
  constructor(n) { this.n = n; this.d = new Float64Array(n * n).fill(1.5); }
  trace() { let t = 0; for (let i = 0; i < this.n; i++) t += this.d[i * this.n + i]; return t; }
}
export function matmul(a, b) {
  const n = a.n, c = new Matrix(n), d = c.d, ad = a.d, bd = b.d;
  for (let i = 0; i < n; i++)
    for (let k = 0; k < n; k++) {
      const aik = ad[i * n + k];
      for (let j = 0; j < n; j++) d[i * n + j] += aik * bd[k * n + j];
    }
  return c;
}

