// Generated by gen_train_modules.py -- PGO training module

export function tokenizer(src) {
  let i = 0, count = 0; const toks = [];
  while (i < src.length) {
    const c = src[i];
    if (c === " " || c === "\n") { i++; continue; }
    if (c >= "0" && c <= "9") { let j = i; while (j < src.length && src[j] >= "0" && src[j] <= "9") j++; toks.push(src.slice(i, j)); i = j; }
    else if (/[a-zA-Z_$]/.test(c)) { let j = i; while (j < src.length && /\w/.test(src[j])) j++; toks.push(src.slice(i, j)); i = j; }
    else { toks.push(c); i++; }
    count++;
  }
  return { toks, count };
}

