// Generated by gen_train_modules.py -- PGO training module

export function errorPaths(n) {
  let sink = 0, caught = 0, thrown = 0;
  for (let i = 0; i < n; i++) {
    try {
      if (i % 3 === 0) { thrown++; throw new TypeError("t" + i); }
      if (i % 5 === 0) { thrown++; throw new RangeError("r" + i); }
      sink += i;
    } catch (e) { caught++; sink += e.message.length % 7; }
    finally { sink ^= 1; }
  }
  return (sink + caught + thrown) % 139;
}

