// Generated by gen_train_modules.py -- PGO training module

class Animal { constructor(name) { this.name = name; } speak() { return this.name + " makes a noise."; } }
class Dog extends Animal { speak() { return super.speak() + " Woof."; } }
class Puppy extends Dog { speak() { return super.speak() + " Yip!"; } }
export function classes(n) {
  let sink = 0; const d = new Dog("Rex"), p = new Puppy("Bit");
  for (let i = 0; i < n; i++) sink += d.speak().length + p.speak().length + i;
  return sink % 127;
}

