// Generated by gen_train_modules.py -- PGO training module

function sumTo(n, acc) { return n <= 0 ? acc : sumTo(n - 1, acc + n); }
function even(n) { return n === 0 ? true : odd(n - 1); }
function odd(n) { return n === 0 ? false : even(n - 1); }
export function tailRec(n) { return sumTo(n, 0) % 151 + (even(n) ? 2 : 1); }

