// Generated by gen_train_modules.py -- PGO training module

export function dateFmt(d, n) {
  let sink = 0;
  for (let i = 0; i < n; i++) {
    const t = new Date(d.getTime() + i * 3600e3);
    sink += t.getUTCFullYear() + t.getUTCMonth() + t.getUTCDate() + t.getUTCHours();
  }
  return sink % 7;
}

