// Generated by gen_train_modules.py -- PGO training module

export function iterators(n) {
  const o = { *[Symbol.iterator]() { for (let i = 0; i < 10; i++) yield i; } };
  let sink = 0;
  for (let r = 0; r < n / 10; r++) for (const x of o) sink += x;
  const arr = Array.from({ length: n / 10 }, (_, i) => i);
  sink += arr.reduce((a, b) => a + b, 0);
  sink += [...arr.slice(0, 50), ...arr.slice(50, 100)].length;
  return sink % 157;
}

