// Generated by gen_train_modules.py -- PGO training module

export function fib(n) { return n < 2 ? n : fib(n - 1) + fib(n - 2); }
export function ackermann(m, n) {
  if (m === 0) return n + 1;
  if (n === 0) return ackermann(m - 1, 1);
  return ackermann(m - 1, ackermann(m, n - 1));
}

