// Generated by gen_train_modules.py -- PGO training module

const base = { describe() { return "base"; }, v: 1 };
const mid = Object.create(base); mid.describe = function () { return "mid:" + this.v; };
const leaf = Object.create(mid);
export function protoChain(n) {
  let sink = 0;
  for (let i = 0; i < n; i++) { leaf.v = i; sink += leaf.describe().length; sink += base.v; }
  return sink % 101;
}

