// Generated by gen_train_modules.py -- PGO training module

export function typed(n) {
  const f = new Float64Array(n), i32 = new Int32Array(n); let sink = 0;
  for (let i = 0; i < n; i++) f[i] = i * 1.5;
  for (let i = 0; i < n; i++) i32[i] = f[i] | 0;
  for (let i = 0; i < n; i++) sink += i32[i] % 17;
  return sink % 131;
}

