// Generated by gen_train_modules.py -- PGO training module

export function sortDrive(n) {
  const a = new Array(n); let s = 12345;
  for (let i = 0; i < n; i++) { s = (s * 48271) % 2147483647; a[i] = s % n; }
  a.sort((x, y) => x - y);
  let sink = 0;
  for (let i = 1; i < n; i++) if (a[i] < a[i - 1]) sink++;
  a.sort();
  return (sink === 0 ? 1 : 0) + (a[0] === undefined ? 1 : 0);
}

