// Generated by gen_train_modules.py -- PGO training module

export function rot13(s) {
  let out = "";
  for (const ch of s) {
    const c = ch.codePointAt(0);
    if (c >= 65 && c <= 90) out += String.fromCharCode((c - 65 + 13) % 26 + 65);
    else if (c >= 97 && c <= 122) out += String.fromCharCode((c - 97 + 13) % 26 + 97);
    else out += ch;
  }
  return out;
}
export function piglatin(s) {
  return s.split(/([aeiou]\w*)/).filter(Boolean).join("-") + " ay";
}

