// converted from console.log/print oracle: expectations baked from the
// node oracle; dynajs-vs-node divergences are explicit DIVERGE entries.
__EXP = null;
// parametric probe generated by tools_agent/gen_param.py
// expectations baked from the node oracle at generation time
__EXP = null;
function mkParent(n) {
    var s = "";
    for (var i = 0; i < n; i++) {
        s += String.fromCodePoint(0x1F600 + (i % 8));
    }
    return s;
}
var parent = mkParent(1200);
var s = parent.slice(0, 65);
test("charat0", function () { assert_eq(String((function(){ return s.charAt(0); })()), "\ud83d", "charat0"); });
test("charat-k", function () { assert_eq(String((function(){ return s.charAt(3); })()), "\ude01", "charat-k"); });
test("charat-oob", function () { assert_eq(String((function(){ return s.charAt(70); })()), "", "charat-oob"); });
test("len", function () { assert_eq(String((function(){ return s.length; })()), "65", "len"); });
summary("sliced_strings");

summary("sliced_strings");
