// converted from console.log/print oracle: expectations baked from the
// node oracle; dynajs-vs-node divergences are explicit DIVERGE entries.
__EXP = null;
// parametric probe generated by tools_agent/gen_param.py
// expectations baked from the node oracle at generation time
__EXP = null;
function mkParent(n) {
    var s = "";
    for (var i = 0; i < n; i++) {
        s += String.fromCodePoint(0x1F600 + (i % 8));
    }
    return s;
}
var parent = mkParent(1200);
var s = parent.slice(0, 1000);
test("at0", function () { assert_eq(String((function(){ return s.at(0); })()), "\ud83d", "at0"); });
test("at-neg", function () { assert_eq(String((function(){ return s.at(-1); })()), "\ude03", "at-neg"); });
test("at-oob", function () { assert_eq(String((function(){ return s.at(1005); })()), "undefined", "at-oob"); });
test("len", function () { assert_eq(String((function(){ return s.length; })()), "1000", "len"); });
summary("sliced_strings");

summary("sliced_strings");
