// converted from console.log/print oracle: expectations baked from the
// node oracle; dynajs-vs-node divergences are explicit DIVERGE entries.
__EXP = null;
// parametric probe generated by tools_agent/gen_param.py
// expectations baked from the node oracle at generation time
__EXP = null;
function mkParent(n) {
    var s = "";
    for (var i = 0; i < n; i++) {
        s += String.fromCodePoint(0x1F600 + (i % 8));
    }
    return s;
}
var parent = mkParent(1200);
var s = parent.slice(0, 64);
test("substring01", function () { assert_eq(String((function(){ return s.substring(0, 1); })()), "\ud83d", "substring01"); });
test("substring-mid", function () { assert_eq(String((function(){ return s.substring(0, 3); })()), "\ud83d\ude00\ud83d", "substring-mid"); });
test("substring-swap", function () { assert_eq(String((function(){ return s.substring(3, 0); })()), "\ud83d\ude00\ud83d", "substring-swap"); });
test("len", function () { assert_eq(String((function(){ return s.length; })()), "64", "len"); });
summary("sliced_strings");

summary("sliced_strings");
