// converted from console.log/print oracle: expectations baked from the
// node oracle; dynajs-vs-node divergences are explicit DIVERGE entries.
__EXP = null;
// parametric probe generated by tools_agent/gen_param.py
// expectations baked from the node oracle at generation time
__EXP = null;
function mkParent(n) {
    var s = "";
    for (var i = 0; i < n; i++) {
        s += String.fromCodePoint(0x1F600 + (i % 8));
    }
    return s;
}
var parent = mkParent(1200);
var s = parent.slice(0, 65);
test("slice01", function () { assert_eq(String((function(){ return s.slice(0, 1); })()), "\ud83d", "slice01"); });
test("slice-neg", function () { assert_eq(String((function(){ return s.slice(-2); })()), "\ude07\ud83d", "slice-neg"); });
test("slice-mid", function () { assert_eq(String((function(){ return s.slice(1, 3); })()), "\ude00\ud83d", "slice-mid"); });
test("slice-len", function () { assert_eq(String((function(){ return s.length; })()), "65", "slice-len"); });
test("len", function () { assert_eq(String((function(){ return s.length; })()), "65", "len"); });
summary("sliced_strings");

summary("sliced_strings");
