// converted from console.log/print oracle: expectations baked from the
// node oracle; dynajs-vs-node divergences are explicit DIVERGE entries.
__EXP = null;
// parametric probe generated by tools_agent/gen_param.py
// expectations baked from the node oracle at generation time
__EXP = null;
function mkParent(n) {
    var s = "";
    for (var i = 0; i < n; i++) {
        s += String.fromCharCode(97 + (i % 26));
    }
    return s;
}
var parent = mkParent(1200);
var s = parent.slice(100, 100 + 1000);
test("idx0", function () { assert_eq(String((function(){ return s[0]; })()), "w", "idx0"); });
test("idxk", function () { assert_eq(String((function(){ return s[3]; })()), "z", "idxk"); });
test("idx-oob", function () { assert_eq(String((function(){ return s[1005]; })()), "undefined", "idx-oob"); });
test("len", function () { assert_eq(String((function(){ return s.length; })()), "1000", "len"); });
summary("sliced_strings");

summary("sliced_strings");
