// converted from console.log/print oracle: expectations baked from the
// node oracle; dynajs-vs-node divergences are explicit DIVERGE entries.
__EXP = null;
// parametric probe generated by tools_agent/gen_param.py
// expectations baked from the node oracle at generation time
__EXP = null;
function mkParent(n) {
    var s = "";
    for (var i = 0; i < n; i++) {
        s += String.fromCharCode(97 + (i % 26));
    }
    return s;
}
var parent = mkParent(1200);
var s = parent.slice(100, 100 + 64);
test("mapkey", function () { assert_eq(String((function(){ return (function(){ var m = new Map(); m.set(s, 7); return m.get(s); })(); })()), "7", "mapkey"); });
test("mapsize", function () { assert_eq(String((function(){ return (function(){ var m2 = new Map(); m2.set(s.slice(0, 1), 1); return m2.size; })(); })()), "1", "mapsize"); });
test("len", function () { assert_eq(String((function(){ return s.length; })()), "64", "len"); });
summary("sliced_strings");

summary("sliced_strings");
