// converted from console.log/print oracle: expectations baked from the
// node oracle; dynajs-vs-node divergences are explicit DIVERGE entries.
__EXP = null;
// parametric probe generated by tools_agent/gen_param.py
// expectations baked from the node oracle at generation time
__EXP = null;
function mkParent(n) {
    var s = "";
    for (var i = 0; i < n; i++) {
        s += String.fromCharCode(97 + (i % 26));
    }
    return s;
}
var parent = mkParent(1200);
var s = parent.slice(100, 100 + 1000);
test("indexOf-head", function () { assert_eq(String((function(){ return s.indexOf(s.charAt(0)); })()), "0", "indexOf-head"); });
test("indexOf-sub", function () { assert_eq(String((function(){ return s.indexOf(s.slice(0, 3)); })()), "0", "indexOf-sub"); });
test("indexOf-miss", function () { assert_eq(String((function(){ return s.indexOf('\u0001'); })()), "-1", "indexOf-miss"); });
test("len", function () { assert_eq(String((function(){ return s.length; })()), "1000", "len"); });
summary("sliced_strings");

summary("sliced_strings");
