// converted from console.log/print oracle: expectations baked from the
// node oracle; dynajs-vs-node divergences are explicit DIVERGE entries.
__EXP = null;
// parametric probe generated by tools_agent/gen_param.py
// expectations baked from the node oracle at generation time
__EXP = null;
function mkParent(n) {
    var s = "";
    for (var i = 0; i < n; i++) {
        s += String.fromCharCode(0x100 + ((i * 7) % 500));
    }
    return s;
}
var parent = mkParent(1200);
var s = parent.slice(100, 100 + 255);
test("at0", function () { assert_eq(String((function(){ return s.at(0); })()), "\u01c8", "at0"); });
test("at-neg", function () { assert_eq(String((function(){ return s.at(-1); })()), "\u02de", "at-neg"); });
test("at-oob", function () { assert_eq(String((function(){ return s.at(260); })()), "undefined", "at-oob"); });
test("len", function () { assert_eq(String((function(){ return s.length; })()), "255", "len"); });
summary("sliced_strings");

summary("sliced_strings");
