// converted from console.log/print oracle: expectations baked from the
// node oracle; dynajs-vs-node divergences are explicit DIVERGE entries.
__EXP = null;
// parametric probe generated by tools_agent/gen_param.py
// expectations baked from the node oracle at generation time
__EXP = null;
function mkParent(n) {
    var s = "";
    for (var i = 0; i < n; i++) {
        s += String.fromCharCode(0x100 + ((i * 7) % 500));
    }
    return s;
}
var parent = mkParent(1200);
var s = parent.slice(100, 100 + 65);
test("idx0", function () { assert_eq(String((function(){ return s[0]; })()), "\u01c8", "idx0"); });
test("idxk", function () { assert_eq(String((function(){ return s[3]; })()), "\u01dd", "idxk"); });
test("idx-oob", function () { assert_eq(String((function(){ return s[70]; })()), "undefined", "idx-oob"); });
test("len", function () { assert_eq(String((function(){ return s.length; })()), "65", "len"); });
summary("sliced_strings");

summary("sliced_strings");
