// converted from console.log/print oracle: expectations baked from the
// node oracle; dynajs-vs-node divergences are explicit DIVERGE entries.
__EXP = null;
// parametric probe generated by tools_agent/gen_param.py
// expectations baked from the node oracle at generation time
__EXP = null;
function mkParent(n) {
    var s = "";
    for (var i = 0; i < n; i++) {
        s += String.fromCharCode(0x100 + ((i * 7) % 500));
    }
    return s;
}
var parent = mkParent(1200);
var s = parent.slice(100, 100 + 127);
test("json", function () { assert_eq(String((function(){ return JSON.stringify(s); })()), "\"\u01c8\u01cf\u01d6\u01dd\u01e4\u01eb\u01f2\u01f9\u0200\u0207\u020e\u0215\u021c\u0223\u022a\u0231\u0238\u023f\u0246\u024d\u0254\u025b\u0262\u0269\u0270\u0277\u027e\u0285\u028c\u0293\u029a\u02a1\u02a8\u02af\u02b6\u02bd\u02c4\u02cb\u02d2\u02d9\u02e0\u02e7\u02ee\u0101\u0108\u010f\u0116\u011d\u0124\u012b\u0132\u0139\u0140\u0147\u014e\u0155\u015c\u0163\u016a\u0171\u0178\u017f\u0186\u018d\u0194\u019b\u01a2\u01a9\u01b0\u01b7\u01be\u01c5\u01cc\u01d3\u01da\u01e1\u01e8\u01ef\u01f6\u01fd\u0204\u020b\u0212\u0219\u0220\u0227\u022e\u0235\u023c\u0243\u024a\u0251\u0258\u025f\u0266\u026d\u0274\u027b\u0282\u0289\u0290\u0297\u029e\u02a5\u02ac\u02b3\u02ba\u02c1\u02c8\u02cf\u02d6\u02dd\u02e4\u02eb\u02f2\u0105\u010c\u0113\u011a\u0121\u0128\u012f\u0136\u013d\u0144\u014b\u0152\"", "json"); });
test("len", function () { assert_eq(String((function(){ return s.length; })()), "127", "len"); });
summary("sliced_strings");

summary("sliced_strings");
