// converted from console.log/print oracle: expectations baked from the
// node oracle; dynajs-vs-node divergences are explicit DIVERGE entries.
__EXP = null;
// parametric probe generated by tools_agent/gen_param.py
// expectations baked from the node oracle at generation time
__EXP = null;
function mkParent(n) {
    var s = "";
    for (var i = 0; i < n; i++) {
        s += String.fromCharCode(0x100 + ((i * 7) % 500));
    }
    return s;
}
var parent = mkParent(1200);
var s = parent.slice(100, 100 + 64);
test("slice01", function () { assert_eq(String((function(){ return s.slice(0, 1); })()), "\u01c8", "slice01"); });
test("slice-neg", function () { assert_eq(String((function(){ return s.slice(-2); })()), "\u0186\u018d", "slice-neg"); });
test("slice-mid", function () { assert_eq(String((function(){ return s.slice(1, 3); })()), "\u01cf\u01d6", "slice-mid"); });
test("slice-len", function () { assert_eq(String((function(){ return s.length; })()), "64", "slice-len"); });
test("len", function () { assert_eq(String((function(){ return s.length; })()), "64", "len"); });
summary("sliced_strings");

summary("sliced_strings");
