// converted from console.log/print oracle: expectations baked from the
// node oracle; dynajs-vs-node divergences are explicit DIVERGE entries.
__EXP = null;
// parametric probe generated by tools_agent/gen_param.py
// expectations baked from the node oracle at generation time
__EXP = null;
function mkParent(n) {
    var s = "";
    for (var i = 0; i < n; i++) {
        s += String.fromCharCode(0x100 + ((i * 7) % 500));
    }
    return s;
}
var parent = mkParent(1200);
var s = parent.slice(100, 100 + 64);
test("template", function () { assert_eq(String((function(){ return `t:${s}`; })()), "t:\u01c8\u01cf\u01d6\u01dd\u01e4\u01eb\u01f2\u01f9\u0200\u0207\u020e\u0215\u021c\u0223\u022a\u0231\u0238\u023f\u0246\u024d\u0254\u025b\u0262\u0269\u0270\u0277\u027e\u0285\u028c\u0293\u029a\u02a1\u02a8\u02af\u02b6\u02bd\u02c4\u02cb\u02d2\u02d9\u02e0\u02e7\u02ee\u0101\u0108\u010f\u0116\u011d\u0124\u012b\u0132\u0139\u0140\u0147\u014e\u0155\u015c\u0163\u016a\u0171\u0178\u017f\u0186\u018d", "template"); });
test("template-len", function () { assert_eq(String((function(){ return `l:${s.length}`; })()), "l:64", "template-len"); });
test("len", function () { assert_eq(String((function(){ return s.length; })()), "64", "len"); });
summary("sliced_strings");

summary("sliced_strings");
