#!/usr/bin/env python3
"""Regenerate src/dyna-charsets.h from the Unicode single-byte mappings.

Committed generator + committed output: the build never reaches the network.
Run after adding a charset, and diff the result -- the gate re-derives and
compares, so a hand-edit of the header shows up as drift.

    python3 tools/gen-charsets.py > src/dyna-charsets.h
"""
import sys

CHARSETS = [
    ("windows-1252", "cp1252"), ("windows-1251", "cp1251"),
    ("windows-1250", "cp1250"), ("windows-1253", "cp1253"),
    ("windows-1254", "cp1254"), ("windows-1255", "cp1255"),
    ("windows-1256", "cp1256"), ("windows-1257", "cp1257"),
    ("windows-1258", "cp1258"),
    ("iso-8859-2", "iso8859_2"), ("iso-8859-3", "iso8859_3"),
    ("iso-8859-4", "iso8859_4"), ("iso-8859-5", "iso8859_5"),
    ("iso-8859-6", "iso8859_6"), ("iso-8859-7", "iso8859_7"),
    ("iso-8859-8", "iso8859_8"), ("iso-8859-9", "iso8859_9"),
    ("iso-8859-10", "iso8859_10"), ("iso-8859-13", "iso8859_13"),
    ("iso-8859-14", "iso8859_14"), ("iso-8859-15", "iso8859_15"),
    ("iso-8859-16", "iso8859_16"),
    ("koi8-r", "koi8_r"), ("koi8-u", "koi8_u"),
    ("macintosh", "mac_roman"), ("ibm866", "cp866"),
]


def main():
    w = sys.stdout.write
    w("/* Generated by tools/gen-charsets.py from the Unicode mappings; do not edit.\n"
      "   High half only: bytes < 0x80 map to themselves in every charset here.\n"
      "   0xFFFF marks a byte the charset does not define. */\n\n")
    names = []
    fwd = {}
    for label, pyname in CHARSETS:
        ident = label.replace("-", "_")
        row = []
        for b in range(0x80, 0x100):
            try:
                cp = ord(bytes([b]).decode(pyname))
                if cp > 0xFFFF:
                    cp = 0xFFFF
            except Exception:
                cp = 0xFFFF
            row.append(cp)
        w("static const uint16_t dyn_cs_%s[128] = {\n" % ident)
        for i in range(0, 128, 8):
            w("    " + ", ".join("0x%04X" % c for c in row[i:i + 8]) + ",\n")
        w("};\n\n")
        fwd[ident] = row
        names.append((label, ident))
    # Reverse maps: (codepoint, byte) sorted by codepoint, bisected at runtime.
    # The forward scan was 128 compares PER CODE POINT; this is 7.
    for label, ident in names:
        row = []
        for b in range(0x80, 0x100):
            cp = fwd[ident][b - 0x80]
            if cp != 0xFFFF:
                row.append((cp, b))
        row.sort()
        w("static const uint16_t dyn_rev_%s[%d][2] = {\n" % (ident, len(row)))
        for i in range(0, len(row), 4):
            w("    " + " ".join("{0x%04X,0x%02X}," % (c, b) for c, b in row[i:i + 4]) + "\n")
        w("};\n\n")
    w("typedef struct { const char *label; const uint16_t *hi;\n"
      "                 const uint16_t (*rev)[2]; unsigned n_rev; } dyn_charset_t;\n\n")
    w("static const dyn_charset_t DYN_CHARSETS[] = {\n")
    for label, ident in names:
        w('    { "%s", dyn_cs_%s, dyn_rev_%s, (unsigned)(sizeof dyn_rev_%s / sizeof dyn_rev_%s[0]) },\n'
              % (label, ident, ident, ident, ident))
    w('    { "iso-8859-1", NULL, NULL, 0 },\n')
    w('    { "us-ascii",   NULL, NULL, 0 },\n')
    w("};\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
