#!/usr/bin/env python3
# Generate the 128-bit cached powers of 10 for the Grisu-style shortest
# fast path in src/dtoa.c. Entry for decimal exponent alpha:
#   f = round(10^alpha * 2^-ec)  with f in [2^127, 2^128),  ec = floor(log2(10^alpha)) - 127
# so that f * 2^ec ~= 10^alpha with relative error <= 2^-128.
import sys
from fractions import Fraction

ALPHA_MIN = -294
ALPHA_MAX = 342

def floor_log2(fr):
    # exact floor(log2(Fraction))
    e2 = round(math_log2(fr))
    while not (Fraction(2) ** e2 <= fr < Fraction(2) ** (e2 + 1)):
        if Fraction(2) ** e2 > fr:
            e2 -= 1
        else:
            e2 += 1
    return e2

def math_log2(fr):
    import math
    return math.log2(fr.numerator) - math.log2(fr.denominator)

def main():
    lines_hi, lines_lo, lines_ec = [], [], []
    for alpha in range(ALPHA_MIN, ALPHA_MAX + 1):
        val = Fraction(10) ** alpha
        e2 = floor_log2(val)
        ec = e2 - 127
        f = round(val * Fraction(2) ** (-ec))
        assert 2 ** 127 <= f < 2 ** 128, (alpha, f.bit_length())
        # verify error bound
        err = abs(val * Fraction(2) ** (-ec) - f)
        assert err <= Fraction(1, 2), (alpha, err)
        lines_hi.append("0x%016XULL" % (f >> 64))
        lines_lo.append("0x%016XULL" % (f & ((1 << 64) - 1)))
        lines_ec.append("%d" % ec)
    n = len(lines_hi)
    out = []
    out.append("/* Generated by tools/gen-dtoa-grisu.py -- do not edit. */")
    out.append("#define GRISU_ALPHA_MIN (%d)" % ALPHA_MIN)
    out.append("#define GRISU_ALPHA_MAX (%d)" % ALPHA_MAX)
    out.append("#define GRISU_ALPHA_COUNT (GRISU_ALPHA_MAX - GRISU_ALPHA_MIN + 1)")
    out.append("")
    out.append("/* Cached powers 10^alpha as 128-bit normalized significands:")
    out.append("   (hi:lo) * 2^ec ~= 10^alpha with |err| <= 2^-128 relative. */")
    out.append("static const uint64_t grisu_pow_hi[GRISU_ALPHA_COUNT] = {")
    for i in range(0, n, 3):
        out.append("    " + ", ".join(lines_hi[i:i+3]) + ",")
    out.append("};")
    out.append("")
    out.append("static const uint64_t grisu_pow_lo[GRISU_ALPHA_COUNT] = {")
    for i in range(0, n, 3):
        out.append("    " + ", ".join(lines_lo[i:i+3]) + ",")
    out.append("};")
    out.append("")
    out.append("static const int32_t grisu_pow_ec[GRISU_ALPHA_COUNT] = {")
    for i in range(0, n, 10):
        out.append("    " + ", ".join(lines_ec[i:i+10]) + ",")
    out.append("};")
    print("\n".join(out))
    # sanity: alpha = 0 -> f = 2^127, ec = -127
    i0 = 0 - ALPHA_MIN
    assert lines_hi[i0] == "0x8000000000000000ULL" and lines_ec[i0] == "-127"

if __name__ == "__main__":
    main()
