#ifndef DYNA_ASYNC_JS_INC_C
#define DYNA_ASYNC_JS_INC_C

static const char dyn_async_js_src[] = "\n"
                                       "(function () {\n"
                                       "    \"use strict\";\n"
                                       "\n"
                                       "    \n"
                                       "    var initError = \"dyna:async is unavailable (initialization failed)\";\n"
                                       "    function stub() { throw new Error(initError); }\n"
                                       "    function stubCtor() { throw new Error(initError); }\n"
                                       "    var STUB = {\n"
                                       "        sleep: stub, withTimeout: stub, retry: stub,\n"
                                       "        Semaphore: stubCtor, Queue: stubCtor, Channel: stubCtor,\n"
                                       "        pmap: stub, Pool: stubCtor, debounce: stub, throttle: stub,\n"
                                       "    };\n"
                                       "    try {\n"
                                       "        \n"
                                       "        if (typeof setTimeout !== \"function\")\n"
                                       "            throw new Error(\"dyna:async requires the global setTimeout\");\n"
                                       "\n"
                                       "        function sleep(ms) {\n"
                                       "            if (typeof ms !== \"number\" || !isFinite(ms) || ms < 0)\n"
                                       "                throw new TypeError(\"sleep: ms must be a non-negative finite number\");\n"
                                       "            return new Promise(function (resolve) { setTimeout(resolve, ms); });\n"
                                       "        }\n"
                                       "\n"
                                       "        \n"
                                       "        function withTimeout(p, ms, reason) {\n"
                                       "            \n"
                                       "            if (!p || typeof p.then !== \"function\")\n"
                                       "                throw new TypeError(\"withTimeout: first argument must be a promise\");\n"
                                       "            if (typeof ms !== \"number\" || !isFinite(ms) || ms < 0)\n"
                                       "                throw new TypeError(\"withTimeout: ms must be a non-negative finite number\");\n"
                                       "            return new Promise(function (resolve, reject) {\n"
                                       "                var settled = false;\n"
                                       "                var t = setTimeout(function () {\n"
                                       "                    if (settled) return;\n"
                                       "                    settled = true;\n"
                                       "                    reject(new Error(typeof reason === \"string\" && reason\n"
                                       "                        ? reason\n"
                                       "                        : \"withTimeout: timed out after \" + ms + \" ms\"));\n"
                                       "                }, ms);\n"
                                       "                p.then(function (v) {\n"
                                       "                    if (settled) return;\n"
                                       "                    settled = true;\n"
                                       "                    clearTimeout(t);\n"
                                       "                    resolve(v);\n"
                                       "                }, function (e) {\n"
                                       "                    if (settled) return;\n"
                                       "                    settled = true;\n"
                                       "                    clearTimeout(t);\n"
                                       "                    reject(e);\n"
                                       "                });\n"
                                       "            });\n"
                                       "        }\n"
                                       "\n"
                                       "        function retry(fn, opts) {\n"
                                       "            if (typeof fn !== \"function\")\n"
                                       "                throw new TypeError(\"retry: fn must be a function\");\n"
                                       "            var retries = 3, backoffMs = 0, factor = 2, onRetry = null;\n"
                                       "            if (opts !== null && opts !== undefined) {\n"
                                       "                if (typeof opts !== \"object\")\n"
                                       "                    throw new TypeError(\"retry: opts must be an object\");\n"
                                       "                if (opts.retries !== undefined && opts.retries !== null) {\n"
                                       "                    if (typeof opts.retries !== \"number\" || !isFinite(opts.retries) || opts.retries < 0 || (opts.retries | 0) !== opts.retries)\n"
                                       "                        throw new TypeError(\"retry: retries must be a non-negative integer\");\n"
                                       "                    retries = opts.retries;\n"
                                       "                }\n"
                                       "                if (opts.backoffMs !== undefined && opts.backoffMs !== null) {\n"
                                       "                    if (typeof opts.backoffMs !== \"number\" || !isFinite(opts.backoffMs) || opts.backoffMs < 0)\n"
                                       "                        throw new TypeError(\"retry: backoffMs must be a non-negative number\");\n"
                                       "                    backoffMs = opts.backoffMs;\n"
                                       "                }\n"
                                       "                if (opts.factor !== undefined && opts.factor !== null) {\n"
                                       "                    if (typeof opts.factor !== \"number\" || !isFinite(opts.factor) || opts.factor < 1)\n"
                                       "                        throw new TypeError(\"retry: factor must be >= 1\");\n"
                                       "                    factor = opts.factor;\n"
                                       "                }\n"
                                       "                if (opts.onRetry !== undefined && opts.onRetry !== null) {\n"
                                       "                    if (typeof opts.onRetry !== \"function\")\n"
                                       "                        throw new TypeError(\"retry: onRetry must be a function\");\n"
                                       "                    onRetry = opts.onRetry;\n"
                                       "                }\n"
                                       "            }\n"
                                       "            return new Promise(function (resolve, reject) {\n"
                                       "                var attempt = 0;\n"
                                       "                var run = function () {\n"
                                       "                    Promise.resolve().then(fn).then(resolve, function (e) {\n"
                                       "                        if (attempt >= retries) { reject(e); return; }\n"
                                       "                        var waitMs = backoffMs * Math.pow(factor, attempt);\n"
                                       "                        attempt += 1;\n"
                                       "                        if (onRetry) {\n"
                                       "                            try { onRetry(e, attempt); } catch (hook) { reject(hook); return; }\n"
                                       "                        }\n"
                                       "                        if (waitMs > 0) setTimeout(run, waitMs);\n"
                                       "                        else Promise.resolve().then(run);\n"
                                       "                    });\n"
                                       "                };\n"
                                       "                run();\n"
                                       "            });\n"
                                       "        }\n"
                                       "\n"
                                       "        \n"
                                       "        function Semaphore(n) {\n"
                                       "            if (typeof n !== \"number\" || !isFinite(n) || (n | 0) !== n || n < 1)\n"
                                       "                throw new TypeError(\"Semaphore: n must be a positive integer\");\n"
                                       "            this._n = n | 0;\n"
                                       "            this._waiters = [];\n"
                                       "        }\n"
                                       "        Semaphore.prototype = {\n"
                                       "            get available() { return this._n; },\n"
                                       "            get waiting() { return this._waiters.length; },\n"
                                       "            acquire() {\n"
                                       "                var self = this;\n"
                                       "                if (this._n > 0) {\n"
                                       "                    this._n -= 1;\n"
                                       "                    return Promise.resolve(function () { self._release(); });\n"
                                       "                }\n"
                                       "                return new Promise(function (resolve) {\n"
                                       "                    self._waiters.push(resolve);\n"
                                       "                });\n"
                                       "            },\n"
                                       "            _release() {\n"
                                       "                var next = this._waiters.shift();\n"
                                       "                if (next !== undefined) {\n"
                                       "                    \n"
                                       "                    next(function () { this._release(); }.bind(this));\n"
                                       "                    return;\n"
                                       "                }\n"
                                       "                this._n += 1;\n"
                                       "            },\n"
                                       "            run(fn) {\n"
                                       "                var self = this;\n"
                                       "                var args = Array.prototype.slice.call(arguments, 1);\n"
                                       "                if (typeof fn !== \"function\")\n"
                                       "                    return Promise.reject(new TypeError(\"Semaphore.run: fn must be a function\"));\n"
                                       "                return this.acquire().then(function (release) {\n"
                                       "                    var p;\n"
                                       "                    try { p = fn.apply(null, args); }\n"
                                       "                    catch (e) { release(); return Promise.reject(e); }\n"
                                       "                    return Promise.resolve(p).then(\n"
                                       "                        function (v) { release(); return v; },\n"
                                       "                        function (e) { release(); throw e; });\n"
                                       "                });\n"
                                       "            },\n"
                                       "        };\n"
                                       "\n"
                                       "        \n"
                                       "        function Queue(cap) {\n"
                                       "            if (cap === undefined || cap === null) cap = Infinity;\n"
                                       "            \n"
                                       "            if (typeof cap !== \"number\" || !isFinite(cap) && cap !== Infinity)\n"
                                       "                throw new TypeError(\"Queue: cap must be a positive number\");\n"
                                       "            if (cap !== Infinity && ((cap | 0) !== cap || cap < 1))\n"
                                       "                throw new RangeError(\"Queue: cap must be a positive integer\");\n"
                                       "            this._cap = cap;\n"
                                       "            this._q = [];\n"
                                       "            this._closed = false;\n"
                                       "        }\n"
                                       "        Queue.prototype = {\n"
                                       "            get length() { return this._q.length; },\n"
                                       "            get closed() { return this._closed; },\n"
                                       "            push(v) {\n"
                                       "                if (this._closed) throw new TypeError(\"Queue: closed\");\n"
                                       "                if (this._q.length >= this._cap) throw new RangeError(\"Queue: full (cap \" + this._cap + \")\");\n"
                                       "                this._q.push(v);\n"
                                       "                return this;\n"
                                       "            },\n"
                                       "            tryPush(v) {\n"
                                       "                if (this._closed || this._q.length >= this._cap) return false;\n"
                                       "                this._q.push(v);\n"
                                       "                return true;\n"
                                       "            },\n"
                                       "            \n"
                                       "            shift() { return this._q.shift(); },\n"
                                       "            close() { this._closed = true; },\n"
                                       "        };\n"
                                       "\n"
                                       "        \n"
                                       "        function Channel(cap) {\n"
                                       "            if (cap === undefined || cap === null) cap = Infinity;\n"
                                       "            \n"
                                       "            if (typeof cap !== \"number\" || !isFinite(cap) && cap !== Infinity)\n"
                                       "                throw new TypeError(\"Channel: cap must be a positive number\");\n"
                                       "            if (cap !== Infinity && ((cap | 0) !== cap || cap < 1))\n"
                                       "                throw new RangeError(\"Channel: cap must be a positive integer\");\n"
                                       "            this._cap = cap;\n"
                                       "            this._q = [];\n"
                                       "            this._blocked = [];     \n"
                                       "            this._receiver = null;  \n"
                                       "            this._closed = false;\n"
                                       "        }\n"
                                       "        Channel.prototype = {\n"
                                       "            get length() { return this._q.length; },\n"
                                       "            get closed() { return this._closed; },\n"
                                       "            send(v) {\n"
                                       "                var self = this;\n"
                                       "                if (this._closed)\n"
                                       "                    return Promise.reject(new TypeError(\"Channel: send on a closed channel\"));\n"
                                       "                if (this._receiver !== null) {\n"
                                       "                    var r = this._receiver;\n"
                                       "                    this._receiver = null;\n"
                                       "                    r.resolve({ value: v, done: false });\n"
                                       "                    return Promise.resolve();\n"
                                       "                }\n"
                                       "                if (this._q.length < this._cap) {\n"
                                       "                    this._q.push(v);\n"
                                       "                    return Promise.resolve();\n"
                                       "                }\n"
                                       "                return new Promise(function (resolve, reject) {\n"
                                       "                    self._blocked.push({ resolve: resolve, reject: reject, v: v });\n"
                                       "                });\n"
                                       "            },\n"
                                       "            recv() {\n"
                                       "                var self = this;\n"
                                       "                if (this._receiver !== null)\n"
                                       "                    return Promise.reject(new TypeError(\"Channel: a recv() is already pending (single consumer)\"));\n"
                                       "                if (this._q.length > 0) {\n"
                                       "                    var v = this._q.shift();\n"
                                       "                    this._admit();\n"
                                       "                    return Promise.resolve({ value: v, done: false });\n"
                                       "                }\n"
                                       "                if (this._closed)\n"
                                       "                    return Promise.resolve({ done: true });\n"
                                       "                return new Promise(function (resolve, reject) {\n"
                                       "                    self._receiver = { resolve: resolve, reject: reject };\n"
                                       "                });\n"
                                       "            },\n"
                                       "            close() {\n"
                                       "                this._closed = true;\n"
                                       "                var r = this._receiver;\n"
                                       "                this._receiver = null;\n"
                                       "                if (r !== null) r.resolve({ done: true });\n"
                                       "                var blocked = this._blocked;\n"
                                       "                this._blocked = [];\n"
                                       "                for (var i = 0; i < blocked.length; i++)\n"
                                       "                    blocked[i].reject(new TypeError(\"Channel: closed while a send was waiting for room\"));\n"
                                       "            },\n"
                                       "            _admit() {\n"
                                       "                while (this._q.length < this._cap && this._blocked.length > 0) {\n"
                                       "                    var s = this._blocked.shift();\n"
                                       "                    this._q.push(s.v);\n"
                                       "                    s.resolve();\n"
                                       "                }\n"
                                       "            },\n"
                                       "            [Symbol.asyncIterator]() {\n"
                                       "                var self = this;\n"
                                       "                return { next: function () { return self.recv(); } };\n"
                                       "            },\n"
                                       "        };\n"
                                       "\n"
                                       "        \n"
                                       "        function pmap(items, fn, opts) {\n"
                                       "            \n"
                                       "            if (!Array.isArray(items))\n"
                                       "                throw new TypeError(\"pmap: items must be an array\");\n"
                                       "            if (typeof fn !== \"function\")\n"
                                       "                throw new TypeError(\"pmap: fn must be a function\");\n"
                                       "            var concurrency = 8;\n"
                                       "            if (opts !== null && opts !== undefined) {\n"
                                       "                if (typeof opts !== \"object\")\n"
                                       "                    throw new TypeError(\"pmap: opts must be an object\");\n"
                                       "                if (opts.concurrency !== undefined && opts.concurrency !== null) {\n"
                                       "                    if (typeof opts.concurrency !== \"number\" || !isFinite(opts.concurrency)\n"
                                       "                        || (opts.concurrency | 0) !== opts.concurrency || opts.concurrency < 1)\n"
                                       "                        throw new TypeError(\"pmap: concurrency must be a positive integer\");\n"
                                       "                    concurrency = opts.concurrency | 0;\n"
                                       "                }\n"
                                       "            }\n"
                                       "            var n = items.length;\n"
                                       "            return new Promise(function (resolve, reject) {\n"
                                       "                if (n === 0) { resolve([]); return; }\n"
                                       "                var results = new Array(n);\n"
                                       "                var next = 0, inFlight = 0, settledCount = 0, failed = false;\n"
                                       "                var launch = function () {\n"
                                       "                    while (!failed && inFlight < concurrency && next < n) {\n"
                                       "                        (function (i) {\n"
                                       "                            inFlight += 1;\n"
                                       "                            Promise.resolve().then(function () { return fn(items[i], i, items); })\n"
                                       "                                .then(function (v) {\n"
                                       "                                    inFlight -= 1;\n"
                                       "                                    if (failed) return;         \n"
                                       "                                    results[i] = v;\n"
                                       "                                    settledCount += 1;\n"
                                       "                                    if (settledCount === n) resolve(results);\n"
                                       "                                    else launch();\n"
                                       "                                }, function (e) {\n"
                                       "                                    inFlight -= 1;\n"
                                       "                                    if (failed) return;         \n"
                                       "                                    failed = true;\n"
                                       "                                    reject(e);\n"
                                       "                                });\n"
                                       "                        })(next);\n"
                                       "                        next += 1;\n"
                                       "                    }\n"
                                       "                };\n"
                                       "                launch();\n"
                                       "            });\n"
                                       "        }\n"
                                       "\n"
                                       "        \n"
                                       "        function Pool(n) {\n"
                                       "            if (typeof n !== \"number\" || !isFinite(n) || (n | 0) !== n || n < 1)\n"
                                       "                throw new TypeError(\"Pool: n must be a positive integer\");\n"
                                       "            this._n = n | 0;\n"
                                       "            this._active = 0;\n"
                                       "            this._q = [];\n"
                                       "        }\n"
                                       "        Pool.prototype = {\n"
                                       "            get size() { return this._n; },\n"
                                       "            get active() { return this._active; },\n"
                                       "            get pending() { return this._q.length; },\n"
                                       "            submit(fn) {\n"
                                       "                var self = this;\n"
                                       "                if (typeof fn !== \"function\")\n"
                                       "                    throw new TypeError(\"Pool.submit: fn must be a function\");\n"
                                       "                return new Promise(function (resolve, reject) {\n"
                                       "                    self._q.push({ fn: fn, resolve: resolve, reject: reject });\n"
                                       "                    self._pump();\n"
                                       "                });\n"
                                       "            },\n"
                                       "            _pump() {\n"
                                       "                var self = this;\n"
                                       "                while (this._active < this._n && this._q.length > 0) {\n"
                                       "                    var job = this._q.shift();\n"
                                       "                    this._active += 1;\n"
                                       "                    Promise.resolve().then(function () { return job.fn(); })\n"
                                       "                        .then(function (v) {\n"
                                       "                            self._active -= 1;\n"
                                       "                            job.resolve(v);\n"
                                       "                            self._pump();\n"
                                       "                        }, function (e) {\n"
                                       "                            self._active -= 1;\n"
                                       "                            job.reject(e);\n"
                                       "                            self._pump();\n"
                                       "                        });\n"
                                       "                }\n"
                                       "            },\n"
                                       "        };\n"
                                       "\n"
                                       "        \n"
                                       "        function debounce(fn, ms) {\n"
                                       "            if (typeof fn !== \"function\")\n"
                                       "                throw new TypeError(\"debounce: fn must be a function\");\n"
                                       "            if (typeof ms !== \"number\" || !isFinite(ms) || ms < 0)\n"
                                       "                throw new TypeError(\"debounce: ms must be a non-negative finite number\");\n"
                                       "            var t = null;\n"
                                       "            var wrapped = function () {\n"
                                       "                var self = this, args = arguments;\n"
                                       "                if (t !== null) clearTimeout(t);\n"
                                       "                t = setTimeout(function () { t = null; fn.apply(self, args); }, ms);\n"
                                       "            };\n"
                                       "            wrapped.cancel = function () {\n"
                                       "                if (t !== null) { clearTimeout(t); t = null; }\n"
                                       "            };\n"
                                       "            wrapped.pending = function () { return t !== null; };\n"
                                       "            return wrapped;\n"
                                       "        }\n"
                                       "\n"
                                       "        \n"
                                       "        function throttle(fn, ms) {\n"
                                       "            if (typeof fn !== \"function\")\n"
                                       "                throw new TypeError(\"throttle: fn must be a function\");\n"
                                       "            if (typeof ms !== \"number\" || !isFinite(ms) || ms < 0)\n"
                                       "                throw new TypeError(\"throttle: ms must be a non-negative finite number\");\n"
                                       "            var last = -Infinity, t = null;\n"
                                       "            var wrapped = function () {\n"
                                       "                var self = this, args = arguments;\n"
                                       "                var now = Date.now();\n"
                                       "                var remain = ms - (now - last);\n"
                                       "                if (remain <= 0) {\n"
                                       "                    last = now;\n"
                                       "                    fn.apply(self, args);\n"
                                       "                    return;\n"
                                       "                }\n"
                                       "                if (t !== null) clearTimeout(t);\n"
                                       "                t = setTimeout(function () {\n"
                                       "                    t = null;\n"
                                       "                    last = Date.now();\n"
                                       "                    fn.apply(self, args);\n"
                                       "                }, remain);\n"
                                       "            };\n"
                                       "            wrapped.cancel = function () {\n"
                                       "                if (t !== null) { clearTimeout(t); t = null; }\n"
                                       "            };\n"
                                       "            wrapped.pending = function () { return t !== null; };\n"
                                       "            return wrapped;\n"
                                       "        }\n"
                                       "\n"
                                       "        return {\n"
                                       "            sleep: sleep, withTimeout: withTimeout, retry: retry,\n"
                                       "            Semaphore: Semaphore, Queue: Queue, Channel: Channel,\n"
                                       "            pmap: pmap, Pool: Pool, debounce: debounce, throttle: throttle,\n"
                                       "        };\n"
                                       "    } catch (initFailure) {\n"
                                       "        initError = \"dyna:async failed to initialize: \" + (\n"
                                       "            initFailure && initFailure.message ? initFailure.message : initFailure);\n"
                                       "        return STUB;\n"
                                       "    }\n"
                                       "})();\n"
                                       "\n";

#endif
