/* dyna-fetch.inc.c -- WHATWG Fetch API subset for DynaJS (plan row 1, 3.1)
 *
 * Implements:
 *   - globalThis.Headers
 *   - globalThis.FormData
 *   - globalThis.AbortSignal
 *   - globalThis.AbortController
 *   - globalThis.Request
 *   - globalThis.Response
 *   - globalThis.fetch
 *
 * Backed by DynaJS HTTPClient (dyna:net) and MultipartFormat/Parse.
 */

#ifndef DYNA_FETCH_INC_C
#define DYNA_FETCH_INC_C

static const char dyn_fetch_js_src[] =
"(function() {\n"
"    class Headers {\n"
"        #map = new Map();\n"
"        constructor(init) {\n"
"            if (init) {\n"
"                if (init instanceof Headers) {\n"
"                    for (const [k, v] of init) this.append(k, v);\n"
"                } else if (Array.isArray(init)) {\n"
"                    for (const [k, v] of init) this.append(k, v);\n"
"                } else if (typeof init === 'object') {\n"
"                    for (const k of Object.keys(init)) this.append(k, init[k]);\n"
"                }\n"
"            }\n"
"        }\n"
"        append(name, value) {\n"
"            name = String(name).toLowerCase();\n"
"            value = String(value).trim();\n"
"            if (this.#map.has(name)) this.#map.set(name, this.#map.get(name) + ', ' + value);\n"
"            else this.#map.set(name, value);\n"
"        }\n"
"        delete(name) { this.#map.delete(String(name).toLowerCase()); }\n"
"        get(name) { return this.#map.get(String(name).toLowerCase()) ?? null; }\n"
"        has(name) { return this.#map.has(String(name).toLowerCase()); }\n"
"        set(name, value) { this.#map.set(String(name).toLowerCase(), String(value).trim()); }\n"
"        forEach(cb, thisArg) { for (const [k, v] of this.#map) cb.call(thisArg, v, k, this); }\n"
"        *keys() { yield* this.#map.keys(); }\n"
"        *values() { yield* this.#map.values(); }\n"
"        *entries() { yield* this.#map.entries(); }\n"
"        [Symbol.iterator]() { return this.entries(); }\n"
"    }\n"
"\n"
"    class FormData {\n"
"        #entries = [];\n"
"        append(name, value, filename) { this.#entries.push([String(name), value, filename]); }\n"
"        delete(name) { name = String(name); this.#entries = this.#entries.filter(e => e[0] !== name); }\n"
"        get(name) { name = String(name); const e = this.#entries.find(x => x[0] === name); return e ? e[1] : null; }\n"
"        getAll(name) { name = String(name); return this.#entries.filter(x => x[0] === name).map(x => x[1]); }\n"
"        has(name) { name = String(name); return this.#entries.some(x => x[0] === name); }\n"
"        set(name, value, filename) {\n"
"            name = String(name);\n"
"            let rep = false;\n"
"            this.#entries = this.#entries.map(e => {\n"
"                if (e[0] === name) { if (!rep) { rep = true; return [name, value, filename]; } return null; }\n"
"                return e;\n"
"            }).filter(Boolean);\n"
"            if (!rep) this.#entries.push([name, value, filename]);\n"
"        }\n"
"        forEach(cb, thisArg) { for (const [k, v] of this.#entries) cb.call(thisArg, v, k, this); }\n"
"        *keys() { for (const [k] of this.#entries) yield k; }\n"
"        *values() { for (const [, v] of this.#entries) yield v; }\n"
"        *entries() { for (const [k, v] of this.#entries) yield [k, v]; }\n"
"        [Symbol.iterator]() { return this.entries(); }\n"
"    }\n"
"\n"
"    class AbortSignal {\n"
"        #aborted = false;\n"
"        #reason = undefined;\n"
"        #listeners = [];\n"
"        get aborted() { return this.#aborted; }\n"
"        get reason() { return this.#reason; }\n"
"        get onabort() { return this._onabort; }\n"
"        set onabort(fn) { this._onabort = fn; }\n"
"        addEventListener(type, listener) {\n"
"            if (type === 'abort' && typeof listener === 'function') {\n"
"                if (this.#aborted) queueMicrotask(() => listener.call(this, { type: 'abort', target: this }));\n"
"                else this.#listeners.push(listener);\n"
"            }\n"
"        }\n"
"        removeEventListener(type, listener) {\n"
"            if (type === 'abort') this.#listeners = this.#listeners.filter(l => l !== listener);\n"
"        }\n"
"        throwIfAborted() { if (this.#aborted) throw this.#reason; }\n"
"        _abort(reason) {\n"
"            if (this.#aborted) return;\n"
"            this.#aborted = true;\n"
"            this.#reason = reason !== undefined ? reason : new Error('This operation was aborted');\n"
"            const evt = { type: 'abort', target: this };\n"
"            if (typeof this._onabort === 'function') {\n"
"                try { this._onabort.call(this, evt); } catch (e) { queueMicrotask(() => { throw e; }); }\n"
"            }\n"
"            for (const l of this.#listeners) {\n"
"                try { l.call(this, evt); } catch (e) { queueMicrotask(() => { throw e; }); }\n"
"            }\n"
"        }\n"
"        static abort(reason = undefined) {\n"
"            const s = new AbortSignal();\n"
"            s._abort(reason);\n"
"            return s;\n"
"        }\n"
"        static timeout(delayMs) {\n"
"            const c = new AbortController();\n"
"            const t = setTimeout(() => c.abort(new Error('The operation timed out')), delayMs);\n"
"            c.signal.addEventListener('abort', () => clearTimeout(t));\n"
"            /* fetch() clears the timer on settle: without this, every short\n"
"               fetch with a long timeout leaves an OS timer + controller alive */\n"
"            c.signal._cancelTimeout = () => clearTimeout(t);\n"
"            return c.signal;\n"
"        }\n"
"    }\n"
"\n"
"    class AbortController {\n"
"        #signal = new AbortSignal();\n"
"        get signal() { return this.#signal; }\n"
"        abort(reason) { this.#signal._abort(reason); }\n"
"    }\n"
"\n"
"    class Response {\n"
"        #status; #statusText; #headers; #body; #bodyUsed = false; #url = '';\n"
"        constructor(body = null, init = {}) {\n"
"            this.#status = init.status ?? 200;\n"
"            this.#statusText = init.statusText ?? '';\n"
"            this.#headers = init.headers instanceof Headers ? init.headers : new Headers(init.headers);\n"
"            this.#url = init.url ?? '';\n"
"            this.#body = body;\n"
"        }\n"
"        get status() { return this.#status; }\n"
"        get statusText() { return this.#statusText; }\n"
"        get ok() { return this.#status >= 200 && this.#status < 300; }\n"
"        get headers() { return this.#headers; }\n"
"        get url() { return this.#url; }\n"
"        get bodyUsed() { return this.#bodyUsed; }\n"
"        #consume() {\n"
"            if (this.#bodyUsed) throw new TypeError('Body has already been consumed');\n"
"            this.#bodyUsed = true;\n"
"            return this.#body;\n"
"        }\n"
"        async text() {\n"
"            const b = this.#consume();\n"
"            if (b === null || b === undefined) return '';\n"
"            if (typeof b === 'string') return b;\n"
"            if (b instanceof Uint8Array || b instanceof ArrayBuffer) return new TextDecoder().decode(b);\n"
"            return String(b);\n"
"        }\n"
"        async json() { return JSON.parse(await this.text()); }\n"
"        async bytes() {\n"
"            const b = this.#consume();\n"
"            if (b === null || b === undefined) return new Uint8Array(0);\n"
"            /* COPIES, not aliases: two clones of one Response must not\n"
"               share a mutable body (WHATWG tee) */\n"
"            if (b instanceof Uint8Array) return b.slice();\n"
"            if (b instanceof ArrayBuffer) return new Uint8Array(b.slice(0));\n"
"            if (typeof b === 'string') return new TextEncoder().encode(b);\n"
"            return new TextEncoder().encode(String(b));\n"
"        }\n"
"        async arrayBuffer() {\n"
"            const u8 = await this.bytes();\n"
"            return u8.buffer.slice(u8.byteOffset, u8.byteOffset + u8.byteLength);\n"
"        }\n"
"        clone() {\n"
"            if (this.#bodyUsed) throw new TypeError('Cannot clone a consumed response');\n"
"            let body = this.#body;\n"
"            /* copy-on-clone: strings/null are immutable and stay shared */\n"
"            if (body instanceof Uint8Array) body = body.slice();\n"
"            else if (body instanceof ArrayBuffer) body = body.slice(0);\n"
"            return new Response(body, {\n"
"                status: this.#status, statusText: this.#statusText,\n"
"                headers: new Headers(this.#headers), url: this.#url\n"
"            });\n"
"        }\n"
"    }\n"
"\n"
"    class Request {\n"
"        #method; #url; #headers; #body; #signal;\n"
"        constructor(input, init = {}) {\n"
"            if (input instanceof Request) {\n"
"                this.#url = input.url;\n"
"                this.#method = init.method ?? input.method;\n"
"                this.#headers = new Headers(init.headers ?? input.headers);\n"
"                this.#body = init.body ?? input.#body;\n"
"                this.#signal = init.signal ?? input.#signal;\n"
"            } else {\n"
"                this.#url = String(input);\n"
"                this.#method = (init.method ?? 'GET').toUpperCase();\n"
"                this.#headers = new Headers(init.headers);\n"
"                this.#body = init.body ?? null;\n"
"                this.#signal = init.signal ?? null;\n"
"            }\n"
"        }\n"
"        get method() { return this.#method; }\n"
"        get url() { return this.#url; }\n"
"        get headers() { return this.#headers; }\n"
"        get signal() { return this.#signal; }\n"
"        get body() { return this.#body; }\n"
"        async text() {\n"
"            if (this.#body === null || this.#body === undefined) return '';\n"
"            if (typeof this.#body === 'string') return this.#body;\n"
"            if (this.#body instanceof Uint8Array || this.#body instanceof ArrayBuffer) return new TextDecoder().decode(this.#body);\n"
"            return String(this.#body);\n"
"        }\n"
"        async json() { return JSON.parse(await this.text()); }\n"
"        async bytes() {\n"
"            if (this.#body === null || this.#body === undefined) return new Uint8Array(0);\n"
"            if (this.#body instanceof Uint8Array) return this.#body.slice();\n"
"            if (this.#body instanceof ArrayBuffer) return new Uint8Array(this.#body.slice(0));\n"
"            return new TextEncoder().encode(String(this.#body));\n"
"        }\n"
"        async arrayBuffer() {\n"
"            const u8 = await this.bytes();\n"
"            return u8.buffer.slice(u8.byteOffset, u8.byteOffset + u8.byteLength);\n"
"        }\n"
"    }\n"
"\n"
"    async function fetch(input, init = {}) {\n"
"        const req = new Request(input, init);\n"
"        const signal = req.signal;\n"
"        if (signal && signal.aborted) throw signal.reason;\n"
"\n"
"        let headersObj = {};\n"
"        for (const [k, v] of req.headers) headersObj[k] = v;\n"
"\n"
"        let body = undefined;\n"
"        if (req.method !== 'GET' && req.method !== 'HEAD') {\n"
"            const b = req.body;\n"
"            if (b instanceof FormData) {\n"
"                const { MultipartFormat } = await import('dyna:net');\n"
"                const parts = [];\n"
"                for (const [name, val, filename] of b.entries()) {\n"
"                    if (val instanceof Uint8Array || val instanceof ArrayBuffer) {\n"
"                        parts.push({ name, body: val, filename: filename || undefined });\n"
"                    } else {\n"
"                        parts.push({ name, value: String(val), filename: filename || undefined });\n"
"                    }\n"
"                }\n"
"                const fmt = MultipartFormat(parts);\n"
"                body = fmt.body;\n"
"                headersObj['content-type'] = fmt.contentType;\n"
"            } else if (b !== null && b !== undefined) {\n"
"                body = typeof b === 'string' ? b :\n"
"                    (b instanceof Uint8Array || b instanceof ArrayBuffer\n"
"                     || b instanceof DataView ? b : await req.text());\n"
"            }\n"
"        }\n"
"\n"
"        const { HTTPClient } = await import('dyna:net');\n"
"        const client = new HTTPClient();\n"
"        if (init.timeout) client.setTimeout(init.timeout);\n"
"\n"
"        let abortListener;\n"
"        let reqPromise = client.requestAsync(req.method, req.url, body, headersObj);\n"
"\n"
"        if (signal) {\n"
"            const abortPromise = new Promise((_, reject) => {\n"
"                abortListener = () => {\n"
"                    try { client.disconnect(); } catch (e) {}\n"
"                    reject(signal.reason);\n"
"                };\n"
"                signal.addEventListener('abort', abortListener);\n"
"            });\n"
"            try {\n"
"                const raw = await Promise.race([reqPromise, abortPromise]);\n"
"                if (signal._cancelTimeout) try { signal._cancelTimeout(); } catch (e) {}\n"
"                /* bodyBytes is the EXACT response octets; the string body rode\n"
"                   a lossy UTF-8 conversion and cannot carry binary. text()\n"
"                   decodes on demand (WHATWG replacement), bytes()/arrayBuffer()\n"
"                   hand the exact bytes back. */\n"
"                return new Response(raw.bodyBytes ?? raw.body, {\n"
"                    status: raw.status, statusText: raw.statusText,\n"
"                    headers: new Headers(raw.headers), url: req.url\n"
"                });\n"
"            } finally {\n"
"                if (signal._cancelTimeout) try { signal._cancelTimeout(); } catch (e) {}\n"
"                if (abortListener) signal.removeEventListener('abort', abortListener);\n"
"            }\n"
"        } else {\n"
"            const raw = await reqPromise;\n"
"            /* bytes-native body: see the abort-path comment above */\n"
"            return new Response(raw.bodyBytes ?? raw.body, {\n"
"                status: raw.status, statusText: raw.statusText,\n"
"                headers: new Headers(raw.headers), url: req.url\n"
"            });\n"
"        }\n"
"    }\n"
"\n"
"    var _g = typeof globalThis !== 'undefined' ? globalThis : (typeof window !== 'undefined' ? window : this);\n"
"    _g.Headers = Headers;\n"
"    _g.FormData = FormData;\n"
"    _g.AbortSignal = AbortSignal;\n"
"    _g.AbortController = AbortController;\n"
"    _g.Response = Response;\n"
"    _g.Request = Request;\n"
"    _g.fetch = fetch;\n"
"})();\n";

static void js_fetch_install(JSContext *ctx, JSValueConst global_obj)
{
    JSValue ret = JS_Eval(ctx, dyn_fetch_js_src, strlen(dyn_fetch_js_src),
                          "<fetch>", JS_EVAL_TYPE_GLOBAL);
    if (JS_IsException(ret)) {
        JSValue err = JS_GetException(ctx);
        JS_FreeValue(ctx, err);
    } else {
        JS_FreeValue(ctx, ret);
    }
}

#endif /* DYNA_FETCH_INC_C */
