// parametric probe generated by tools_agent/gen_waveb.py
// expectations baked from the node oracle at generation time
__EXP = null;

var tdz = "no";
function early() { return M.S; }
try { tdz = String(early()); } catch (e) { tdz = (e && e.constructor && e.constructor.name) || "unknown"; }
const M = Object.freeze({ S: "hello" });

test("tdz", function () { assert_eq(String((function(){ return tdz; })()), "ReferenceError", "tdz"); });
test("after", function () { assert_eq(String((function(){ return M.S; })()), "hello", "after"); });
summary("constprop_waveB");
