// parametric probe generated by tools_agent/gen_waveb.py
// expectations baked from the node oracle at generation time
__EXP = null;
const M = Object.freeze({ S: "go", T: true, I: 42 });
function ds(x) {
    switch (x) {
        case M.S: return "s";
        case M.I: return 1;
        default: return "d";
    }
}
function ds2(x) {
    switch (x) {
        case M.S: return "s";
        case "no": return "n";
        default: return "d2";
    }
}

test("hit_str", function () { assert_eq(String((function(){ return ds(M.S); })()), "s", "hit_str"); });
test("hit_int", function () { assert_eq(String((function(){ return ds(M.I); })()), "1", "hit_int"); });
test("miss", function () { assert_eq(String((function(){ return ds(0); })()), "d", "miss"); });
test("str2", function () { assert_eq(String((function(){ return ds2(M.S); })()), "s", "str2"); });
test("miss2", function () { assert_eq(String((function(){ return ds2(1); })()), "d2", "miss2"); });
summary("constprop_waveB");
