// parametric probe generated by tools_agent/gen_waveb.py
// expectations baked from the node oracle at generation time
__EXP = null;
const M = Object.freeze({ S: "hello" });
const g = function M() { return typeof M; };

test("fnexpr", function () { assert_eq(String((function(){ return g() === "function" && M.S; })()), "hello", "fnexpr"); });
test("top", function () { assert_eq(String((function(){ return M.S; })()), "hello", "top"); });
summary("constprop_waveB");
