// parametric probe generated by tools_agent/gen_waveb.py
// expectations baked from the node oracle at generation time
__EXP = null;
const M = Object.freeze({ C: "7", D: "00" });
test("bracket0", function () { assert_eq(String((function(){ return M["C"]; })()), "7", "bracket0"); });
test("bracket1", function () { assert_eq(String((function(){ return M.C; })()), "7", "bracket1"); });
test("bracket2", function () { assert_eq(String((function(){ return M[7]; })()), "undefined", "bracket2"); });
test("bracket3", function () { assert_eq(String((function(){ return M["D"]; })()), "00", "bracket3"); });
test("bracket4", function () { assert_eq(String((function(){ return M.D; })()), "00", "bracket4"); });
test("id", function () { assert_eq(String((function(){ return 1; })()), "1", "id"); });
summary("constprop_waveB");
