// parametric probe generated by tools_agent/gen_waveb.py
// expectations baked from the node oracle at generation time
__EXP = null;
const M = Object.freeze({ S: "hello", I: 42 });
try { M["dyn" + 1] = 1; } catch (e) {}

test("post", function () { assert_eq(String((function(){ return M.S; })()), "hello", "post"); });
test("postI", function () { assert_eq(String((function(){ return M.I; })()), "42", "postI"); });
test("still", function () { assert_eq(String((function(){ return typeof M; })()), "object", "still"); });
summary("constprop_waveB");
