// parametric probe generated by tools_agent/gen_waveb.py
// expectations baked from the node oracle at generation time
__EXP = null;
const M = Object.freeze({ S: "hello", W: "\u00e9\u4e2d", C: "7", T: true, F: false, N: null, I: 42 });
test("stmt0", function () { assert_eq(String((function(){ return M.S; })()), "hello", "stmt0"); });
test("stmt1", function () { assert_eq(String((function(){ return M.W; })()), "\u00e9\u4e2d", "stmt1"); });
test("stmt2", function () { assert_eq(String((function(){ return M.C; })()), "7", "stmt2"); });
test("stmt3", function () { assert_eq(String((function(){ return M.T; })()), "true", "stmt3"); });
test("stmt4", function () { assert_eq(String((function(){ return M.F; })()), "false", "stmt4"); });
test("stmt5", function () { assert_eq(String((function(){ return M.N; })()), "null", "stmt5"); });
test("stmt6", function () { assert_eq(String((function(){ return M.I; })()), "42", "stmt6"); });
test("typeof", function () { assert_eq(String((function(){ return typeof M.S + typeof M.T + typeof M.N; })()), "stringbooleanobject", "typeof"); });
summary("constprop_waveB");
