// parametric probe generated by tools_agent/gen_waveb.py
// expectations baked from the node oracle at generation time
__EXP = null;
const M = Object.freeze({ S: "hello", W: "\u00e9\u4e2d", C: "7", T: true, F: false, N: null, I: 42 });
test("eq0", function () { assert_eq(String((function(){ return (M.I === M.I); })()), "true", "eq0"); });
test("typeof", function () { assert_eq(String((function(){ return typeof M.S + typeof M.T + typeof M.N; })()), "stringbooleanobject", "typeof"); });
summary("constprop_waveB");
