// parametric probe generated by tools_agent/gen_waveb.py
// expectations baked from the node oracle at generation time
__EXP = null;
const M = Object.freeze({ W: "\u00e9\u4e2d" });
test("arg0", function () { assert_eq(String((function(){ return [1, M.W][1]; })()), "\u00e9\u4e2d", "arg0"); });
test("id", function () { assert_eq(String((function(){ return 1; })()), "1", "id"); });
summary("constprop_waveB");
