// parametric probe generated by tools_agent/gen_waveb.py
// expectations baked from the node oracle at generation time
__EXP = null;
function f() { with ({}) { } const M = Object.freeze({ A: 4 }); return M.A; }

test("f", function () { assert_eq(String((function(){ return f(); })()), "4", "f"); });
summary("constprop_waveB");
