// parametric probe generated by tools_agent/gen_waveb.py
// expectations baked from the node oracle at generation time
__EXP = null;
function f() { { const M = Object.freeze({ A: 5 }); return M.A; } }

test("f", function () { assert_eq(String((function(){ return f(); })()), "5", "f"); });
summary("constprop_waveB");
