// parametric probe generated by tools_agent/gen_waveb.py
// expectations baked from the node oracle at generation time
__EXP = null;
function* g() { const M = Object.freeze({ A: 6 }); yield M.A; }
var it = g();

test("v", function () { assert_eq(String((function(){ return it.next().value; })()), "6", "v"); });
summary("constprop_waveB");
