// parametric probe generated by tools_agent/gen_waveb.py
// expectations baked from the node oracle at generation time
__EXP = null;
function ds(x) {
    const OP = Object.freeze({ K0: 1, K1: 7, K2: 13 });
    switch (x) {
        case OP.K0: return "a";
        case OP.K1: return "b";
        case OP.K2: return "c";
        default: return "d";
    }
}

test("h0", function () { assert_eq(String((function(){ return ds(1); })()), "a", "h0"); });
test("h1", function () { assert_eq(String((function(){ return ds(7); })()), "b", "h1"); });
test("h2", function () { assert_eq(String((function(){ return ds(13); })()), "c", "h2"); });
test("hm", function () { assert_eq(String((function(){ return ds(5); })()), "d", "hm"); });
summary("constprop_waveB");
