// parametric probe generated by tools_agent/gen_waveb.py
// expectations baked from the node oracle at generation time
__EXP = null;
function run(p) {
    const OP = Object.freeze({ PUSH: 0, ADD: 1, SUB: 2, HALT: 3 });
    let sp = -1, st = [], pc = 0;
    while (pc < p.length) {
        const op = p[pc++];
        switch (op) {
            case OP.PUSH: st[++sp] = p[pc++]; break;
            case OP.ADD: { const b = st[sp--], a = st[sp--]; st[++sp] = a + b; break; }
            case OP.SUB: { const b = st[sp--], a = st[sp--]; st[++sp] = a - b; break; }
            case OP.HALT: return st[sp];
            default: return NaN;
        }
    }
    return NaN;
}
var prog = [0, 10, 0, 4, 1, 0, 2, 3];

test("run", function () { assert_eq(String((function(){ return run(prog); })()), "2", "run"); });
test("again", function () { assert_eq(String((function(){ return run(prog); })()), "2", "again"); });
summary("constprop_waveB");
