// parametric probe generated by tools_agent/gen_waveb.py
// expectations baked from the node oracle at generation time
__EXP = null;
function f() { const M = Object.freeze({ A: 7 }); return function () { return M.A; }; }
var g = f();

test("g", function () { assert_eq(String((function(){ return g(); })()), "7", "g"); });
summary("constprop_waveB");
