// parametric probe generated by tools_agent/gen_waveb.py
// expectations baked from the node oracle at generation time
__EXP = null;
var r = (function () { const M = Object.freeze({ A: 5 }); return M.A; })();

test("r", function () { assert_eq(String((function(){ return r; })()), "5", "r"); });
summary("constprop_waveB");
