// parametric probe generated by tools_agent/gen_waveb.py
// expectations baked from the node oracle at generation time
__EXP = null;
async function f() { const M = Object.freeze({ A: 6 }); return M.A; }

test("t", function () { assert_eq(String((function(){ return typeof f(); })()), "object", "t"); });
summary("constprop_waveB");
