// parametric probe generated by tools_agent/gen_waveb.py
// expectations baked from the node oracle at generation time
__EXP = null;
const M = Object.freeze({ A: 1, B: 2, S: "x" });
let acc = 0;
outer:
for (let i = 0; i < 2; i++) {
    acc += M.A;
    for (let j = 0; j < 3; j++) {
        if (j === 1) { acc += M.S.length; continue outer; }
        acc += M.B;
    }
}

test("acc", function () { assert_eq(String((function(){ return acc; })()), "8", "acc"); });
summary("constprop_waveB");
