// parametric probe generated by tools_agent/gen_waveb.py
// expectations baked from the node oracle at generation time
__EXP = null;
const M = Object.freeze({ I1: 5, I2: 9, S: "sx" });
function f(x) {
    switch (x) {
        case M.I1: return "i1";
        case M.S: return "s";
        case M.I2: return "i2";
        default: return "d";
    }
}

test("i1", function () { assert_eq(String((function(){ return f(M.I1); })()), "i1", "i1"); });
test("s", function () { assert_eq(String((function(){ return f(M.S); })()), "s", "s"); });
test("i2", function () { assert_eq(String((function(){ return f(M.I2); })()), "i2", "i2"); });
test("d", function () { assert_eq(String((function(){ return f(0); })()), "d", "d"); });
summary("constprop_waveB");
