// parametric probe generated by tools_agent/gen_waveb.py
// expectations baked from the node oracle at generation time
__EXP = null;
const M = Object.freeze({ A: 3, S: "yy" });
function f() {
    let r = M.A;
    try { r += M.S.length; throw new Error('x'); }
    catch (e) { r += M.A; } finally { r += M.A; }
    return r;
}

test("f", function () { assert_eq(String((function(){ return f(); })()), "11", "f"); });
summary("constprop_waveB");
