// GENERATED by tests/agent/features_du/gen/gen_using_probes.py — do not edit.
// Oracle: ECMAScript Explicit Resource Management spec (stage 3), cross-checked
// against the test262 explicit-resource-management corpus. node v22.23.1 cannot
// parse these probes (feature absent there; flag build is partial), so the
// baked expectations are spec-derived literals.
// This probe only parses on engines built with CONFIG_USING=y.

function __EV(name, fn) { test(name, fn); }
function __say(s) { (typeof print === "function" ? print : console.log)(s); }
function __res(id, log) {
  // a disposable whose [Symbol.dispose] records events
  var o = {};
  o.id = id;
  o[Symbol.dispose] = function () { log.push("dispose:" + this.id + ":" + (this === o)); };
  return o;
}

// Grammar/early-error contract. Every case is evaluated from a string so a
// rejection is a catchable SyntaxError rather than a file parse failure.

__EV("script-top-level-rejected", function () {
  assert_throws(function () { (0, eval)("{ using x = null; } using y = null;"); }, "SyntaxError");
});

__EV("block-level-allowed", function () {
  var ok = (0, eval)('{ using x = null; } true;');
  assert(ok === true, "block-level using must parse");
});

__EV("await-using-outside-async-rejected", function () {
  assert_throws(function () { (0, eval)("function f(){ await using x = null; }"); }, "SyntaxError");
});

__EV("using-requires-initializer", function () {
  assert_throws(function () { (0, eval)("function f(){ using x; }"); }, "SyntaxError");
});

__EV("single-statement-context-rejected", function () {
  assert_throws(function () { (0, eval)("if (1) using x = null;"); }, "SyntaxError");
});

__EV("labelled-statement-rejected", function () {
  assert_throws(function () { (0, eval)("lbl: using x = null;"); }, "SyntaxError");
});

__EV("line-terminator-makes-it-expression", function () {
  // `using` [no LineTerminator] BindingIdentifier: with a newline it parses
  // as two statements (an expression statement on `using`, then `x = 1`).
  var f = new Function("var x = 'unset'; try { using\nx = 1; } catch (e) {} return typeof x;");
  // `using` alone throws ReferenceError (caught); the assignment never runs
  assert_eq(f(), "string");
});

__EV("using-as-identifier-still-works", function () {
  var using = 5;
  assert_eq(using + 1, 6);
  var o = { using: 7 };
  assert_eq(o.using, 7);
});

__EV("for-in-head-rejected", function () {
  assert_throws(function () { (0, eval)("for (using x in {}) {}"); }, "SyntaxError");
});

__EV("redeclaration-in-block-rejected", function () {
  assert_throws(function () { (0, eval)("{ using a = null; using a = null; }"); }, "SyntaxError");
});

__EV("var-conflicts-with-using-rejected", function () {
  assert_throws(function () { (0, eval)("function f(){ using a = null; var a; }"); }, "SyntaxError");
});

__EV("for-using-of-of-reads-using-as-target", function () {
  // `for (using of of [1])`: `using` is the assignment TARGET (never a
  // declaration when the binding name would be `of`); the iterable is the
  // identifier `of`, which is undeclared -> runtime ReferenceError.
  var err = __mustThrow(function () { (0, eval)("for (using of of [1]) {}"); });
  assert(err, "expected ReferenceError");
  assert_eq(err.constructor.name, "ReferenceError");
});

summary("using_grammar_matrix");
