// GENERATED by tests/agent/features_du/gen/gen_using_probes.py — do not edit.
// Oracle: ECMAScript Explicit Resource Management spec (stage 3), cross-checked
// against the test262 explicit-resource-management corpus. node v22.23.1 cannot
// parse these probes (feature absent there; flag build is partial), so the
// baked expectations are spec-derived literals.
// This probe only parses on engines built with CONFIG_USING=y.

function __EV(name, fn) { test(name, fn); }
function __say(s) { (typeof print === "function" ? print : console.log)(s); }
function __res(id, log) {
  // a disposable whose [Symbol.dispose] records events
  var o = {};
  o.id = id;
  o[Symbol.dispose] = function () { log.push("dispose:" + this.id + ":" + (this === o)); };
  return o;
}

var events;

__EV("reverse-order-two-resources", function () {
  events = [];
  { using a = __res("a", events), b = __res("b", events); events.push("body"); }
  assert_eq(events.join("|"), "body|dispose:b:true|dispose:a:true");
});

__EV("null-undefined-skipped", function () {
  events = [];
  { using a = null, b = undefined; events.push("body"); }
  assert_eq(events.join("|"), "body");
});

__EV("non-object-throws-typeerror", function () {
  var err = __mustThrow(function () { { using a = 42; } });
  assert(err, "expected throw");
  assert_eq(err.constructor.name, "TypeError");
});

__EV("object-without-dispose-throws", function () {
  var err = __mustThrow(function () { { using a = {}; } });
  assert(err, "expected throw");
  assert_eq(err.constructor.name, "TypeError");
});

__EV("non-callable-dispose-throws", function () {
  var err = __mustThrow(function () {
    var o = {};
    o[Symbol.dispose] = 42;
    { using a = o; }
  });
  assert(err, "expected throw");
  assert_eq(err.constructor.name, "TypeError");
});

__EV("method-lookup-at-registration", function () {
  events = [];
  var o = {};
  o[Symbol.dispose] = function () { events.push("dispose"); };
  var ran = false;
  { using a = o; ran = true; delete o[Symbol.dispose]; }
  assert(ran, "body must run");
  assert_eq(events.join("|"), "dispose");
});

__EV("capability-captured-at-declaration", function () {
  events = [];
  var cap = __res("cap", events);
  { using a = cap; cap = null; }
  assert_eq(events.join("|"), "dispose:cap:true");
});

__EV("nested-blocks-innermost-first", function () {
  events = [];
  { using o = __res("out", events); { using i = __res("in", events); events.push("mid"); } }
  assert_eq(events.join("|"), "mid|dispose:in:true|dispose:out:true");
});

__EV("dispose-alone-throws-propagates", function () {
  events = [];
  var err = __mustThrow(function () {
    { using a = { [Symbol.dispose]: function () { events.push("d"); throw new Error("boom"); } };
      events.push("body"); }
  });
  assert(err, "expected throw");
  assert_eq(err.message, "boom");
  assert_eq(events.join("|"), "body|d");
});

__EV("dispose-error-suppressed-into-body-error", function () {
  // body throws orig; dispose throws d1; d1 becomes the pending error and the
  // orig error is chained as .suppressed (SuppressedError(error=d1, suppressed=orig));
  // the dispose error (the newer one) is what propagates.
  var caught = null;
  try {
    { using a = { [Symbol.dispose]: function () { throw new Error("d1"); } };
      throw new Error("orig"); }
  } catch (e) { caught = e; }
  assert(caught, "expected throw");
  assert_eq(caught.constructor.name, "SuppressedError");
  assert_eq(caught.error.message, "d1");
  assert(caught.suppressed, "expected .suppressed");
  assert_eq(caught.suppressed.message, "orig");
});

__EV("body-error-suppressed-into-dispose-error", function () {
  // two resources: the second dispose throws over the first body error;
  // the final propagated error is the LAST disposition error.
  var caught = null;
  try {
    { using a = { [Symbol.dispose]: function () { throw new Error("e1"); } },
          b = { [Symbol.dispose]: function () { throw new Error("e2"); } };
      throw new Error("body"); }
  } catch (e) { caught = e; }
  assert(caught, "expected throw");
  assert_eq(caught.constructor.name, "SuppressedError");
  assert_eq(caught.error.message, "e1"); // reverse order: a (first) disposes last
  assert_eq(caught.suppressed.error.message, "e2");
  assert_eq(caught.suppressed.suppressed.message, "body");
});

__EV("this-and-mutations-visible-to-dispose", function () {
  events = [];
  var o = { n: 1 };
  var self = "no";
  o[Symbol.dispose] = function () { self = (this === o) ? "same" : "other"; events.push("n=" + this.n); };
  { using a = o; o.n = 42; }
  assert_eq(self, "same");
  assert_eq(events.join("|"), "n=42");
});

__EV("generator-yield-inside-using", function () {
  events = [];
  function* g() {
    using a = __res("g", events);
    yield 1;
    yield 2;
    events.push("end");
  }
  var got = [];
  for (var v of g()) got.push(v);
  assert_eq(got.join("|"), "1|2");
  assert_eq(events.join("|"), "end|dispose:g:true");
});

__EV("try-finally-ordering", function () {
  events = [];
  function f() {
    try {
      { using a = __res("u", events); events.push("block"); }
      events.push("after-block");
    } finally {
      events.push("finally");
    }
  }
  f();
  assert_eq(events.join("|"), "block|dispose:u:true|after-block|finally");
});

summary("using_block_matrix");
