// GENERATED by tests/agent/features_du/gen/gen_using_probes.py — do not edit.
// Oracle: ECMAScript Explicit Resource Management spec (stage 3), cross-checked
// against the test262 explicit-resource-management corpus. node v22.23.1 cannot
// parse these probes (feature absent there; flag build is partial), so the
// baked expectations are spec-derived literals.
// This probe only parses on engines built with CONFIG_USING=y.

function __EV(name, fn) { test(name, fn); }
function __say(s) { (typeof print === "function" ? print : console.log)(s); }
function __res(id, log) {
  // a disposable whose [Symbol.dispose] records events
  var o = {};
  o.id = id;
  o[Symbol.dispose] = function () { log.push("dispose:" + this.id + ":" + (this === o)); };
  return o;
}

var events;

__EV("break-disposes", function () {
  events = [];
  while (true) {
    { using a = __res("b", events); events.push("body"); break; }
  }
  assert_eq(events.join("|"), "body|dispose:b:true");
});

__EV("continue-disposes-per-iteration", function () {
  events = [];
  for (var i = 0; i < 2; i++) {
    { using a = __res("i" + i, events); events.push("it" + i); continue; }
  }
  assert_eq(events.join("|"), "it0|dispose:i0:true|it1|dispose:i1:true");
});

__EV("return-disposes-preserves-value", function () {
  events = [];
  function f() {
    { using a = __res("r", events); return 7; }
  }
  assert_eq(f(), 7);
  assert_eq(events.join("|"), "dispose:r:true");
});

__EV("return-inside-try-disposes-before-finally", function () {
  events = [];
  function f() {
    try {
      { using a = __res("t", events); return "v"; }
    } finally { events.push("finally"); }
  }
  assert_eq(f(), "v");
  assert_eq(events.join("|"), "dispose:t:true|finally");
});

__EV("throw-disposes-and-propagates", function () {
  events = [];
  var caught = null;
  function f() {
    { using a = __res("x", events); throw new Error("x1"); }
  }
  try { f(); } catch (e) { caught = e; }
  assert(caught && caught.message === "x1", "original error propagates");
  assert_eq(events.join("|"), "dispose:x:true");
});

__EV("labeled-break-crosses-two-scopes", function () {
  events = [];
  outer: {
    { using a = __res("in1", events);
      inner: { using b = __res("in2", events); break outer; } }
  }
  // innermost scope's resource first
  assert_eq(events.join("|"), "dispose:in2:true|dispose:in1:true");
});

__EV("initializer-throw-skips-rest", function () {
  events = [];
  var sideB = 0;
  var caught = null;
  function mk(id) { events.push("mk" + id); return __res(id, events); }
  function bad() { events.push("bad"); throw new Error("init"); }
  try {
    { using a = mk("a"), b = bad(), c = mk("c"); events.push("never"); }
  } catch (e) { caught = e; }
  assert(caught && caught.message === "init", "initializer error propagates");
  assert_eq(sideB, 0);
  // a was fully registered before b's initializer threw -> disposed;
  // c's initializer never ran.
  assert_eq(events.join("|"), "mka|bad|dispose:a:true");
});

__EV("second-initializer-throw-disposes-first", function () {
  events = [];
  var caught = null;
  function bad() { throw new Error("i2"); }
  try {
    { using a = __res("a", events), b = bad(); events.push("never"); }
  } catch (e) { caught = e; }
  assert(caught && caught.message === "i2", "initializer error propagates");
  assert_eq(events.join("|"), "dispose:a:true");
});

__EV("closure-observes-resource", function () {
  events = [];
  var log = "unset";
  function f() {
    using a = __res("c", events);
    return function () { log = "seen"; return a.id; };
  }
  var g = f();
  assert_eq(g(), "c");
  assert_eq(log, "seen");
  assert_eq(events.join("|"), "dispose:c:true");
});

summary("using_exit_matrix");
